Makefile

Switch to a more portable way of setting FLOW_VERSION env variable for
builds, so that the version gets threaded through in CI.

Fix flowctl version

---

crates/catalog/src/collection.rs
crates/catalog/src/error.rs
crates/catalog/src/snapshots/catalog__collection__test__register.snap
crates/catalog/src/specs.rs
crates/catalog/src/test_case.rs

The documents in a test verify step must be in lexicographical order,
according to the collection's key. This commit adds a verification
during catalog builds to verify that the documents are in the proper
order, so that we can fail fast when the user provides them out of
order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/62)

Validate that test verify step docs are ordered

---

Cargo.lock
crates/bindings/Cargo.toml
crates/bindings/build.rs
crates/bindings/cbindgen.toml
crates/bindings/flow_bindings.h
crates/bindings/src/extract.rs
crates/bindings/src/lib.rs
crates/bindings/src/service.rs
crates/bindings/src/upper_case.rs
crates/catalog/Cargo.toml
crates/derive/src/extract_api.rs
crates/derive/src/snapshots/derive__extract_api__test__extractor_service.snap
crates/protocol/src/cgo.rs
crates/protocol/src/lib.rs
go/bindings/extract.go
go/bindings/extract_test.go
go/bindings/service.go
go/bindings/service_test.go
go/bindings/upper_case.go

A Service looks like a bidirectional channel, but is one which is
synchronously polled to send and receive framed message code and data
payloads. It's intended as a fundamental building block for building
bidirectional in-process streaming services that interoperate between
Go and Rust -- an interface which is a heck of a lot faster than gRPC.
It achieves zero-copy semantics by pushing Go []byte buffers down
into CGO invocations, and surfacing Rust-owned []byte arenas and
Frame payloads. There are some rules callers need to adhere to,
such as not scribbling "sent" memory until Poll() is called, and
not referencing Rust-owned memory returned by Poll() after _another_
Poll() call is made.
It amortizes the CGO overhead by vectorizing dispatch. On the Rust
side, some common functions are …

bindings: add crate and Go module with Service inter-op mechanism

---

go/ingest/apis.go
go/ingest/apis_test.go
go/ingest/http_api.go
go/ingest/http_api_test.go

Adds an ingestion endpoint for ingesting a single document into a single collection from a single http request. This endpoint is meant to simplify "webhook" integrations by allowing a client to simply POST to a collection's endpoint, as long as the data validates against the collection's schema.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/90)

Add an ingestion endpoint for a single document

---

crates/models/src/names.rs
crates/models/src/tables/behaviors.rs
crates/models/src/tables/macros.rs
crates/models/src/tables/mod.rs

"names" module, along with "tables", are now the *only* places for
cross-project domain models.
Specifications from source loading will be made private in a future
commit.
Protobuf models are now encoded using proto-encoding, rather than JSON.
Update debug views to reflect this (and make identifying intra-model
changes easier).
Table changes:
- Add JournalRules
- Rework Transforms, flattening some formerly hoisted spec fields.
- Rework Materializations, again flattening fields.
- Rework TestSteps, flattening fields.
- Add NamedSchemas, which identifies `$anchor: Named` schemas of the catalog.
- Add BuiltTransforms & BuiltDerivations.
Also added a module for additional table behaviors.
--- …

models: add `names` and updated `tables`

---

go/bindings/combine.go
go/bindings/combine_test.go
go/bindings/derive.go
go/ingest/ingest.go
go/runtime/derive.go
go/testing/driver.go

Materialization wants to work with them in packed form, so let the
client unpack if that's what they want to do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/108)

bindings: combiner passes packed rather than unpacked fields

---

go.mod
go.sum
go/testing/driver.go

This is intended to fix flakey tests caused by floating point operations
that result in very minor differences between actual and expected
numbers.
The maintainer of `jsondiff` opted to just expose a generic `CompareNumbers` function, which they've merged already. So I just copied the comparison function from my original PR there over into our repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/114)

flowctl test compares numbers using epsilon

---

.devcontainer/release.Dockerfile

Changes the flow docker image so that it's based on [node:lts-buster](https://hub.docker.com/layers/node/library/node/lts-buster/images/sha256-3729fcdfd2ae17fa75ae927289aa687cbdea1a2f392ba4fd341bee69da894ca0?context=explore). This is the latest LTS node release, based on debian 10. The main goal here was to ensure that nodejs is available inside the flow image. Technically, we could get away with much less than what's included in this image, at least at runtime. But this seems like a reasonable place to leave it for now.
There's corresponding changes in the flow-template repo to create a simplified dev container based on this. One of the features there (and the reason for the deletion of the `node` user) is that the devcontainer now runs as the (non-root) flow user.
---
This change …

change base docker image to node lts

---

crates/build/src/nodejs/mod.rs
examples/acmeBank.flow.ts
examples/common.flow.yaml
go.mod
go.sum
go/bindings/build_load.go
go/flowctl/cmd-apply.go
go/runtime/flow_consumer.go

* 🐛 It's '"NpmPackage"', not "NpmPackage" (it's a JSON-encoded enum).
`flowctly apply` now panics if an NPM package fails to be built.
* We can't rely on Etcd being sync-able in `flowctl apply`, as it's
often behind a `kubectl port-forward`.
* Code format acmeBank.flow.ts
* Add commented-out store URL for kubernetes test clusters.
* Update broker root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/134)

flowctl-apply: various tweaks and fixes from kubernetes testing

---

go.mod
go/bindings/combine.go
go/bindings/combine_test.go
go/bindings/derive.go
go/bindings/derive_test.go
go/flow/mapping.go
go/ingest/ingest.go
go/runtime/derive.go
go/runtime/materialize.go
go/testing/driver.go

Gather prometheus metrics for Combine and Derive.
This is a minimal starting point for Flow instrumentation to support
some Grafana dashboards. Instrumentation of rocksdb sizes isn't included
here because the intent is to add that to Gazette.
These may still need changed, so I don't want to merge just yet, but it's probably good to get feedback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/135)

Add basic prometheus metrics and trace lambdas

---

.devcontainer/release.Dockerfile
go/materialize/driver/sql2/.snapshots/TestSQLGenerator-postgres_flow_materializations
go/materialize/driver/sql2/.snapshots/TestSQLGenerator-postgres_gazette_checkpoints
go/materialize/driver/sql2/.snapshots/TestSQLGenerator-postgres_test_table
go/materialize/driver/sql2/.snapshots/TestSQLGenerator-sqlite_flow_materializations
go/materialize/driver/sql2/.snapshots/TestSQLGenerator-sqlite_gazette_checkpoints
go/materialize/driver/sql2/.snapshots/TestSQLGenerator-sqlite_test_table
go/materialize/driver/sql2/endpoint.go
go/materialize/driver/sql2/sqlgen.go

The snowsql cli is required by the snowflake materialization driver for
the materialization initialization process. This adds the CLI to the
docker image so that it's available in all environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/138)

Add snowsql to flow docker image

---

crates/json/src/schema/build.rs
crates/json/src/schema/types.rs

It's really easy to forget to quote `null` when it's used as a string in
JSON schemas. This adds a more helpful error message when deserializing
JSON schema `type` values. If you write `type: [string, null]`, you will
now see an error message telling you that "null" must be written with
quotes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/140)

More helpful error message for unquoted nulls

---

crates/build/src/nodejs/generators.rs
crates/build/src/nodejs/snapshots/build__nodejs__scenario_test__scenario.snap
examples/marketing/flow.ts
examples/net-trace/services.flow.ts
examples/re-key/flow.ts
examples/segment/flow.ts
examples/soak-tests/set-ops/flow.ts
examples/temp-sensors/flow.ts
examples/wiki/pages.flow.ts
flow_generated/flow/anchors.d.ts
flow_generated/flow/collections.d.ts
flow_generated/flow/interfaces.d.ts
flow_generated/flow/registers.d.ts
flow_generated/flow/routes.ts
package.json

package.json is updated so that `npm run lint` uses
"flow_generated/tsconfig-files.json" as its source of files to lint.
An immediate benefit is that it unbreaks the experience of running
`flowctl test` on just a subset of a larger catalog. Currently that will
barf because the linter observes typescript files *not* configured under
the current typescript project and produces an error.
In doing this I realized that our current glob pattern doesn't capture
multiple levels of directory hierarchy, and that our linting was
actually broken. This commit includes a bunch of linter updates / fixes
to get linting passing as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/142)

typescript linting should use current project files

---

crates/build/src/nodejs/generators.rs
examples/all.flow.yaml
examples/source-schema/README.md
examples/source-schema/flow.ts
examples/source-schema/flow.yaml
flow_generated/flow/collections.d.ts
flow_generated/flow/interfaces.d.ts
flow_generated/flow/registers.d.ts
flow_generated/flow/routes.ts
flow_generated/flow/transforms.d.ts
flow_generated/tsconfig-files.json

Typescript stubs were being generated without importing the `transforms`
module, even when a transform source schema was used. This resulted in a
typescript compilation error since the `source` function parameter
references `transforms`. This now conditionally imports `transofrms`
during stub generation if any transforms in the file use a source
schema.
Also adds a source-schema example catalog with a brief README explaining
their use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/144)

Import transofrms when source schema is used

---

crates/build/src/nodejs/generators.rs
crates/build/src/nodejs/interface.rs
crates/build/src/nodejs/snapshots/build__nodejs__scenario_test__scenario.snap

To avoid linter errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/149)

typescript: generated stubs should use underscores

---

go/materialize/driver/snowflake/snowflake.go

Snowflake materializations add the client_session_keep_alive parameter,
which prevents authorization tokens from expiring after 4 hours of being
idle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/150)

Pass client_session_keep_alive for snowflake

---

crates/protocol/src/flow.rs
go/labels/labels.go
go/labels/labels_test.go
go/protocols/flow/flow.pb.go
go/protocols/flow/flow.proto
go/protocols/flow/shuffle_extensions.go
go/protocols/flow/shuffle_extensions_test.go
go/runtime/split_workflow.go
go/shuffle/read.go
go/shuffle/read_test.go
go/shuffle/reader_test.go
go/shuffle/subscriber.go
go/shuffle/subscriber_test.go

The ranges used for key and rclock values were inclusive at the
beginning and exclusive at the end. This ended up being a little tricky
to work with, as it required a special case for handling hashed values
at the MaxUint32 boundary. It also presented challenges when
constructing Flow 32 bit range specs from other (kinesis, for example)
ranges that use more bits to represent their ranges. Just using the high
32 bits from larger representations could result in 32 bit ranges where
begin == end (empty ranges), which require even more special cases.
The solution implemented here is to make these ranges inclusive on both
ends. This allows the ranges to fully represent all possible hashed
values, and requires no special cases for MaxUint32. Ranges where begin
== end are now also valid and …

Make Flow key and rclock ranges inclusive

---

crates/models/src/build/mod.rs
crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap
go.mod
go.sum
go/materialize/driver/webhook/driver.go

Webhooks use the endpoint address url as the ResourcePath. This means we need to return that ResourcePath from the webhook driver and thoroughly percent-encode it before sending it over to Gazette.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/170)

Set the ResourcePath in webhook driver validation

---

Makefile
go/capture/driver/airbyte/connector.go
go/capture/driver/airbyte/connector_test.go

Add tests for edge cases of parsing JSONL records from connectors.
No bugs were found in the original implementation.
Then improve parsing to avoid excessive copies of the written buffer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/178)

avoid copies in connector stdout & more tests

---

Cargo.toml

This should make debugging more consistent. Without this change it was impossible to (for example, on my machine) place a breakpoint in the file `collection.rs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/198)

Enable debug info in dev builds

---

Cargo.lock
crates/doc/Cargo.toml
crates/doc/src/inference.rs
crates/json/Cargo.toml
crates/json/src/schema/build.rs
crates/json/src/schema/mod.rs
crates/json/src/validator.rs
crates/json/tests/schema_test.rs

Resolves #196
Changes our JSON schema to use the `fancy-regex` crate so that
look-ahead and look-behind are supported. This brings us into compliance
with the JSON Schema standard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/201)

Switch JSON schema to use fancy-regex

---

.devcontainer/devcontainer.json
.devcontainer/github-ubuntu-2004.Dockerfile
.github/workflows/main.yml
Makefile

Also have Codespaces build the entire project on first initialization.
Fixes #191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/200)

downgrade from Go 1.16.7 => 1.16.6

---

go/shuffle/reader.go

Resolves #182 
Turns out that I wasn't able to reproduce this, but based on what I see in the code, it seems like this was indeed the cause of the flowctl run that overstays its welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/202)

Check for context cancellation in replay reads

---

README.md
crates/sources/src/scenarios/snapshots/sources__scenarios__endpoints_captures_materializations.snap
crates/sources/src/specs.rs
examples/acmeBank.flow.yaml

The postgres materialization config was changed from using 'dbname' to
'database'. This change updates the specs on the rust side to match
that. This also adds serde attributes to optional fields to prevent them
from being serialized if they are `None`. Without those attributes,
undefined fields were being serialized in the connector config as
explicit nulls.
Fixes #216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/217)

Update dbname to database in specs

---

.github/workflows/main.yml
Makefile

We'd like to consolidate on using GitHub's container registry.
We still reference the quay.io hosted images everywhere, so we can't reasonably remove that all at once. So we'll start by publishing the images to both registries, then we can update the quay.io references to use ghcr.io instead, then we can sunset quay.io entirely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/218)

Publish Docker images to ghcr.io

---

Makefile

I struggled a little bit at first to figure out how to build flowctl.. And then realized today that if the rust side changes it must be built beforehand. This just adds a default target and builds them both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/219)

Make the default target to build the rust side and then the go side

---

go/flow/js_worker.go

Changes the js worker to pass the npm package as a regular file path
instead of a relative file uri. This is because recent versions of npm
will not handle the relative file uri.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/235)

Pass npm-package as a regular path

---

go/testing/action.go
go/testing/driver.go
go/testing/graph.go
go/testing/graph_test.go

Since the testing cluster is also used by develop, I believe this check needs to be removed or logic needs to be added to handle logic from commit https://github.com/estuary/flow/commit/db72fc41f660ec1f7a5f41f0c2eaca3572c685bc as it triggers this panic when using a catalog that has readDelay (citi-bike example)
```
panic: expected DisableClockTicks to be set [recovered]
panic: expected DisableClockTicks to be set
goroutine 1 [running]:
go.gazette.dev/core/mainboilerplate.InitDiagnosticsAndRecover.func2()
/data/go/pkg/mod/go.gazette.dev/core@v0.89.1-0.20210914224834-2d07306a0edb/mainboilerplate/diagnostics.go:46 +0x77
panic(0x2a506c0, 0x30471e0)
/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/estuary/flow/go/testing.(*Cluster).Advance(0xc0000dd680, 0x9d29229e0000, 0x2d5e539, 0xd) …
```

Fix panic when running in develop mode with readDelay.

---

go/capture/adapter.go
go/capture/driver/airbyte/connector.go
go/capture/driver/airbyte/connector_test.go
go/flowctl/cmd-develop.go
go/flowctl/cmd-test.go
go/materialize/adapter.go
go/runtime/capture.go
go/runtime/materialize.go
go/shuffle/read.go
go/shuffle/read_test.go
go/shuffle/reader.go

See individual comments. I observed some crashes from `flowctl` due to poorly behaved materialization connectors (because, to be fair, I was kill -9'ing them).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/242)

assorted fixes from attempting to reproduce snowflake timeouts plus backoff cancellation

---

crates/json/Cargo.toml

Our `json` create directly depends on `bitvec`, but we also on `nom` in a different crate. `nom` also depends on `bitvec`. We've not specified a version, but rather relied on Cargo to resolve a working version for
`bitvec`.
Now, `bitvec`'s `0.20.0` release introduced some semver breaking changes. `nom` has `bitvec` pinned at `0.19`. This causes Cargo to resolve `flow`'s dependency on `bitvec` to be `0.19`, rather than the latest `0.2x.x` release.
However, other crates which depend on our `json` crate to fail to pickup the `nom` constraint. This allows them to resolve `bitvec` to the `0.2x.x` releases. This are incompatible with the code we've written in the `json` crate.
Pinning `bitvec` to the `0.19.x` releases prevents dependent crates from trying to use an incompatible version of …

Pin `bitvec` dependency to 0.19

---

.devcontainer/release.Dockerfile
scripts/flowctl.sh

Because of this issue with Docker For Mac https://github.com/docker/for-mac/issues/5831
Using the flowctl.sh script does not work on M1 Macs when it is using Node 16. This PR reverts back to Node V14 which is the LTS release anyhow and does include the nullish collating operator which I understand was the main driver for upgrading Node.
It also adds a command option to ensure the flow docker image is up to date as part of the `flowctl.sh` script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/245)

Revert nodejs to v14 LTS release

---

go/capture/driver/airbyte/driver.go
go/materialize/driver/image/driver.go

MaterializationSpec is shared with the catalog KeySpace and must be copied.
Audit and document this restriction in drivers.
Tested:
* Started with a `flowctl develop` catalog having a built-in Snowflake materialization
* Executed `flowctl shard split` while that catalog was running (1 -> 2 shards).
* Transitioned the catalog materialization in-place to using the `materialize-snowflake` connector.
* Executed `flowctl shard split` 2x while _that_ catalog was running (2 -> 4 shards).
Issue #247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/248)

capture/materialize: in-process drivers must deep copy specifications

---

go/capture/driver/airbyte/connector.go
go/capture/driver/airbyte/connector_test.go
go/materialize/driver/image/driver.go

The `airbyte.RunConnector` is not converting an empty response from places like [this](https://github.com/estuary/connectors/blob/main/materialize-webhook/driver.go#L116), leaving nil resp variable unchanged, which causes `flowctl` to crash on [this line](https://github.com/estuary/flow/blob/master/go/flowctl/cmd-apply.go#L313).
The proposed fix sets the `nil` response variable, if not populated, to an empty response in `Apply` command of the `image` driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/253)

convert nil resp

---

go/flow/mapping.go
go/flow/mapping_test.go

Issue #255
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/256)

go/flow: when mapping hashes to partitions, account for inclusive KeyEnd

---

go.mod
go.sum
go/materialize/driver/image/driver.go
go/materialize/driver/postgres/driver.go
go/materialize/driver/postgres/sqlgen_test.go
go/materialize/driver/snowflake/snowflake.go
go/materialize/driver/snowflake/snowflake_test.go
go/materialize/driver/sqlite/sqlite.go
go/materialize/driver/sqlite/sqlite_test.go

This PR handles a refactoring of the protocols repo in https://github.com/estuary/protocols/pull/8.
In order to support BigQuery as well as any other SQLish database that does not directly have support in Go's *sql.DB driver framework, I needed to refactor the Endpoint in protocols into an Interface. As well, I somewhat standardized a Renderer for handling identifier and field encapsulation and sanitization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/254)

Handle refactoring in protocols repo to support other SQLish databases without support for Go's sql.DB driver framework.

---

Makefile
go/flow/.snapshots/TestConvergence-deletion-empty-cluster
go/flow/.snapshots/TestConvergence-deletion-full-cluster
go/flow/.snapshots/TestConvergence-list-partitions-at-build-request
go/flow/.snapshots/TestConvergence-list-shards-at-build-request
go/flow/converge.go
go/flow/converge_test.go
go/flow/journals.go
go/flow/mapping.go
go/flow/mapping_test.go
go/flowctl/cmd-api-activate.go
go/flowctl/cmd-api-await.go
go/flowctl/cmd-api-delete.go
go/flowctl/cmd-deploy.go
go/flowctl/cmd-local-data-plane.go
go/flowctl/cmd-shards-split.go
go/flowctl/cmd-temp-data-plane.go
go/flowctl/cmd-test.go
go/flowctl/main.go
go/runtime/capture.go
go/runtime/derive.go
go/runtime/flow_consumer.go
go/runtime/ops.go
go/runtime/task_term.go
go/runtime/testing.go
go/shuffle/read.go
go/shuffle/read_test.go
go/testing/action.go
go/testing/driver.go

`api delete` is a low-level API for deleting activated tasks and
collections of a catalog build.
Also add supporting convergence routines and tests to make it work.
`deploy` is a user-facing workflow which builds a catalog, deploys it to
a data-plane and, if asked, will await a Ctrl-C and then clean up the
deployment before exiting. It's a first attempt at tackling a super
common local development workflow, and is a replacement for the
(removed) `develop` command.
Also add `api await` which monitors the execution of catalog dataflow in
a configured data plane, and exits once all captures have completed one
invocation and all downstream effects have propagated.
Issue #287
--- …

flowctl: `api delete`, `api await`, and `deploy` commands

---

go/flowctl/cmd-combine.go
go/flowctl/cmd-temp-data-plane.go

Encountered the missing network paratemeres when writing tests for elastic search connector.
Although these changes are no longer needed, after some refactor to the connector test, it might worth adding these parameters for completeness. 
( Assuming there are no other considerations in setting the network parameters on the `temp-data-plane` and `comibine` commands.)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/307)

add network params

---

.devcontainer/release.Dockerfile
Makefile

Drop snowsql as it's no longer needed (moved to materialize-snowflake
connector).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/308)

Makefile: include `sops` in package artifact

---

crates/validation/src/errors.rs
crates/validation/src/schema.rs
crates/validation/tests/snapshots/scenario_tests__keyed_location_wrong_type.snap
crates/validation/tests/snapshots/scenario_tests__schema_reference_verification.snap
examples/reduction-types/append.flow.yaml
flow_generated/flow/collections.d.ts
go/flow/testdata/specs_test.flow.yaml

Further restrict disallowed types of keyed locations to include NULL (in addition to object, array, and fractional).
* Catalogs which previously used null-able keyed locations will now error (I'm unaware of any)
* Attempts to use a nullable location as a key (a collection key or shuffle key) will produce an error:
```
$ flowctl check --source flow.yaml 
requests-rollup.flow.yaml error at /collections/acmeCo~1requests-rollup.v1 :
location /deal/id accepts "null", "string" in schema file:///workspaces/acmeCo/requests-rollup.schema.yaml, but "null" is disallowed in locations used as keys
```
https://docs.estuary.dev/concepts/catalog-entities/collections#allowed-key-field-types
Two updates to make to this section:
* Null …

require that keyed locations not be `null`

---

Makefile
crates/models/src/build/mod.rs
crates/models/src/lib.rs
crates/models/src/resources.rs
crates/models/src/schemas.rs
crates/models/src/tables/mod.rs
crates/models/src/tests.rs
crates/protocol/src/flow.rs
crates/sources/src/loader.rs
crates/sources/src/scenarios/snapshots/sources__scenarios__test__endpoints_captures_materializations.snap
crates/sources/src/scenarios/snapshots/sources__scenarios__test__test_case.snap
crates/sources/src/scenarios/test_test_case.yaml
crates/sources/tests/snapshots/schema_generation__catalog_schema_snapshot.snap
crates/validation/src/lib.rs
crates/validation/src/test_step.rs
crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap
flow.schema.json
go.mod
go.sum
go/flowctl/cmd-api-test.go
go/flowctl/cmd-test.go
go/testing/driver.go

Support a snapshot testing workflow through:
1) Allowing `documents` of ingest and verity test steps to be a relative URL, in addition to the current inline array of documents. If given as a URL, the file MUST be a JSON array of document objects.
2) Offering a `--snapshot` flag in `flowctl test` & `flowctl api test`, which will generate nicely formatted JSON encodings (array of documents) of actual documents produced into a collection during the test run.
Before this PR, users were required to either a) edit document fixtures and expectations by hand within the catalog, or b) copy and past document fixtures into test and verification steps. Users (I) would copy terminal output and tediously re-format it into the catalog test which is under development. …

enable snapshot testing workflow

---

README.md
go/flowctl/cmd-api-activate.go
go/flowctl/cmd-api-await.go
go/flowctl/cmd-api-delete.go
go/flowctl/cmd-api-test.go
go/flowctl/cmd-deploy.go
go/flowctl/cmd-shards-split.go
go/flowctl/cmd-temp-data-plane.go
go/flowctl/cmd-test.go
tests/run-end-to-end.sh

`flowctl` commands which interact with data planes, now ask the data plane what it's configured `--flow.builds-root` is, instead of requiring a `--builds-root` argument to be explicitly passed.
Similarly, `flowctl temp-data-plane` no longer takes a --builds-root, and instead uses a `./builds/` subdirectory of the temporary directory which is provisioned for the data plane.
Where before you passed `--builds-root`, now you don't.
The top-level README example is updated, and updates to the `flow-template` repository are required.
To my knowledge we hadn't documented this elsewhere yet.
Enjoy the fewer flags.
--- …

flowctl: remove --builds-root flag

---

go/connector/run.go

The default docker daemon configuration will cause all stdout/err output to be
persisted to disk, which results in eventual disk exhaustion. Previously, we
expected the daemon configuration to specify a more reasonable log-driver in
any environment in which Flow would run, but this turns out to be difficult in
environments such as codespaces, which don't give you direct control over the
daemon configuration. In any case, it's really easy to forget to configure the
default log driver, and there's no longer much use for running `docker logs`
now that we're publishing all connector stderr output to the ops logs
collections. So this changes Flow to always run connectors with docker log
collection disabled, which should prevent any future disk exhaustion without
anyone needing …

Disable docker logs for all connectors

---

go/runtime/capture.go
go/runtime/materialize.go

Fixes: #328 
In certain circumstances where a materialization or capture failed to properly
initialize, it may be possible for it to `Close` the client/delegate twice,
thus triggering a panic. This was actually observed in a materialization, but
was theoretically possible in a capture as well.
The second commit addresses the possibility that closing the capture delegate or materialization client may return a `context.Canceled`, which should be ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/327)

Prevent closing materialization/capture clients twice

---

site/docs/concepts/connectors.md
site/docs/guides/connect-network.md
site/docs/guides/create-dataflow.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL.md

Initial documentation on our support for SSH tunneling. This is time-sensitive because this capability is going to be exposed in the config manager early next week, and some documentation must be provided. 
3 files were added/changed:
* postgres connector doc - states that this connector supports SSH tunneling. Will add similar sections to other connectors as support is added, and take this out when we transition to a connector-independant workflow
* connectors concept doc - added a section for connecting to endpoints on a secure network. Long term, I imagine we'll want to break this out into separate docs, but give our current TOC structure and the amount of options available, I think it makes sense to put here for now
* New guide on setting up and configuring ssh …

Initial SSH docs - guide, connector section

---

.github/workflows/main.yml
Cargo.lock
Cargo.toml
control.Dockerfile
crates/control/Cargo.toml
crates/control/README.md
crates/control/config/base.toml
crates/control/config/development.toml
crates/control/config/production.toml
crates/control/config/test.toml
crates/control/src/bin/db_url.rs
crates/control/src/config.rs
crates/control/src/config/app_env.rs
crates/control/src/lib.rs
crates/control/src/main.rs
crates/control/src/routes.rs
crates/control/src/shutdown.rs
crates/control/src/startup.rs
crates/control/tests/it/connectors.rs
crates/control/tests/it/health_check.rs
crates/control/tests/it/main.rs
crates/control/tests/it/snapshots/it__connectors__list_connectors_works.snap
crates/control/tests/it/support.rs

closes #339 
Just a small step, but we have to start somewhere. Adds a `control` crate to the Flow repo. This houses a web server that will be the Control Plane API. There's currently a simple server, some rudimentary tests, and a system for basic application configuration.
If you want to try it locally, I'd recommend either:
```bash
$ cargo run
$ curl localhost:3000/health_check
$ curl localhost:3000/connectors
```
No user facing impact yet
I recommend walking through commit by commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/345)

Add Control Plane Skeleton

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL.md

Added instructions from [slack conversation](https://estuaryworkspace.slack.com/archives/C012S5U0WP2/p1643151353092500?thread_ts=1643151253.092400&cid=C012S5U0WP2) to connect to RDS postgres. 
Modified somewhat to instruct user to choose SSH tunneling since that's all we support right now; removed the bit about IP access because we don't have an IP range.
Nested under Postgres connector docs with the assumption that users that need it will start there. Links to SSH docs included to make it a complete workflow 
I _think_ this should work but might be missing some details needed to get SSH + RDS to work together
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM …

Add RDS section to Postgres connector docs

---

site/docs/concepts/README.md
site/docs/concepts/advanced/logs-stats.md
site/docs/reference/Connectors/_category_.json
site/docs/reference/organizing-catalogs.md
site/docs/reference/reduction-strategies/_category_.json
site/docs/reference/working-logs-stats.md

We're not quite ready to document stats because they're not as easy to access/work with yet, but documentation for logs  was also missing. 
Two new pages: Added a conceptual page under Advanced concepts. Broke off the section on accessing logs to be a separate doc under Reference, though I'm open to combining the two or moving it elsewhere. 
In the future, the plan is to cover parallel aspects of stats in subsections of these same two docs.
No shortlinks, don't think we need to add any either (?)
YAML samples need particular attention.. especially the example using the webhook connector.
--- …

Add logs documentation, placeholder for stats

---

crates/protocol/src/consumer.rs
go.mod
go.sum
go/flow/converge_test.go
go/protocols/capture/pull_client.go
go/protocols/capture/pull_client_test.go
go/protocols/materialize/client.go
go/protocols/materialize/client_transactor_test.go
go/runtime/capture.go
go/runtime/materialize.go
go/runtime/task_term.go
go/shuffle/read.go
go/shuffle/read_test.go
go/shuffle/reader_test.go

See individual commits for fixes to #350 & #352. No behavior or documentation changes.
See also the related gazette fix: https://github.com/gazette/core/pull/315
Testing:
* #352 is a challenging / timing dependent reproduction, but I'm pretty confident this is the underlying cause. New unit tests are added.
* #350 and gazette/core#314 were manually confirmed by running a catalog that mixed a polled & streaming capture, along with a materialization, and excercising:
* Multiple timed polling intervals.
* Multiple deployments of the same catalog tasks, such that their specs were updated.
* Multiple unassignments of the running materialization to re-create the conditions of assigning to the same reactor & slot, to confirm the "delete and re-create" semantics were honored.
---
This change …

runtime: fix five bugs

---

crates/protocol/src/consumer.rs
go.mod
go.sum

Updating to the latest version of Gazette which the underlying `unassign` command from Gazette and the accompanying proto changes.
See:
- https://github.com/gazette/core/pull/316
Supports adding the shard supervisor cron job to the k8s environments.
TODO: document unassign in Gazette docs
This is a draft while I work on the shard supervisor cron job. I can't build docker images locally, so I needed to push this to build the image for testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/322)

Update gazette dependency

---

go/runtime/derive.go
go/runtime/materialize.go
go/runtime/task_term.go
go/shuffle/api_test.go
go/shuffle/read.go
go/shuffle/read_test.go
go/shuffle/reader.go
go/shuffle/reader_test.go
go/shuffle/ring.go
go/shuffle/ring_test.go

Shuffled reads now log to the ops.Logger, and are controllable using a
per-shard log level.
Do a comprehensive audit and update of the debug logging
we have in place around journal reads.
Issue #355
The `shards: {logLevel: debug}` stanza of a catalog task (derivation or materialization) now authors debug logs into the operations log.
No documentation impacts, as this simply makes ops logs more functional / comprehensive.
nada
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/362)

go/shuffle: audit and update logging, and use ops.Logger

---

go.mod
go.sum
go/runtime/ops.go
go/shuffle/read.go
go/shuffle/reader.go
go/shuffle/ring.go

Substantially increase the read cancellation timeout, from ~65 seconds to ~35 minutes.
Investigation of read amplification highlighted that mixing (relatively) frequent cancellations,
aggressive buffering, and connector transactions that regularly took ~2-3 minutes results
in pretty extravagant numbers of surplus reads from Gazette.
Relaxing this cancellation appears to have wholly resolved the problem.
Otherwise, add more telemetry.
* Support `pprof.Labels` so that we can associate specific shards, builds, and journals to goroutine traces (`debug=1`) and profiles.
* Add a new metric which surfaces the polling state of each ongoing shuffled journal read undertaken by a shard. This is helpful for understanding which specific journal(s) a shard is waiting for data from, …

read & debugging telemetry

---

site/docs/reference/Connectors/materialization-connectors/BigQuery.md
site/docs/reference/Connectors/materialization-connectors/Rockset.md
site/package-lock.json

Add docs for bigquery connector. 
created new shortlink for future (verify after merge & deploy)
https://go.estuary.dev/materialize-bigquery
- Roles in the [README](https://github.com/estuary/connectors/tree/main/materialize-bigquery#readme) didn’t align exactly with the names of roles found in the GCS/bigquery help. I went with Google’s version, but this is worth verifying that I picked the right ones.
- In some connector docs (like Postgres) we give step-by-step setup to walk people through meeting the prerequisites. In others (Like Rockset) we don’t. This simply has to do with how intuitive setup would be for users of the particular endpoint. In this case, I didn’t add steps. If anyone has experience to …

bigquery connector docs

---

go/capture/driver/airbyte/driver.go

Parse `KeyPtrs`  as a list of segments, and pass it to the source DB connector.
This enables overriding the DB primary key if the keys specified for catalog collections differ from the DB primary keys, and in that case the catalog collection keys wins, according to [this logic](https://github.com/estuary/connectors/blob/main/sqlcapture/capture.go#L186-L195) 
To enable the key overriding, specify the key in the catalog capture collections. E.g. the following specification enables <user_id, created> to be the primary keys for storing data captured from a psql table `search_phrases`, which has no primary key specified in the DB.
```
collections:
deepsync/search_phrases:   # Table has no primary key
schema: search_phrases.schema.yaml
key: [/user_id, …
```

passing primary keys to source connector

---

.github/workflows/main.yml

This causes CI to fail when there is no `cargo-cache` binary in the cache.
This was helpful when I was working on the CI stuff on my branch, but it got left in accidentally in one place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/381)

ci: Remove extra logging

---

Cargo.lock
crates/control/Cargo.toml
crates/control/README.md
crates/control/config/development.toml
crates/control/config/test.toml
crates/control/src/cmd/serve.rs
crates/control/src/config.rs
crates/control/src/main.rs
crates/control/src/models/mod.rs
crates/control/src/services/builds_root.rs
crates/control/src/services/builds_root/gcs.rs
crates/control/src/services/builds_root/local.rs
crates/control/src/services/builds_root/mod.rs
crates/control/src/services/mod.rs
crates/control/src/startup.rs
crates/control/tests/it/support.rs

Adds `PutBuilds` and `FetchBuilds` services to control plane, for
interacting with the builds root. These services are initialized on
startup and are added as extension layers, so they're available to all
handlers.
**Workflow steps:** n/a
The workflow for local development is a little quirky due to the builds root being specified only as a URI. This means that in the config file, you must provide an absolute path to a builds root. It's currently set to `/var/tmp/flow-builds/` in `config/development.toml`. The pain point there is that if you add a build `foo` with one instance of the application, then another instance of the application won't see it, and you won't be able to create a second build with the same …

Adds builds_root module to control plane

---

.github/workflows/main.yml
Makefile
crates/flow_cli_common/src/lib.rs
go/connector/decrypt.go
go/flowctl-go/cmd-temp-data-plane.go
go/pkgbin/exec.go

`flowctl` now requires that external binaries it invokes are co-located
in its same executable directory. This was already the practice with
`flowctl-go`, so the behavior is now consistent for both.
Similarly require that `sops` be co-located in the current executable
directory.
Remove dependencies on GOPATH from Makefile.
Instead, Go binaries are directly built (using go build -o) into the
desired $PKGDIR location.
export PATH is also removed from the Makefile, to coerce binaries to
rely only on co-location within a package directory and to not shell out
to $PATH and hope for the best, as this is a frequent source of
challenges from unexpected / old / stale binaries.
None.
None.
None.
---
This …

build: tighten outputs and paths

---

site/docs/concepts/connectors.md

Adds config details for SSH on materialization connectors, per https://github.com/estuary/flow/pull/379
YAML samples are now provided for both the current capture connectors (ie, just postgres for now) and all materializations. I'm assuming in the future this will be consistent and we'll just have one standard config. 
Initially, I was going to just commit this directly and skip the PR, but it seemed worthwhile to make sure that _both_ configs are accurate. 
FYI, related doc changes per https://github.com/estuary/connectors/pull/143 were [already covered here](https://github.com/estuary/flow/commit/910925a97fe4fa2735fa9b56738153bbd08d1f1e). In hindsight, I probably should've included those on this PR too.
--- …

Docs - SSH for materializations

---

.github/workflows/main.yml

See https://github.com/google-github-actions/setup-gcloud/issues/539
Github actions are failing at the moment because of this: https://github.com/estuary/flow/runs/5642694619?check_suite_focus=true#step:6:73
--- …

github workflows: fix gcloud branch pinning to @v0

---

go/protocols/materialize/sql/driver.go

We were previously raising a validation error when `delta_updates` was
altered for an existing materialization binding. That was done based on
the general principle that it's easier to relax restrictions than to
introduce new ones, not to address some specific correctness issue. Now
we have an actual use case where it's desirable to change an existing
binding from regular to delta-updates mode, and so this relaxes that
validation to allow it. This preserves the restriction on changing
`delta_updates` from `true` to `false`, since that seems to guard
against a greater potential for problems.
For an existing SQL materialization binding (one that has been applied), the `delta_updates` property can now be changed from `false` to `true` (but not the other …

Allow enabling delta updates on materializations

---

site/docs/guides/connect-network.md
site/docs/reference/Connectors/materialization-connectors/PostgreSQL.md
site/docs/reference/Connectors/materialization-connectors/README.md

Adds docs for materialize-postgres. 
Tested the connector via SSH to a Google Cloud database, and added docs to cover a few gotcha's there. I intend to test in AWS and Azure too, but don't have time immediately and want to get the essentials pushed out. 
- Config descriptions and titles were added by me, referencing source-postgres, because none were provided by this connector. Similarly, there was no README, which I would otherwise reference.
- The fields that are flagged as required seemed a bit odd to me - I feel like they should _all_ be. But this is what came out of the schemalate markdown generator, so...
-  Another thing that we found during testing that strikes me as odd: SSH to a hosted DB on Gcloud required that the DB use a _private_ …

Docs - materialize-postgres

---

Cargo.lock
crates/models/Cargo.toml
crates/models/src/lib.rs
crates/models/src/resources.rs
crates/sources/Cargo.toml
crates/sources/src/loader.rs
crates/sources/src/scenarios/mod.rs
crates/sources/src/scenarios/snapshots/sources__scenarios__test__inline_nested_catalogs.snap
crates/sources/tests/snapshots/schema_generation__catalog_schema_snapshot.snap
flow.schema.json

In addition to base64 values. This is more ergonomic in some cases,
as inner JSON documents can be directly contained in the catalog without
being obfuscated through base64 encoding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/430)

models: allow inline resource contents to be JSON

---

go/protocols/materialize/sql/spec_mapping.go

Changes the SQL generation for materialization tables to add `IF NOT
EXISTS`. This allows for manual creation of the target tables without
needing to also create and insert into `flow_materializations_v2`. A
newly supported workflow is to manually create the target tables, and
then apply the materialization.
- use `psql`, for example, to create the tables that you want to materialize into
- _then_ run `flowctl api activate` to apply the materialization
- The materialization should now use the tables you created manually
I'm thinking we should leave this undocumented for now, since I'm not really sure if this should be a blessed path for customizing the generated tables.
This was motivated by …

SQL materializations CREATE TABLE IF NOT EXISTS

---

.vscode/settings.json
Cargo.lock
Makefile
crates/connector_proxy/Cargo.toml
crates/connector_proxy/src/apis.rs
crates/connector_proxy/src/errors.rs
crates/connector_proxy/src/interceptors/airbyte_source_interceptor.rs
crates/connector_proxy/src/interceptors/network_proxy_capture_interceptor.rs
crates/connector_proxy/src/interceptors/network_proxy_materialize_interceptor.rs
crates/connector_proxy/src/libs/stream.rs

- Refactoring stream macros to use `futures` crates StreamExt and TryStreamExt methods instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/435)

Connector Proxy stream refactor

---

go/protocols/materialize/sql/validate.go

- Field names over 63 bytes are not allowed in Postgres and will get truncated
- If there are multiple fields with such long names and they share a prefix that's 63 bytes long, they will become duplicate column names
- This PR introduces a limit of 63 bytes for all SQL materializations as a general rule
N/A
N/A
Also see: https://estuary-dev.slack.com/archives/C01G7CFNA8K/p1649772559301679
Solves https://github.com/estuary/connectors/issues/166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/440)

sql/validate: don't allow field names >63 bytes in length

---

site/docs/reference/Connectors/materialization-connectors/Elasticsearch.md
site/docs/reference/Connectors/materialization-connectors/Firebolt.md
site/docs/reference/Connectors/materialization-connectors/Parquet.md
site/docs/reference/Connectors/materialization-connectors/README.md

Adds docs for `materialize-s3-parquet` and `materialize-elasticsearch`. This catches us up on connector docs. 
With the exception of most of the `field_overrides` in elasticsearch, I wrote the property descriptions - they're either not present in the config or I wasn't able to find them.
Some outstanding questions because the original developer isn't here and there are no READMEs. Specifically, with Elastic, I used up my free trial a while ago and wasn't able to test, so this needs review from someone familiar with that platform. 
* Prerequisites and permissions for elastic - are these correct?
* Is there anything worth mentioning in the intro for the mechanism of this connector that'd be pertinent to the user?
--- …

Elasticsearch and S3-parquet connector docs

---

crates/doc/src/annotation.rs
crates/doc/src/inference.rs

resolves #439
- Supports `x-` prefixed fields in JSONSchema. This is a kind of convention to use these kinds of fields for custom behaviour. For example it is used here: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mailchimp/source_mailchimp/schemas/shared/addressMergeSegment.json#L9
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/441)

support x- fields in JSONSchema

---

site/docs/reference/Connectors/materialization-connectors/PostgreSQL.md

- Documents PostgreSQL's reserved words
N/A
https://docs.estuary.dev/reference/Connectors/materialization-connectors/PostgreSQL/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/444)

docs: document PostgreSQL reserved words

---

crates/connector_proxy/src/errors.rs
crates/connector_proxy/src/interceptors/network_tunnel_capture_interceptor.rs
crates/connector_proxy/src/interceptors/network_tunnel_materialize_interceptor.rs

- Refactor usages of or_bail and replace them with mapping the error to a custom error in customer-proxy
- N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/448)

connector-proxy: replace or_bail usages with map_err to custom err

---

crates/network-tunnel/src/interface.rs

- The `tunnelType` field was causing an error in parsing because we were denying unknown fields in this enum. The `tunnelType` is not necessary for parsing this configuration in Rust using Serde.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flo …

network-tunnel: fix `tunnelType` causing parse failure

---

crates/network-tunnel/src/interface.rs

- Remove `tunnelType` since it's unnecessary for parsing of network tunnel config
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/453)

network-tunnel: remove `tunnelType` from network tunnel config

---

crates/connector_proxy/src/main.rs

- We used to eat up stderr of connector and only output it in case of error. With this change it's just forwarded to the parent stderr.
Solves #455 
N/A
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/456)

connector-proxy: let delayed process inherit stderr

---

crates/connector_proxy/src/connector_runner.rs
crates/connector_proxy/src/libs/command.rs
crates/connector_proxy/src/main.rs
crates/network-tunnel/src/main.rs

- Use `Stdio::inherit()` for stderr of child process in connector-proxy, this simplifies the logic and removes the need for a manual copy in of stderr. We don't process anything of the stderr anyway.
- Because we used to join our stdin/stdout streams concurrently, rather than in parallel, if one of them was stuck, it would block all the others from working as well. So I changed that to use a parallel copy which allows the stdin to reach the process.
- Added a test with `tail -f` (which will not terminate its stdout until an EOF in stdin is received) to test this: with the concurrent approach, this gets blocked forever, with the parallel approach and stderr being inherited, this allows the EOF in stdin to reach the process without being blocked by the stdout and exits as …

connector-proxy: inherit stderr for child and parallelize streaming of I/O

---

site/docs/reference/Connectors/capture-connectors/gcs.md

Documents the workflow enabled by https://github.com/estuary/connectors/pull/168
Just a few explanatory paragraphs, and then basically used the same config sample from the PR comment (with slight changes). This is a workflow for advanced users/admins that should be documented but doesn't need to be accessible for all users, so docs aren't very in-depth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/459)

Add service account impersonation section to source-gcs docs

---

crates/connector_proxy/src/errors.rs
go/connector/run.go

- Pass `--log.level` in connector runner to connector proxy
Pass `--log.level` to flowctl and see it being passed to connector proxy.
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/461)

go/connector/run: pass --log.level to connector proxy

---

crates/doc/src/inference.rs
crates/json/Cargo.toml
crates/json/benches/github_events.rs
crates/json/benches/testdata/github-event.schema.json
crates/json/src/schema/build.rs
crates/json/src/schema/index.rs
crates/json/src/schema/intern.rs
crates/json/src/schema/mod.rs
crates/json/src/validator.rs

For the `properties` and `required` keywords, by:
1) Having Application::Properties use direct string comparison rather
than interning. Interning is not fundamentally required for properties
as the keyword has no look-back requirement (where we must check
if the property was seen long after we've processed it). This lets
schemas scale to an arbitrary number of properties.
2) Adding Application::Inline as an in-place application has no schema
keyword. `required` properties of a schema may be pushed down into
Inline applications on an as-needed basis. This is done by deferring
processing of `required` keywords until the intern table size is known,
and then overflowing extra entries into Inline sub-schemas.
This is still correct because `required` is an embarrisingly-parallel
keyword to …

json: remove the 64-property limit in schemas

---

crates/connector_proxy/src/connector_runner.rs
crates/connector_proxy/src/libs/airbyte_catalog.rs
crates/connector_proxy/src/libs/command.rs
crates/connector_proxy/src/main.rs

- Delayed execution was not passing the `--log.level` and so a good chunk of logs were lost and made debugging harder
- The `tracing` macro calls were not actually printing the message for some reason, an empty log was being printed. I changed it to use `"{}"` as a format string and now it works.
- Log stuff from Airbyte connectors and pass `--log.level`
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/471)

connector-proxy: fix log printing in delayed execution

---

crates/connector_proxy/src/connector_runner.rs
crates/schemalate/src/firebolt/firebolt_queries.rs
crates/schemalate/src/firebolt/firebolt_types.rs

- Non-lowercase column names must be quoted, otherwise they are considered to be lowercase, and this causes issues when the flow documents have non-lowercase keys.
- Quote columns that are not lowercase
- Fixes https://github.com/estuary/connectors/issues/196
- Use a flow document with non-lower-case keys
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/479)

schemalate/firebolt: quote column names that are not lowercase

---

.github/workflows/main.yml

cancel in progress workflows for the same ref to avoid old actions from
overriding newer actions
- Fixes #481 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/482)

github actions: concurrency group based on workflow and ref + cancel

---

crates/connector_proxy/src/main.rs
go/connector/run.go

Fixes #467 
Connector containers were not always stopping in response to SIGTERM.
This changes how we handle signal propagation for connectors to rely on
docker's built-in 'tinyinit' process, which is enabled by passing the
`--init` argument to `docker run`. This removes the signal handling from
connector-proxy, since it's no longer required and would likely just be
confusing to readers.
Have a capture shard that fails for just about any reason, apart from the connector itself exiting non-0. In this case, the connector container used to stay running, even after the shard was unassigned. With this change, the connector is now stopped when the shard is unassigned or if the shard spec changes. …

Use docker --init for connector signal propagation

---

crates/parser/src/lib.rs
crates/parser/src/schema_generator/mod.rs
crates/parser/src/schema_generator/snapshots/parser__schema_generator__test__generator_with_multiple_values.snap

Implements the skeleton of what could be used to generate JSONSchema
from a JSON document. `schema_generator::generate(Metadata, &JSONValue)`
generates a JSON Schema from the JSONValue document provided. It is
expected that the document is a JSON object and will return an error if
the JSON value received is not an object (it will error on an Array
too).
All validations are generated inline currently and only support scalar
values. The tests here are built around the current implementation, they
will change as more features are added.
Also, the library itself is not being used anywhere and is inaccessible.
Once the library is going to settle, it will be added as a command in
`flow-parser` and will be usable from the CLI.
--- …

Parser: JSONSchema Generator

---

site/docs/reference/Connectors/materialization-connectors/Firebolt.md

Adds a table from list in #480 
**Notes for reviewers:*
Basically just want to make sure these are expressly forbidden, vs some other systems' reserved words which are permissible when they're quoted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/495)

Add reserved words to Firebolt connector docs

---

site/docs/reference/Connectors/capture-connectors/MySQL.md

The description under "Bindings" was completely incorrect for the `/namespace` field and contained a copy-paste error regarding `/stream`.
Also while I was skimming the docs I noticed that the `binlog_expire_logs_seconds` example was for 7 days, but our recommendation should be to aim for 30 days (since that's the default value that an unmodified MySQL install uses) -- 7 is just the minimum we're prepared to accept.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/498)

docs/MySQL: Fix some incorrect information

---

go/protocols/materialize/sql/driver.go

jsonSchema has the ability to toggle the ability to reference properties
so they aren't embedded in the properties field.
For fields that are defined in go struct's annotation, these are
automatically inlined and never referenced. However, a custom type can
be created and will be, by default, referenced.
So this flag seems to be application, for the most part, only affecting
custom types.
In practice, by enabling the `DoNotReference` flag, the custom type gets rendered differently. With the flag disabled:
```json
"properties": {
"credentials_json": {
"$schema": "http://json-schema.org/draft-04/schema#",
"$ref": "#/definitions/Credential",
}
},
"additionalProperties": false,
"type": "object",
"definitions": {
"Credential": {
"type": "string",
"title": "Credentials",
"description": "Google …
```

sqlDriver: Do not reference fields when generating JSONSchema

---

crates/network-tunnel/src/interface.rs

sshForwarding should have its own key under networkTunnel
- Use `flowctl discover` on a connector
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/508)

network-tunnel: fix JSONSchema of network tunnel

---

crates/schemalate/src/firebolt/firebolt_projections.rs
crates/schemalate/src/firebolt/firebolt_types.rs

- We rejected fields that were reserved words or had illegal characters
- This PR changes the behaviour to quote those fields instead
- Use a field which is a reserved word or does not meet the [identifier requirements](https://docs.firebolt.io/general-reference/identifier-requirements.html)
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/499)

schemalate/firebolt: quote reserved words and weird fields instead of rejecting

---

crates/parser/src/schema_generator/mod.rs
crates/parser/src/schema_generator/properties.rs
crates/parser/src/schema_generator/snapshots/parser__schema_generator__test__generator_with_multiple_values.snap
crates/parser/src/schema_generator/validations.rs

Because we'll eventually need to merge JSONSchema together, it's better
if the generator uses the doc's create and the Shape struct provided by
that crate. Some of the logic is similar to what schemars is using but
it allows set operations on shape which is something that doesn't exists
currently with schemars.
So, the flow for this changes a little bit where initially, the JSON
payload still has to be parsed into a `serde_json::Value` and be passed
to the generator. Then, it will convert the payload into a Shape that is
effectively a tree of multiple shapes which builds the structure of a
JSONSchema.
When the schema is parsed and ready to be rendered as a JSON Value, the
generator will create a `schemars::RootSchema` and convert all shapes
into this schema. This is because the logic of …

SchemaGenerator: Refactor the logic to use Shape

---

Makefile

Sops 3.7.3 is the first version to support using GCP KMS with workload
identity federation tokens. This updates our sops version so that we can
run sops in CI using WIF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/483)

Update sops to 3.7.3 for WIF support

---

crates/assemble/src/ops/mod.rs
crates/assemble/src/ops/snapshots/assemble__ops__test__ops_collections_are_generated.snap

Changes the generation of ops collections to only generate them when
they're not already defined in the sources. This allows a catalog source
yaml to include definitions of ops collections, and thus permits
migration to having them generated by the control plane agent instead of
flowctl.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/516)

Allow catalogs to define ops collections

---

crates/connector_proxy/src/libs/image_inspect.rs

- I added the protocol label to all our materialization images: https://github.com/estuary/connectors/commit/cf209eb2dc4469365384081461509ebd275f4ae4
- So we do not need this hack anymore.
Use a materialization image
N/A
- I also triggered a re-fetch of these new images on production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/518)

connector_proxy: remove docker image url hack for flow protocol inference

---

Cargo.lock
crates/connector_proxy/Cargo.toml
crates/connector_proxy/src/interceptors/airbyte_source_interceptor.rs
crates/doc/src/ptr.rs

use `doc::Pointer(vec).to_string()` in connector-proxy for translating primary key lists to JSON pointers. Removes our dependency on `json-pointers` crate (3rd party)
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/517)

doc/pointer: from_vec and Display implementations

---

crates/network-tunnel/src/interface.rs

- The new JSONSchema for NetworkTunnel is:
```
{
"title": "Network Tunneling",
"description": "Setup a network tunnel to access systems on a private network",
"advanced": true,
"oneOf": [
{
"type": "object",
"title": "SSH Forwarding",
"properties": {
"sshForwarding": {}
}
},
{
"type": "null",
"title": "Disabled"
}
]
}
```
- Resolves https://github.com/estuary/connectors/issues/231
Go to Network Tunnel tab in connector configuration page, you will see two variants: SSH Forwarding and Disabled. If you accidentally hit SSH Forwarding, you can select Disabled to be able to proceed.
Not that I'm aware of
Thanks a lot to @travjenkins for https://github.com/estuary/ui/pull/199, it's very useful!
--- …

network-tunnel: "Disabled" variant for Network Tunnel JSONSchema

---

crates/connector_proxy/src/libs/image_inspect.rs

Reverts estuary/flow#518
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/523)

Revert "connector_proxy: remove docker image url hack for flow protocol inference"

---

crates/connector_proxy/src/libs/network_tunnel.rs
crates/network-tunnel/src/errors.rs
crates/network-tunnel/src/sshforwarding.rs

- The UI was sending down a `networkTunnel: null` when using the "Disabled" case, and it was throwing an error
- Handling the case where `networkTunnel: null` by removing that key, but not starting a network tunnel
- Use "Disabled" in UI for network tunnel configuration or pass `networkTunnel: null` manually
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/526)

connector_proxy: consider null values of networkTunnel

---

crates/connector_proxy/src/connector_runner.rs
tests/end-to-end.expected

- Bubble up exit status errors from Airbyte connectors
- Regression from #512 🤦🏽 
N/A
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/540)

connector_proxy: bubble up exit status errors from airbyte connectors

---

crates/connector_proxy/src/connector_runner.rs

- We saw this `unwrap` in alerts channel, it happens if the connector exits abruptly and the receiver of the channel is dropped.
- Add a better error message to avoid confusions.
Resolves #530 
N/A
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/531)

connector_proxy: handle channel send error gracefully

---

crates/connector_proxy/src/libs/image_inspect.rs
go/connector/run.go
go/flowctl-go/cmd-api-spec.go

This reverts commit 4d246d8641806e964c5535ec2737f465f5838dd8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/524)

cli + connector_proxy: support labels for materialization images + backward-compatibility hack

---

go/protocols/capture/coordinator.go
go/protocols/capture/pull_client_test.go
go/protocols/capture/push_server_test.go
go/runtime/capture.go
go/runtime/connector_store.go
go/runtime/connector_store_test.go
go/runtime/materialize.go

Not all recovery log commits necessarily imply an updated driver
checkpoint. Refactor the capture runtime to update driver checkpoints
within ConsumeMessage, rather than StartCommit.
Update the capture protocol to make these semantics clearer and harder
to mis-use.
Manually tested with a capture that exits EOF without writing a
checkpoint.
Fixes #541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/542)

captures: separate driver checkpoint update from log commit

---

.github/workflows/main.yml
Cargo.lock
crates/connector_proxy/src/connector_runner.rs
crates/connector_proxy/src/libs/network_tunnel.rs
crates/network-tunnel/Cargo.toml
crates/network-tunnel/src/errors.rs
crates/network-tunnel/src/interface.rs
crates/network-tunnel/src/sshforwarding.rs
site/docs/concepts/connectors.md
site/docs/guides/connect-network.md
tests/run-all.sh
tests/run-end-to-end.sh
tests/source-test-no-state/flow.yaml
tests/sshforwarding/materialize-postgres.ssh.config.yaml

Reverts estuary/flow#532
Is re-deployment of #528 
- Switches from using `thrussh` to shelling out to OpenSSH binaries (`ssh`) for creating a network tunnel
- This means it is now necessary for connectors to have OpenSSH installed. This is done in https://github.com/estuary/connectors/pull/258.
- This changes the config spec, since now the user is part of the `ssh_endpoint` instead of being a separate key. Updates docs to mention the change in `ssh_endpoint`
- Also added a new cache action which reduces the total build time by about 40-50%, from ~45m to ~28m.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/535)

network-tunnel: switch to using openssh for tunnel

---

crates/network-tunnel/src/sshforwarding.rs

- Mark private key field as `secret`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/546)

network-tunnel: mark ssh private key as secret field

---

tests/run-end-to-end.sh

- The default `PGPASSWORD` can be set to `flow`

tests/end-to-end: set default PGPASSWORD=flow if not set

---

crates/validation/src/errors.rs
crates/validation/tests/snapshots/scenario_tests__collection_key_empty.snap

Adds a short link to the `CollectionKeyEmpty` error text. The new short link https://go.estuary.dev/Zq6zVB points at https://docs.estuary.dev/concepts/collections/#empty-keys which should hopefully give the user enough context to understand how to fix things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/547)

validation: Add short link to CollectionKeyEmpty error

---

crates/connector_proxy/src/connector_runner.rs
go/materialize/driver/sqlite/.snapshots/TestSpecification
go/protocols/materialize/go-schema-gen/generate.go
go/protocols/materialize/sql/driver.go

There are a few materialization connectors that currently aren't marking their secret fields as `secret`.
Unfortunately this wasn't as simple as adding `secret: true` to their schemas. The connectors which use the `sql/driver` package rely on it to generate their spec schemas. This package was missing the fixes for boolean schemas we already have in the connectors repo. While we'd like to eventually move the `sql/driver` package over to the connectors repo, there's a bit more untangling to do for that. In the meantime, we'll just copy these two functions over to `flow` so that we can correctly serialize the schemas in the materialization connectors.
1. Merge this PR
2. Bump the flow dependency in the connectors repo
3. Rebuild the affected images
4. …

Better Generated Go Schemas

---

go/flow/.snapshots/TestConvergence-list-partitions-at-build-request
go/flow/.snapshots/TestConvergence-list-recovery-logs-request
go/flow/.snapshots/TestConvergence-list-shards-at-build-request
go/flow/converge.go
go/flow/converge_test.go
go/flowctl-go/cmd-api-delete.go
go/testing/driver.go

Do not explicitly require they match on --build-id,
though we continue to *expect* that this is the case.
We were not explicitly checking build IDs of updated shards, so it seems
a bit silly to do it only for deletions.
In any case this level of transactional checking is now the
responsibility of the control plane. KISS.
Issue estuary/animated-carnival#24
Tested in combination with estuary/animated-carnival#25:
* Started a local control-plane + data-plane, with a side Postgres DB
* Create a capture and multiple materializations over a period of time,
with staggered deletions of materializations while creating others.
* Deleted all remaining tasks, and verified that all ApplyDelete RPCs
were run and all shards were removed, leaving an empty data-plane. …

relax `api delete` to remove named shards in all cases

---

site/docs/guides/connect-network.md
site/docs/reference/Connectors/capture-connectors/MySQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL.md

Per feedback from @dyaffe, these updates include:
SSH setup guide
- Instruct user to specify port 22 for ssh_endpoint
- Correct misleading notes referring to port 5432 - elaborate that 5432 is Postgres and 3306 is mysql
Source-postgres
- correct azure setup steps
- ensure that user connects to the correct instance before performing queries
- distinguish Postgres v14 queries from previous versions for cloud platforms (see note below)
Source-mysql
- Add setup steps for azure
- Add setup steps for google cloud
Regarding v14 vs previous version queries for postgres:
As a non-sql-expert, I had some trouble parsing out which queries, exactly, in the pre-v-14 versions for Google Cloud and Amazon steps would be replaced by `GRANT pg_read_all_data `. So, …

Doc updates for SSH, postgres, mysql

---

site/docs/reference/Connectors/capture-connectors/MySQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL.md
site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/amplitude.md
site/docs/reference/Connectors/capture-connectors/apache-kafka.md
site/docs/reference/Connectors/capture-connectors/exchange-rates.md
site/docs/reference/Connectors/capture-connectors/facebook-marketing.md
site/docs/reference/Connectors/capture-connectors/gcs.md
site/docs/reference/Connectors/capture-connectors/google-analytics.md
site/docs/reference/Connectors/capture-connectors/google-sheets.md
site/docs/reference/Connectors/capture-connectors/hubspot.md
site/docs/reference/Connectors/capture-connectors/intercom.md
site/docs/reference/Connectors/capture-connectors/mailchimp.md
site/docs/reference/Connectors/capture-connectors/stripe.md
site/docs/reference/Connectors/capture-connectors/zendesk-support.md

Adds connector docs for the following newly added sources
- amplitude
- intercom
- stripe
- zendesk support
I will update these shortlinks after merging:
Zendesk:
https://go.estuary.dev/9riGqC
https://go.estuary.dev/VHDFYJ
Stripe:
https://go.estuary.dev/k392Zj
https://go.estuary.dev/OhUbgL
Amplitude:
https://go.estuary.dev/94rlKl
https://go.estuary.dev/CTEm20
Intercom:
https://go.estuary.dev/3L0sGJ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/561)

Docs: amplitude, intercom, stripe, zendesk support

---

crates/connector_proxy/src/libs/network_tunnel.rs
crates/network-tunnel/src/sshforwarding.rs

This is a grab-bag of several fixes, basically what I did was try and misconfigure SSH forwarding in various common ways (forgetting to specify a username, inputting the wrong or malformed key data, inputting the wrong SSH server hostname/IP, etc) and tweaked things to try and make the reasons for those failures more obvious.
Concretely, this meant:
* Replacing the previous logic around detecting the `Entering interactive session` log message with a new mechanism which     uses the tokio `BufReader::lines()` and then looks at each output line individually to decide how to log it.
* Hard-coded some special cases for logging certain messages from `ssh` at `DEBUG` and `ERROR` levels, with the default being `INFO` for any message not otherwise handled.
* Explicitly giving the …

sshforwarding: Various tweaks to make failures debuggable

---

Cargo.lock
crates/connector_proxy/Cargo.toml
crates/connector_proxy/src/libs/network_tunnel.rs
crates/connector_proxy/src/libs/snapshots/flow_connector_proxy__libs__network_tunnel__test__extended_endpoint_schema-2.snap
crates/connector_proxy/src/libs/snapshots/flow_connector_proxy__libs__network_tunnel__test__extended_endpoint_schema.snap
crates/network-tunnel/Cargo.toml
crates/network-tunnel/src/errors.rs
crates/network-tunnel/src/networktunnel.rs
crates/network-tunnel/src/sshforwarding.rs

This is an attempt to implement the mechanism I described in https://github.com/estuary/flow/issues/513, which allows a top-level endpoint config property named `address` to serve as the `forwardHost/forwardPort` values for SSH tunneling (and replaces the `address` property with `127.0.0.1:$RANDOM_LOCAL_PORT` before invoking the connector).
It includes some additional logic which does a similar job when asked for the endpoint config spec, and omits the `forwardHost`, `forwardPort`, and `localPort` properties from the SSH config portion of the resulting schema IFF the main endpoint config schema contains a top-level `address` property.
It should be noted that the new logic is backwards-compatible in two ways:
- First, any existing captures/materializations which explicitly …

Simplified SSH Forwarding Configuration

---

go/flowctl-go/cmd-api-activate.go
go/flowctl-go/cmd-api-build.go
go/flowctl-go/cmd-api-delete.go
go/flowctl-go/cmd-api-discover.go
go/flowctl-go/cmd-api-spec.go
go/flowctl-go/cmd-check.go
go/flowctl-go/cmd-combine.go
go/flowctl-go/cmd-deploy.go
go/flowctl-go/cmd-discover.go
go/flowctl-go/cmd-temp-data-plane.go
go/flowctl-go/cmd-test.go
go/runtime/flow_consumer.go
tests/run-end-to-end.sh

Changes the default value of the --network argument to flowctl serve
consumer to be empty so that the host network will not be used by
default. This also removes the default from `temp-data-plane`, so
users who use that for running locally may want to pass `--network=host`
in order to connect to services running on localhost.
Using the host network in production would be bad because tasks that use ssh forwarding could end up using conflicting ports. This PR is primarily to address that issue.
If you run temp-data-plane locally, you'll probably want to add the `--network host` argument. Otherwise, no change.
No user-facing docs changes, since temp-data-plane isn't really a user-facing subcommand anymore.
**Notes for …

Don't use host network by default

---

Cargo.lock
crates/parser/Cargo.toml
crates/parser/src/config/character_separated.rs
crates/parser/src/config/mod.rs
crates/parser/src/config/snapshots/parser__config__test__config_schema_is_generated.snap
crates/parser/src/format/mod.rs
crates/parser/src/input/compression.rs

Adds support for Zstandard compression in the parser, allowing it to
parse files that are compressed using `zstd`. The parser should be able
to detect zstd compression in most, if not all cases, based on either
the `.zst` extension or the 'magic bytes' at the beginning of a
zstd-compressed file.
Users shouldn't need to do anything in order to use this feature. Files that are compressed using zstd should now "just work".
There's some minor impact to the open PR #569: `zstd` is now an allowable option for `compression`.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/574)

Parser support for zstd compression

---

site/docs/reference/Connectors/capture-connectors/amazon-s3.md
site/docs/reference/Connectors/capture-connectors/gcs.md

Changes documentation for source-gcs and source-s3 per 
https://github.com/estuary/connectors/pull/276 and https://github.com/estuary/flow/pull/556
Added info on the parser as a section to the connector docs themselves; didn't seem like quite enough info to warrant a separate page.
Config tables and YAML have also been updated.
I noticed a typo in the spec, in the description for `/csv/lineEnding` it's corrected here, but worth fixing at the source. 
* "withe" should be "with"
* Also, the md syntax for italicizing _either_ doesn't output correctly either in the UI or the docs. Might be best to just remove that.
--- …

Docs: new parser config for cloud storage

---

crates/parser/src/config/character_separated.rs
crates/parser/src/config/mod.rs
crates/parser/src/config/snapshots/parser__config__test__config_schema_is_generated.snap
crates/parser/src/format/character_separated/mod.rs
crates/parser/tests/csv_error_absorption_test.rs

Previously, the `errorThreshold` field was represented as an
`Option<ErrorThreshold>`, which meant that the default value was always
`null`. This changes the representation so that it no longer uses an
`Option` and instead uses the number 0 as the default. This is more
clear and user friendly, and renders better in the UI.
`null` is no longer a valid value for `errorThreshold` in the parser config. Use `0` instead. I don't think there's any endpoint configs that actually specified `null` though.
**Documentation links affected:** None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/573)

Change parser errorThreshold default to 0

---

go/parser/run.go

This allows the caller to signal that we should halt parsing. Without this change, the parser will continue to read documents from the source until it reaches the end of data even if the caller has encountered an error (or would for its own reasons prefer to stop).
N/A
N/A
Used by the latest changes to https://github.com/estuary/connectors/pull/278.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/579)

Bubble up errors returned from parser consumer

---

site/docs/concepts/connectors.md
site/docs/guides/connect-network.md
site/docs/reference/Connectors/capture-connectors/MySQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL.md

Updates documentation to reflect the new network tunnel config per https://github.com/estuary/flow/pull/563
Eliminated reference to older config, even though it's backward-compatible, because it's not expected to be pertinent to the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/580)

Docs: updated network tunnel config

---

crates/build/src/lib.rs

Bailing out early here causes the generated build database to be empty.
This ends up crashing the agent which expects a well-populated build
database.
1. Create a flow.yaml with a json schema which does not parse.
2. Run `flowctl api build` against it.
3. Inspect the generated build database and notice the complete lack of tables.
4. Checkout this branch.
5. Remove the old build database (they are additive, so old build errors stick around)
6. Rerun the build
7. Inspect the generated build database and see the npm packaging error in the `errors` table.
N/A
N/A
--- …

Log npm package errors as build errors

---

site/docs/concepts/advanced/_category_.json
site/docs/concepts/advanced/shards.md
site/docs/concepts/captures.md
site/docs/concepts/flowctl.md
site/docs/reference/Configuring-task-shards.md
site/docs/reference/Connectors/materialization-connectors/BigQuery.md
site/docs/reference/organizing-catalogs.md
site/docs/reference/working-logs-stats.md

users need to set minimum transaction duration to avoid running up against bigquery's table operations limitations. This PR adds this to the docs, along with all the required background information. This includes:
- new performance considerations section in BQ docs, plus step-by-step to change the appropriate setting
- changes to conceptual shards docs to discuss transactions
- Addition of a new reference page for shards config 
Plus some other random updates that aren't entirely related, but are necessary:
- instructions to download new flowctl binaries
- Remove references to some older `flowctl` commands `discover`, `shards split`
- update section about data discovery to discuss it as something that's only available in the UI
added a …

Docs: bigquery caveat, shards, transactions, plus flowctl

---

crates/build/src/lib.rs
crates/validation/src/errors.rs
crates/validation/src/lib.rs

Generating TypeScript types can fail if there are user schema errors.
Only proceed if validation is successful.
Tested manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/560)

crates/build: don't generate TS package if there are validation failures

---

crates/connector_proxy/src/libs/network_tunnel.rs
crates/connector_proxy/src/libs/snapshots/flow_connector_proxy__libs__network_tunnel__test__extended_endpoint_schema-2.snap
crates/network-tunnel/src/sshforwarding.rs

- Hide network tunnel config for connectors that do not have an `address` configuration
- Do not expose `forward_host`, `forward_port` and `local_port` as Network Tunnel configuration fields for user
- Still needs to wait until we are done with adding `address` to `materialize-postgres` as @willdonnelly mentioned [here](https://github.com/estuary/flow/issues/513#issuecomment-1189360127)
(anything that …

network-tunnel: hide tunnel config if there is no `address` field

---

site/docs/reference/Connectors/materialization-connectors/PostgreSQL.md

See https://github.com/estuary/connectors/pull/297
https://docs.estuary.dev/reference/Connectors/materialization-connectors/PostgreSQL/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/593)

docs: materialize-postgresql accepts address instead of host:port

---

README.md
examples/acmeBank.flow.yaml
site/docs/concepts/connectors.md
tests/citi-bike-success/flow.yaml
tests/materialize-logs.flow.yaml
tests/sshforwarding/materialize-postgres.ssh.config.yaml

This is a followon to https://github.com/estuary/connectors/pull/297 which replaced the 'host' and 'port' properties with 'address'. This commit modifies the test configurations to use 'address', and also a couple of other places where a 'host' property was mentioned in the context of `materialize-postgres`
The test changes ought to fix CI builds for the flow repository.
None, the main docs changes were actually done slightly before the `address` change landed, and this just fixes a handful of tests and examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/601)

Replace 'host' with 'address' for materialize-postgres

---

Makefile

The standard `test` (`[`) binary uses the syntax `[ foo = bar ]` for string equality comparison rather than `[ foo == bar ]`. This is easy to miss because many shells (like bash for instance) use their own builtin replacement which *does* accept `==`, but for whatever reason my setup was having trouble with that in the context of Makefile command execution.
For obvious reasons I have not tested this on a Mac, but in general I'd expect this change to be more likely to work in odd places, so hopefully it's fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/600)

Minor POSIX-compatibility fix to makefile

---

crates/validation/src/capture.rs
crates/validation/src/materialization.rs
crates/validation/tests/scenario_tests.rs
crates/validation/tests/validation_skipped_when_disabled.yaml
go/flowctl-go/cmd-api-activate.go
go/flowctl-go/cmd-api-delete.go
tests/citi-bike-success/flow.yaml

The problem that we observed is this. Say you have a capture or a materialization, and the system you're connecting to becomes unreachable in some way. It could be that someone changed the credentials, deleted the database, or anything else. In Flow, we often want to just disable these tasks so that we can reduce the noise of alerts, and then they can be resumed when the system comes back online. This was not possible because Flow would call into the connectors to `Validate` the specs when changing `/shards/disabled` from `false` to `true`. I also discovered that `flowctl api activate` would also call into the connector to `ApplyUpsert` disabled shards.
This PR updates the build step to skip the call to `Validate`, and also the activate step to skip the call to …

Allow disabling captures and materializations when the external systems are unreachable

---

crates/network-tunnel/src/main.rs
crates/network-tunnel/src/networktunnel.rs
crates/network-tunnel/src/sshforwarding.rs

- Attempt to resolve #598
- According to https://doc.rust-lang.org/std/process/struct.Child.html#warning it's possible for processes to become zombies if they are not `wait`ed on. In this case, in the `prepare` step we do not wait on the process, which means if there is any failure in the `prepare` step, we will end up with a zombie. This is likely to be the problem we saw a few days ago where network tunnel initialisation failed during `prepare` and we ended up not being able to spawn a fresh instance because of the socket being still in use.
- Fail the `prepare` step of network tunnel initialisation, the child `ssh` process must be killed.
N/A …

network-tunnel: cleanup child process in case of success and failure

---

crates/connector_proxy/src/interceptors/airbyte_source_interceptor.rs
crates/connector_proxy/src/libs/airbyte_catalog.rs

- Connector proxy now passes through `cursorField` from Airbyte spec of streams. This allows us to specify a cursor field for each stream (useful for source-firestore).
- Pass `cursorField` to a binding resource_spec, it's an optional array of strings
- - - …

connector_proxy: pass through cursorField in Airbyte connectors

---

crates/schemalate/src/firebolt/firebolt_queries.rs
crates/schemalate/src/firebolt/firebolt_types.rs

- We were only quoting column identifiers, but table names must also conform to the same identifier requirements
- Create a table with a special character such as `-`
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/623)

schemalate/firebolt: quote table name identifiers if necessary

---

README.md

These are condensed from the notes I took when getting Flow to build on my new M1 macbook. I left out a few more obvious issues such as the error you get when `go` or `protobuf` aren't installed, as I felt it was fairly obvious what the fix was.
One thought I had is that these issues may not all be M1-specific, especially openssl and llvm. Maybe it should all be under a "getting started" section? My default was to just keep it simple.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/627)

docs: Document some potential isues when building from scratch on an M1, and their resolutions

---

go/runtime/flow_consumer.go
go/runtime/task_term.go

The ops logs appender previously used the `Context` of the shard, which
caused log messages to be silently dropped as soon as the shard was
unassigned. This caused us to miss logs related to connector shutdown
because we generally shutdown connectors only after the shard context is
cancelled.
This change introduces a global `AppendService`, which is used by all
`LogAppender`s. This uses a context that will never be cancelled, and
thus should capture logs during the teardown of shards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/629)

Use a process-scoped Context for ops logs appender

---

crates/connector_proxy/src/libs/airbyte_catalog.rs

Closes https://github.com/estuary/connectors/issues/316
This fixes the `estuary.dev/tail` and `estuary.dev/range` `ConfiguredCatalog` field serialization. `alias` is only for [deserialization](https://serde.rs/field-attrs.html#alias), where as `rename` works for serialization as well. This matches up with the expected values in the protocol [go structs](https://github.com/estuary/flow/blob/02070f5ffee5a6583d1ced2bb7fdd7bd182c9c4b/go/protocols/airbyte/catalog.go#L107-L111) and also the [Rust Kafka connector](https://github.com/estuary/connectors/blob/89a0b84f68e22a3bea0111136afb631d7520c05c/source-kafka/src/catalog.rs#L27-L48).
It also fixes the formatting for values of `range`, which need to be [0-padded and 8 digits …

fix serialization of tail and range

---

crates/validation/src/errors.rs
crates/validation/src/schema.rs
crates/validation/tests/scenario_tests.rs
crates/validation/tests/snapshots/scenario_tests__keyed_location_pointer_is_malformed.snap

Add explicit validation over JSON pointer locations within the catalog.
Special case the "you missed the leading slash" condition from the more
obtuse "something else is invalid about your JSON pointer".
- - - …

validation: add user-friendly validation checks over JSON pointers

---

site/docs/concepts/connectors.md
site/docs/guides/connect-network.md
site/docs/reference/Connectors/capture-connectors/MySQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL.md
site/docs/reference/Connectors/capture-connectors/google-firestore.md
site/docs/reference/Connectors/capture-connectors/http-file.md
site/docs/reference/Connectors/materialization-connectors/PostgreSQL.md

Adds documentation for:
- Whitelisting the Estuary IP for source-postgres, source-mysql, materialize-postgres
- Fixing format issues found this week
- Messaging around slots for source-postgres (https://github.com/estuary/connectors/pull/331)
- Updates to source-firestore resource config (https://github.com/estuary/connectors/pull/319)
- Headers for source-http file (https://github.com/estuary/connectors/pull/321) - plan to follow up on this one so I can add more detail to the docs because I don't 100% get how this works 
Self-review for this one
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/657)

Docs: whitelisting IPs + various odds and ends

---

site/docs/guides/create-derivation.md

Adds a generalized user guide to creating a derivation with flowctl. 
This is much-0needed to accompany the existing [guide to create a ui-only dataflow](https://docs.estuary.dev/guides/create-dataflow/). 
The example scenario / code works, and is provided just to have some sort of basic reference, but it still might be nice to revisit in the future to provide something more compelling (especially because, as I found out today, source-hello-world _always_ outputs infinite greetings).
Create a derivation, start to finish, as if you were a new user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/654)

docs: add generic derivation guide

---

crates/json/Cargo.toml
crates/json/src/schema/build.rs
crates/json/src/schema/formats.rs
crates/json/src/schema/mod.rs
crates/json/src/validator.rs
crates/json/tests/validator_test_utils.rs
examples/net-trace/schema.yaml

Use an explicit Format enum deserialized by serde, so that unsupported formats are a build-time rather than a run-time error.
Add support for macaddr and macaddr8 formats, which are not part of the standard but are sensible and for which we have an internal use case (related to stats materializations).
Add basic test cases for almost all formats, which supplements the official schema test cases.
Tested:
* New tests cases covering macaddr and others.
* Manually verified that invalid formats now produce helpful build errors like:
```
examples/net-trace/schema.yaml error at <root> :
failed to build JSON schema
Caused by:
0: at keyword 'format' of schema 'file:///home/johnny/estuary/flow/examples/net-trace/schema.yaml#/$defs/ip-port/properties/ip': unknown variant …
```

crates/json: use explicit serde enum and add macaddr8 support

---

crates/connector_proxy/src/interceptors/network_tunnel_capture_interceptor.rs
crates/connector_proxy/src/interceptors/network_tunnel_materialize_interceptor.rs

- Resolves #648 by replacing the `.expect` with a proper `Result::Err`
- wrongly-configured network tunnel for a materialization
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/664)

network-tunnel: better error when consuming config fails

---

crates/json/src/number.rs
crates/json/src/schema/mod.rs
crates/json/src/validator.rs
crates/validation/tests/snapshots/scenario_tests__invalid_initial_register.snap
crates/validation/tests/snapshots/scenario_tests__test_step_ingest_schema_error.snap
go/bindings/.snapshots/TestDeriveWithIncResetPublish-derivedValidationErr
go/bindings/.snapshots/TestDeriveWithIncResetPublish-registerValidationErr
go/bindings/.snapshots/TestExtractorValidation
go/bindings/combine_test.go

- This is a first PR to improve the document JSON validation errors for human-readability
- ~My suggestion for the next step is to implement `Display` for [`FailedValidation`](https://github.com/estuary/flow/blob/master/crates/doc/src/lib.rs#L88-L91), so that we can render a pretty-printed JSON document, and point to the errors on it, something like:~ (See my comment below)
From:
```
"document": {
"bit": true,
"int": 52,
"str_whoops": "string B"
},
"basic_output": {
"errors": [
{
"absoluteKeywordLocation": "test://example/int-string.schema",
"error": "Invalid: Properties \"int\", \"str\", \"bit\" are required.",
"instanceLocation": "",
"keywordLocation": "#"
}
],
```
To:
```
{
"bit": true,
"int": 52,
"str_whoops": "string B"
<-- Property "str" is required but is missing
} …
```

json: human-readable error messages

---

go/flowctl-go/cmd-discover.go

- If you have a collection with slash in its name, discover fails because the directory doesn't exist, this PR resolves that issue.
- `flowctl-admin discover` on a connector with nested collections (e.g. firestore)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/636)

flowctl-go/discover: mkdir for nested collection paths

---

Cargo.lock
crates/connector_proxy/Cargo.toml
crates/flow_cli_common/Cargo.toml
crates/parser/Cargo.toml
crates/parser/src/main.rs

- I tried to use `flow_cli_common` in another project (airbyte-to-flow), but Cargo got confused about the two versions of clap we have in our `Cargo.lock` in this repository, turns out we had some packages still using clap:2 with structopt, which is now part of clap:3 as derive. I just migrated the code to use clap:3 and removed clap:2.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/680)

cargo: remove clap:2 and structopt, replace with clap:3

---

.github/workflows/flowctl-release.yaml
.github/workflows/main.yml
crates/flowctl/build.rs

Uses the `FLOW_VERSION` env variable to set the version string used by flowctl. This makes it consistent with the rest of the build, and allows non-release builds to use the version that's determined by the Makefile.
Also specifies the rust toolchain for flowctl release CI jobs.
_In theory_, this should get flowctl releases working, but I'll have to test that after this is merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/698)

Set flowctl version from FLOW_VERSION

---

.github/workflows/flowctl-release.yaml
.github/workflows/flowctl-test.yaml
.github/workflows/main.yml
Makefile

Previously, flow builds would install protoc using `apt`, while `flowctl` builds would use the `setup-prococ` action. This standardizes on the `setup-protoc` action because it supports multiple platforms.
Further, the `setup-protoc` action was previously failing due to rate limit errors from the GH API (it uses the API in order to fetch release versions). This commit adds the `repo-token` variable, which allows for a much higher rate limit, since the request is authenticated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/700)

Use setup-protoc action with authentication in CI

---

go/connector/run.go
go/flowctl-go/cmd-api-spec.go

- use a tcp socket for communicating with connectors
- I could not test UDS due to https://github.com/docker/for-mac/issues/483, but adding it should not be too hard if necessary
- We need a way to migrate our existing deployments to this new method without disruption in service, so I may have to change this code so that it supports both methods somehow, open to suggestions on that
- At the moment this pull-request means network-tunnel doesn't work anymore since I'm bypassing connector-proxy completely. Moving network-tunnel to an independent binary should also be worked before we can fully migrate. …

connector: use tcp socket for communicating with connectors

---

crates/agent-sql/src/publications.rs
crates/agent-sql/tests/expansions.rs

Closes https://github.com/estuary/flow/issues/655
Modifies the the flow expansion behavior when doing a build to not include unneeded captures or materializations. This prevents cases where (for example) an existing materialization failing to validate will prevent any new materializations being created from a shared collection. It may also provide a benefit to how long it takes to do a build in certain cases.
As far as I can tell this matches the intent of the original expansion, per the comments in existing the code.
In addition to the new unit tests, I ran a scenario locally where I:
- Made a single collection
- Create a Postgres materialization from that collection
- Allowed that materialization to successfully start & run, but then deleted the …

agent-sql: fix flow expansion to captures & materializations

---

supabase/functions/oauth/access-token.ts
supabase/functions/oauth/encrypt-config.ts

- Log the response from encryption service when encryption fails to allow for troubleshooting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/705)

supabase/oauth: when encryption fails, log the response from enc service

---

.devcontainer/github-ubuntu-2004.Dockerfile
.devcontainer/release.Dockerfile

One cannot use the devcontainer locally on M1 at this moment, nor build a release image. 
This PR:
* Installs git-lfs in the devcontainer that works for supported buster platforms instead of just amd64. 
* Upgrades rust in the devcontainer to 1.64.0
* Upgrades golang to the latest version in a way that supports many platforms.
* Installs docker-ce-cli from a repository so it supports more platforms
I've tested this locally on arm64/M1.
It should work, after not working before. 
None that I'm aware of. 
It might behoove a review who has a linux workstation to try and run `make docker-image` and also try running the devcontainer locally.
- - - …

devcontainer and release fixes

---

Makefile

- default target can include linux-binaries
`make`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/706)

make: default target can include linux-binaries

---

.devcontainer/release.Dockerfile

This is to support https://github.com/estuary/ops/issues/177. It adds gcloud utils to the release for agent support. 
N/A.
N/A
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/710)

adding gcloud utilities for agent deploy

---

go/protocols/materialize/go-schema-gen/.snapshots/TestGenerateSchema
go/protocols/materialize/go-schema-gen/generate.go
go/protocols/materialize/go-schema-gen/generate_test.go

This is a copy of the changes that were made in the mirrored code in the connectors repo, see https://github.com/estuary/connectors/pull/370
- - - …

go-schema-gen: use integers for ordering values

---

site/docs/reference/Connectors/capture-connectors/MySQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL.md
site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/amazon-ads.md
site/docs/reference/Connectors/capture-connectors/amplitude.md
site/docs/reference/Connectors/capture-connectors/apache-kafka.md
site/docs/reference/Connectors/capture-connectors/exchange-rates.md
site/docs/reference/Connectors/capture-connectors/facebook-marketing.md
site/docs/reference/Connectors/capture-connectors/gcs.md
site/docs/reference/Connectors/capture-connectors/github.md
site/docs/reference/Connectors/capture-connectors/google-ads.md
site/docs/reference/Connectors/capture-connectors/google-analytics.md
site/docs/reference/Connectors/capture-connectors/google-firestore.md
site/docs/reference/Connectors/capture-connectors/google-search-console.md
site/docs/reference/Connectors/capture-connectors/google-sheets.md
site/docs/reference/Connectors/capture-connectors/http-file.md
site/docs/reference/Connectors/capture-connectors/hubspot.md
site/docs/reference/Connectors/capture-connectors/intercom.md
site/docs/reference/Connectors/capture-connectors/linkedin-ads.md
site/docs/reference/Connectors/capture-connectors/mailchimp.md
site/docs/reference/Connectors/capture-connectors/notion.md
site/docs/reference/Connectors/capture-connectors/survey-monkey.md
site/docs/reference/Connectors/capture-connectors/tiktok.md
site/docs/reference/Connectors/materialization-connectors/README.md

Add docs for:
* source-notion
* source-survey-monkey
* source-tiktok-marketing
* source-google-search-console
* source-amazon-ads
Also, re-orders connectors to emphasize ours over airbyte's, and better explain how we integrate with 3rd parties. 
https://go.estuary.dev/fdKumB - GSC
https://go.estuary.dev/Y8iqCr - SurveyMonkey
https://go.estuary.dev/byfCts - TikTok
https://go.estuary.dev/VyWQ7h - TikTok
https://go.estuary.dev/EkkKXD - GSC
https://go.estuary.dev/9iXgpB - Notion
https://go.estuary.dev/rzNWCe - Amazon ads
...all need to be updated to point to our docs after merge.
Self-reviewed. We can tweak these more later if needed.
- - - …

docs: notion, surveymonkey, tiktok, gsc, amazon ads

---

go/connector/run.go

- There are still intermittently errors about connecting to the socket, not sure why it would be slow but increasing this for now to allow the rollout of airbyte-to-flow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/716)

connector/run: increase timeout for connecting to TCP socket

---

site/docs/getting-started/tutorials/README.md
site/docs/getting-started/tutorials/_category_.json
site/docs/getting-started/tutorials/dataflow-s3-snowflake.md
site/docs/guides/README.md
site/docs/guides/create-dataflow.md
site/docs/guides/create-derivation.md
site/docs/guides/system-specific-dataflows/README.md
site/docs/guides/system-specific-dataflows/_category_.json
site/docs/guides/system-specific-dataflows/s3-to-snowflake.md
site/docs/reference/Connectors/capture-connectors/amazon-s3.md
site/docs/reference/Connectors/materialization-connectors/Snowflake.md

* Introduces distinction between user guide (BYO data; assumes there is an active use case) and tutorials (provides data and exact step-by-step; designed for learning)
* Adds a "system specific guide" section to user guides, which we can populate with popular source-to-destination combinations
* Adds the first system-specific guide for an S3 to Snowflake dataflow
* Adds a thorough tutorial on S3 to snowflake using Citibike data
* Some associated changes to S3 and Snowflake connector docs that I found along the way
* Updates general guide to create a dataflow to new UI
Merging with self-review and will incorporate feedback on the published materials at a later date.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

docs: s3 to snowflake guide and tutorial

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yaml

This pins Postgres to 14 in the devcontainer setup as well as fixes a location for vscode extension for Rust support. `postgres:latest` is currently PG15 which doesn't work with this setup. 
N/A
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/731)

small fixes for devcontainers

---

supabase/functions/oauth/access-token.ts
supabase/functions/oauth/auth-url.ts

We want to use jspm because when it bundles non-es module libraries it uses Node polyfills instead of esm's use of Deno STD polyfills.
Also - there are some formatting changes because I saved the file and my LSP kicked in.
Start up edge functions with any recent version of Supabase
None
This feels so weird as a fix for the problem and I also still do not know exactly what happened in 1.4.7 that messed stuff up. I looked at the change (https://github.com/supabase/cli/compare/v1.4.6...v1.4.7) and could not see anything that would cause an issue. The version of Deno was already locked so it should not be that.
On version 1.4.6 and before we were good.
On version 1.4.7 we get an error like this: …

Enable edge functions to work on newer local Supabase Versions

---

.github/workflows/control-ci-cd.yaml

- deploy supabase functions on `master` branch instead of `main`, this broke during migration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/734)

ci: deploy supabase functions on 'master' branch

---

supabase/migrations/09_publications.sql

- I checked stats for our queries on `live_specs_ext` and found that all offending queries have a filter on `spec_type` which does not have an index, and they order by `updated_at DESC NULL LAST` which also does not have an index. With these changes, I can see an improvement from 3.6-4s down to 1.9-2.2s.
- To get statistics, I used:
```
SELECT query, mean_exec_time, total_exec_time, min_exec_time, max_exec_time FROM pg_stat_statements WHERE query LIKE '%live_specs_ext%';
```
- This is still relatively slow for 10 documents, and that's becaues apparently our authentication policy on `live_specs` table runs before any other quals (i.e. before filtering by `spec_type`). I did some research trying to find a way to optimise this, and basically ask postgres: can you please …

supabase/db: live_specs needs index on spec_type

---

crates/derive/src/pipeline/mod.rs
go/connector/run.go
go/flowctl-go/cmd-api-spec.go

Roll-back the implementation of connector/run.go to stdio-only mode. This is being done out of excess caution only, and not because of a specific known problem in this implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/740)

connector: revert to stdio behavior

---

site/docs/concepts/advanced/logs-stats.md
site/docs/concepts/collections.md
site/docs/concepts/flowctl.md
site/docs/getting-started/installation.md
site/docs/reference/authentication.md
site/docs/reference/working-logs-stats.md

Docs updates per #707, including
- Updates to flowctl docs to reflect new commands
- Updates to collections docs (on flowctl access)
- Updates to the concept and reference pages on logs and statistics, including full docs of stats, which were omitted prior
- A few random tweaks to installation and auth docs
don't think there are any shortlinks. 
I decided to handle stats properties (sort of) like connector config properties. I'm very curious to hear feedback on this. It's the sort of thing that I don't expect people to use all the time, but needs to be somewhere. Note the table _is_ simplified, but I didn't think exhaustively detailing the whole stats schema would be necessary or even helpful here.
- - -
This …

docs: flowctl updates, logs and stats

---

crates/agent-sql/src/publications.rs
crates/agent-sql/tests/publications.rs

We update spec edges *before* validating the specifications for referential correctness, so we must relax our precondition to allow for referenced specs that don't actually exist.
We'll later surface these missing specs as build errors when checking for referential integrity.
None. Agent will no longer crash if referenced collections don't actually exist.
- - - …

agent-sql: allow null specs when inserting data-flow edges

---

crates/connector_proxy/src/errors.rs

This commit tweaks `interceptor_stream_to_io_stream` to no longer stringify the underlying error type, so we get more information about the cause of the error.
In addition it changes `IOError` to be "transparent", meaning that when unwrapping the error details it won't be mentioned, which makes failure messages a lot more concise with (AFAIK) no loss of useful information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/749)

connector_proxy: Error wrapping tweaks

---

crates/connector_proxy/src/connector_runner.rs
crates/connector_proxy/src/main.rs

Our use of tokio::io to read from stdin will actually map those reads into regular, synchronous reads on a blocking thread pool of the tokio::Runtime.
Sometimes those reads will run forever, since stdin is never closed by the parent process without our first exiting or closing our stdout.
However, the Drop behavior of a Runtime is to block forever awaiting all tasks to stop running, which means we can deadlock. Use shutdown_background instead to explicitly and immediately leak blocking tasks which cannot be cancelled.
Tested locally with a reproduction case using a capture connector that deliberately fails.
Before this patch I confirmed that the connector-proxy was attempting to exit but not actually doing so, because it was sitting in Runtime::Drop awaiting a blocking …

connector_proxy: use explicit shutdown_background of tokio::Runtime

---

crates/flowctl/src/catalog/mod.rs

PR #707 regressed the ability to delete catalog entities using `flowctl catalog draft --delete ...`. This fixes that by allowing the `spec_type` of a `SpecCummaryItem` to be `null`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/754)

Fix deletion of catalog entities in flowctl

---

crates/connector_proxy/src/connector_runner.rs

- Do not wait for `streaming_all` to finish if the connector has already exit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/763)

connector-proxy: exit after underlying connector exits

---

site/docs/reference/Connectors/capture-connectors/google-firestore.md

Per https://github.com/estuary/connectors/pull/395 and https://github.com/estuary/connectors/pull/409, this updates and enhances the Firestore connector docs. 
* Document new backfill mode option in the binding config
* Add information section on FIrestore's data model and how we handle it (basically paraphrasing @willdonnelly's README).
go.estuary.dev/source-firestore - doesn't need to be modified but it'll be more useful now that we have better info.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/775)

Docs: Firestore backfill mode and data model

---

go/connector/run.go

Increases the maximum size of a message in the capture and materialization protocols, to allow Flow to process individual documents that are up to approximately 16MB. This seems like a reasonable maximum document size, and allows Flow to be useful for processing blockchain data, which tends to occasionally have documents in the 8-12MB range.
No change to the workflow, but things will now work properly if a user captures documents up to about 16MB.
We don't currently document our maximumm document size, but I think we should.
I tested this locally by capturing a ~9MB JSON document from GCS, and also running it through a derivation.
- - - …

Increase maxMessageSize to 16MB

---

go/protocols/airbyte/args.go

Previously the `log.level` flag was implemented as a property of each subcommand, but that meant that it had to come after the subcommand: `./connector --log.level=debug spec` would fail, for instance.
This commit moves the logging config into the global 'Application Options' option group so that it can be parsed at any position in the command line, and then changes the plumbing for how that gets applied during command execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/780)

protocols/airbyte: Support `log.level` anywhere in command line

---

go/protocols/capture/adapter.go
go/protocols/materialize/adapter.go

Fix an observed production behavior of connectors often not exiting after the runtime shard fails with (for example and most commonly) a schema violation.
While it's technically true that the server controls context cancellation, in practice this causes deadlocks with docker. I suspect this is because it's muxing process stdout and process control over a single unix domain socket without proper per-stream flow control, but not 100% confirmed :shrug: Instead, drop a current Send on the floor and propagate an error.
Testing:
I reproduced the essential behaviors we're seeing in production, including a schema violation, a connector that is stuffing its stdout, and the continued running of a connector and hangs of `docker inspect`/ `docker stop` after a shard is unassigned. …

go/protocols: adapter streamServer Send() must account for context cancellation

---

supabase/migrations/10_spec_ext.sql
supabase/tests/live_specs_ext.test.sql

- if a user has multiple rows giving them access to the same resource, we would show duplicate rows in `live_specs_ext`, with this PR, we avoid that by filtering with a common table expression that uses `distinct role_prefix`.
- I checked the performance of this query, and it seems to be as good as the previous one
- - - …

supabase/live_specs_ext: avoid duplicate specs due to multiple roles

---

site/docs/reference/Connectors/capture-connectors/amazon-s3.md
site/docs/reference/Connectors/capture-connectors/policies/iam-user-full-bucket.json
site/docs/reference/Connectors/capture-connectors/policies/iam-user-prefix-only.json
site/docs/reference/Connectors/capture-connectors/policies/public-full-bucket.json
site/docs/reference/Connectors/capture-connectors/policies/public-prefix-only.json

Significantly enhances source-s3 docs to have proper setup steps and samples of AWS policy documents. 
Separate steps and samples are included for 
* allowing a specific IAM user to access a bucket (adapted from a customer's recent experience)
* making a bucket public with a policy that allows anonymous reads (tested by me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/785)

docs: s3 bucket policy

---

crates/agent/src/publications.rs
crates/build/src/lib.rs

In addition to being smart about detecting when to run NPM, I also realized that we were naively always running tests, even if there weren't any tests to run. Skipping this early shaved off ~50% from my build time locally
Fixes #761
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/789)

refactor: skip running expensive tasks (npm, tests) if they're not neccesary

---

crates/agent/src/main.rs
supabase/seed.sql

Changes the default value for `accounts-email` used by the agent to be `support@estuary.dev`. This is consistent with the name of the account on prod. In practice this will only effect local development, making the two emails consistent.
Start a local flow development instance and observe the new value used for `accounts-email`. 
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/794)

agent: default accounts-email is support@estuary.dev

---

local/start-component.sh
supabase/migrations/14_gateway_auth.sql

Generates a self-signed TLS certificate when starting a local Flow instance using `start-flow.sh`. The DPG requires TLS, even when the browser is only connecting to the plain HTTP port, because of the janky way that DPG proxies REST requests to its own gRPC service over the loopback interface.
For devs only:
- You need to have the `openssl` binary on your PATH.
- when you run `start-flow.sh`, it will now generate the self-signed certificate automatically.
- If you re-run the supabase migrations, then the correct gateway address will be populated in the database.
- If you _don't_ re-run the migrations, then you can just update the gateway address to `http://localhost:28317`
This goes along …

Use self-signed TLS cert for DPG in start-flow.sh

---

site/docs/concepts/captures.md
site/docs/concepts/collections.md
site/docs/concepts/materialization.md

Documentation about documents :) 
Per https://github.com/estuary/flow/pull/779, notes maximum size of documents in collections, captures, and materializations concept docs. 
I realized that previously, we never explicitly stated plainly for our less-technical users that "collections are made up of documents and documents are..." I amended this by adding a small section to the top of the Collections page. 
If there's any other pertinent information we should add about this topic please let me know!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/797)

docs: documents and size

---

crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/lib.rs
crates/flowctl/src/ops.rs

fixes #726 
The new ouput of `flowctl logs --help`:
```
flowctl-logs
Prints the runtime logs of a task (capture, derivation, or materialization).
Reads contents from the `ops/<tenant>/logs` collection, selecting the partition that corresponds to
the selected task. This command is essentially equivalent to the much longer: `flowctl collections
read --collection ops/<tenant>/logs --include-partition estuary.dev/field/name=<task> --uncommitted`
USAGE:
flowctl logs [OPTIONS] --task <TASK>
OPTIONS:
--task <TASK>
The name of the task
--follow
Whether to block waiting for new data. If provided, the read will continue indefinitely
until interrupted or ending due to an error
-o, --output <OUTPUT>
How to format CLI output
[possible values: json, yaml, table]
--since <SINCE>
Start …
```

fix flowctl logs|stats help messages

---

Cargo.lock
crates/flowctl/Cargo.toml
crates/flowctl/src/auth/mod.rs
crates/flowctl/src/auth/roles.rs
crates/flowctl/src/catalog/mod.rs
crates/flowctl/src/collection/mod.rs
crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/config.rs
crates/flowctl/src/dataplane.rs
crates/flowctl/src/draft/author.rs
crates/flowctl/src/draft/develop.rs
crates/flowctl/src/draft/mod.rs
crates/flowctl/src/lib.rs
crates/flowctl/src/raw.rs

- Replace `Token` authentication with `ServiceAccount` which accepts a JSON file with three fields `access_token`, `refresh_token` and `expires_at` where `expires_at` is calculated [similar to how GoTrue does it](https://github.com/supabase/gotrue-js/blob/a441eef4d7291ec20b756cde99ccee87329594d0/src/lib/helpers.ts#L3-L6).
- Automatically refresh the `access_token` before running commands if expiry is close (in 10 minutes) or has already expired
- Solves the first item of https://github.com/estuary/animated-carnival/issues/43
- This requires a subsequent UI pull-request which changes the token presented to user to be a JSON object with the fields described. All these fields should already be available to the UI as part of `session` -- I made this [ui …

flowctl: service-account instead of token and auto-refresh

---

tests/run-end-to-end.sh
tests/source-test-no-state/flow.yaml

- Don't use `--poll`, instead use a modified version of `source-test` that can be told to exit: https://github.com/estuary/connectors/pull/429
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/817)

tests: run e2e tests without `--poll` (tail)

---

supabase/seed.sql

Updates the seed connectors list to use `dev` tags for the images - most of these connectors were failing to load when starting a new local dev environment for various reasons.
Also changes the `source-test` one (back?) to `source-hello-world`, so that `source-hello-world` is available by default for local dev.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/834)

local: update seed connectors

---

crates/assemble/src/lib.rs
crates/derive/src/combine_api.rs
crates/derive/src/pipeline/mod.rs
crates/derive/src/snapshots/derive__combine_api__test__combine_with_defaults_array.snap
crates/derive/src/snapshots/derive__combine_api__test__combine_with_defaults_different_types.snap
crates/derive/src/snapshots/derive__combine_api__test__combine_with_defaults_nested.snap
crates/derive/src/snapshots/derive__combine_api__test__combine_with_defaults_simple.snap
crates/doc/src/inference.rs
crates/doc/src/snapshots/doc__inference__test__default_value_validation.snap
crates/doc/src/validation.rs
crates/schemalate/src/markdown.rs

Teaches the drainer to look for default values from `default` annotations in the schema of draining documents if an actual value is not present when extracting fields. This only takes place for a materialization, and is a means to provide an alternative to materializing `null` values.
Closes https://github.com/estuary/flow/issues/764
Schemas can be annotated with default values, and materializations will use those default values instead of `null`. The values provided in the schema will be validated during builds to ensure they are compatible with the fields they are specified for.
It would be good to update our schema annotations docs with this: https://docs.estuary.dev/concepts/schemas/#annotations
We should say that …

combine: drainer considers default values during field extraction

---

ops-catalog/catalog-stats.ts
ops-catalog/ops-catalog-stats-schema.json
ops-catalog/ops-stats-schema.json
ops-catalog/stats-local-endpoint.sops.yaml
ops-catalog/template-common.flow.yaml
ops-catalog/template-local.flow.yaml
ops-catalog/template-prod.flow.yaml
supabase/seed.sql

Following up on https://github.com/estuary/flow/issues/764, this updates the catalog stats derivation to not output explicit zeros. This will save space, since many of these fields are 0 most of the time. Using default values of `0` on `docsAndBytes` we can now materialize into the stats table without having `null` values.
Also in this PR I am updating the stats materialization to use the "normal" postgres connector, since it is now compatible with pgBouncer, see https://github.com/estuary/connectors/pull/439.
Some notes on how this can be rolled out:
- It needs https://github.com/estuary/flow/issues/764 to actually be deployed and running live, otherwise materializations from this pipeline will fail on attempting to insert `null` values into the stats table.
- Existing …

ops-catalog: stats derivation does not output explicit zero values

---

supabase/functions/_shared/helpers.ts

- Mustache does not support inline helpers like Handlebars, that is: `{{ urlencode x }}` is not supported by Mustache.
- All helpers are block helpers in Mustache, so we need to support `{{#urlencode}}{{{x}}}{{/urlencode}}`. This is also supported by Handlebars.
- This pull-request updates our helpers so that they support inline helpers (current templates), block helpers in Handlebars, and block helpers in Mustache, so we can start switching all helper usages to block helpers as we go while not breaking things.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or …

oauth/helpers: support mustache and handlebars block helpers

---

Cargo.lock
Cargo.toml
crates/agent/Cargo.toml
crates/connector-init/src/lib.rs
crates/connector-init/src/main.rs
crates/connector-init/src/rpc.rs
crates/ops/src/decode.rs
go/protocols/capture/adapter.go
go/protocols/capture/coordinator.go
go/protocols/materialize/adapter.go
go/runtime/capture.go
go/runtime/derive.go
go/runtime/materialize.go
ops-catalog/ops-log-schema.json
tests/citi-bike-success/logs
tests/source-test-exit-status/data-plane.out.expect
tests/source-test-exit-status/logs
tests/source-test-no-state/logs

* Log failed / success exit status for the connector, in addition to returning an error. Format the exit `status` directly as it has nice handling for distinguishing signals vs exit codes.
* Log stdout processing failure and (debug) success for the connector.
^ There's an unavoidable race between stdout processing and the connector's exit status. Tonic can only return the first error. By logging both, we ensure that the ops collection at least has the full story.
* Use `error` instead of `err` consistently.
* Add `trace` as a supported ops log level, and further add various aliases for other common error levels we should flexibly parse. …

connector-init: various tweaks to improve ops logs and errors

---

crates/agent-sql/src/directives/beta_onboard.rs
crates/agent/src/directives/beta_onboard.rs

When creating a new tenant, setup their default storage mapping such that collection data (but not recovery log data) gets written under the `collection-data/` prefix. This allows us to put an object lifecycle policy on that prefix to automatically delete old data.
New tenants that are created via the betaOnboarding directive will now store collection data under the `collection-data/` prefix. Existing storage mappings are unaffected by _this_ change, but will be updated via a separate migration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/847)

Add prefix to new tenant storage mappings

---

.github/workflows/flowctl-release.yaml

Adds codesigning to our release process for `flowctl`. Now, all future `flowctl` Mac releases will be signed, which at least in theory makes it possible for Mac users to run it after downloading it using a browser. This does not include notarization.
I adapted the steps from both [these GH docs](https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development) and [this blog post](https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions). I've tested these steps locally and confirmed that I'm able to sign the binary without any interactive prompts. But based on my experience so far, I'm only about 50% confident that this is actually going to work in CI. I'd like to …

Sign mac binaries in CI release job

---

site/docs/concepts/derivations.md
site/docs/concepts/schemas.md

Updates conceptual Schema docs for two recent PRs:
* https://github.com/estuary/flow/pull/826 
* https://github.com/estuary/flow/pull/825
* My schema-writing skills aren't the strongest - I created samples in both new sections but please let me know if they don't make sense / if you have a better, more robust example I can sub in. 
* Writing about `default` annotations caused me to pause on an older line in the docs: _"Flow extends JSON Schema with additional annotation keywords, which provide Flow with further instruction for how documents should be processed."_ This feels like it should be followed by a comprehensive list - I know about `reduce` and now `default` but are there other Flow-specific keywords we should call out? Wasn't able to find …

Docs: schema updates

---

crates/parser/src/config/mod.rs
crates/parser/src/config/snapshots/parser__config__test__config_schema_is_generated.snap

Adjusts the generated parser schema so that it renders correctly in the UI.
Recently the UI became more strict about showing errors for schema that it considers invalid. So we now have some connectors that are showing errors in the configuration pages, see https://github.com/estuary/connectors/issues/467. This updates the `parser` schema so that it can be shown correctly. It seems that the UI needs a `"type": "object"` for the `format` property, and also doesn't want the `type` to be removed from the `type` objects it contains.
Open the parser config in the UI and observe that there are no more error messages shown.
N/A
- - -
This change …

parser: improve parser schema for UI display

---

control_plane_readme.md
supabase/oauth_seed.sql

- Add a new encrypted seed file that contains dev-specific oauth2 configurations for our connectors. These OAuth2 apps are separate and independent of our production OAuth2 app, and they are not going to be used for production use.
- So far I've only added github, but I'm setting the stone with this PR and want to make sure we like the method I'm using here, if not we can change how we do this, and then I'm adding all the other connectors.
- `control_plane_readme.md` describes how to get this seed into the database
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, …

oauth: add seed for local oauth2 connectors

---

crates/flowctl/src/catalog/mod.rs
crates/flowctl/src/catalog/publish.rs
crates/flowctl/src/catalog/pull_specs.rs
crates/flowctl/src/catalog/test.rs
crates/flowctl/src/draft/author.rs
crates/flowctl/src/draft/develop.rs
crates/flowctl/src/raw.rs
crates/flowctl/src/source.rs
crates/flowctl/src/source/bundle.rs
crates/flowctl/src/typescript/mod.rs
crates/sources/src/loader.rs

Fixes #862
Teaches the `typescript generate` subcommand to automatically fetch collections that are used as transform sources. This allows users to create derivations of source collections without needing to first pull their specs. Specs will be resolved by making a separate request for collection that's named as the `source` of a transform but not already included in the sources. I used a separate request per collection because it simplifies the process of generating good error messages, and because the number of collections to be fetched is expected to be relatively small. An example error message is:
```
Error: resolving the collection 'estuary/public/wikipedia/recentchangess', referenced from the transform 'fromWiki' in derivation 'phil/test/wikipedia/test-derivation' …
```

Automatically fetch collections for TS generation

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/mariadb.md
site/docs/reference/Connectors/materialization-connectors/README.md
site/docs/reference/Connectors/materialization-connectors/timescaledb.md

Adds docs for source-mariadb and materialize-timescaledb
Mariadb setup is different enough from source-mysql, so it seemed worth providing a complete page for it (rather than simply linking to source-mysql docs).
The Timescale docs are pretty similar to materialize-postgres, but for consistency they also get their own full, fleshed-out page.
I'm pretty confident in this one so I don't think it needs an in-depth review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/874)

docs: add mariadb and timescale

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/alpaca.md

Adds a documentation page for new Alpaca source connector
We'll need to create a [shortlink](https://app.short.io/) after publication and use it for the documentation URL for the connector (it's currently pointing to estuary.dev).
Please pay particular attention to the "Real time and historical data" and "Limitations" sections - there are a few details there I'm not 100% on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/872)

docs: source-alpaca

---

Makefile

- I realised we are building `flowctl` as a musl target, but it's actually used on the host machine, so I changed our makefile to build `flowctl` for the host target.
- flowctl is released through a CI pipeline that does not depend on the Makefile, so it shouldn't affect our flowctl release process: https://github.com/estuary/flow/blob/master/.github/workflows/flowctl-release.yaml
- This will allow mac users to use locally-built `flowctl` after running `make`
- `make`
- `flowctl` …

make: build flowctl for host arch, not musl

---

crates/agent/src/publications/specs.rs

solves #878: if a capture exists with name X, and a user attempts to create a materialization (or another non-capture entity), the error would be ambiguous and confusing. This commit tries to clarify the message.
- Try to create a capture with a name that conflicts with an existing materialization (or vice versa)
- - - …

publications: better error message when creating duplicate named publication

---

.github/workflows/flow-web.yaml

This will hopefully fix the publication of the flow-web NPM module. :crossed_fingers: There's not really a great way to test this locally, so I'd like to just see how it goes after being merged to master.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/885)

specify npm credentials for flow-web publish

---

.github/workflows/flow-web.yaml

I'd pushed #885 to specify the credentials for publishing, but the publish workflow only triggers if one of the files in `crates/flow-web/` is modified. This broadens that check so that the workflow will also run if the workflow yaml itself is modified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/886)

trigger flow-web CI when workflow file changes

---

Cargo.lock
Cargo.toml
crates/json/Cargo.toml
crates/json/src/schema/formats.rs

Part of https://github.com/estuary/connectors/issues/505
Adds support for string formats of "integer" and "number". These will allow connectors to handle integers and numbers encoded as strings.
See related PR for the SQL materialization connectors that require this change: https://github.com/estuary/connectors/pull/507
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/883)

crates/json: add integer and number string formats

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL.md
site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/alloydb.md
site/docs/reference/Connectors/materialization-connectors/Elasticsearch.md
site/docs/reference/Connectors/materialization-connectors/Parquet.md
site/docs/reference/Connectors/materialization-connectors/README.md
site/docs/reference/Connectors/materialization-connectors/alloydb.md

Adds docs pages for source-alloydb and materialize-alloydb. Modified from Postgres docs.
We'll need [shortlinks](https://app.short.io/) to these pages to add to the connector for use in the UI.
In here I instruct the user to use SSH tunneling to connect to this one because, from what I can tell, there's no way to connect to AlloyDB directly equivalent to whitelisting an IP. I tried creating a [firewall rule in the VPC](https://cloud.google.com/vpc/docs/using-firewalls) to no avail. It's possible that I'm wrong so please let me know if there's a way to do this.
- - - …

docs: Add AlloyDB connectors

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/salesforce-real-time.md

Adds simple reference docs for real-time salesforce connector -- in-depth guide on using the two salesforce connectors in parallel will come later.
A lot of this is copied/slightly modified from the other connector docs. The one thing I really wasn't sure about was the supported salesforce objects.... I couldn't figure out in the code if there was a specific list for this connector, so I used the list from the other one for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/922)

docs: salesforce-next

---

crates/flowctl/src/source/unbundle.rs
crates/models/src/catalogs.rs

Fixes #924
When running `flowctl catalog pull-specs --existing merge-spec`, it was possible to mangle the content of indirected resources such as typescript modules, connector configs, schemas, etc. This would happen if you had an existing directory with the spec for `acmeCo/specA` and then ran:
`flowctl catalog pull-specs --existing merge-spec --name acmeCo/specB` In that case, an existing indirected typescript module (or schema or whatever) from `specA` would end up having its first line of content overwritten by the relative path to that content.
The fix here is to just skip re-writing indirected content for specs that are already in the current directory, but not included in the set of specs being pulled.
- - - …

Fix flowctl catalog pull-specs with merge-spec

---

supabase/migrations/04_auth.sql
supabase/migrations/09_publications.sql
supabase/migrations/10_spec_ext.sql
supabase/migrations/11_stats.sql
supabase/migrations/12_storage.sql
supabase/migrations/15_directives.sql
supabase/migrations/16_tenants.sql
supabase/pending/faster_auth.sql
supabase/seed.sql
supabase/tests/auth.test.sql
supabase/tests/combined_grants_ext.test.sql
supabase/tests/directives.test.sql
supabase/tests/live_specs_ext.test.sql
supabase/tests/performance.test.sql
supabase/tests/stats.test.sql
supabase/tests/tenants.test.sql

This is a package of schema changes, test updates, and a new benchmark which quantify and then improve the performance of various authorization primitives and views within the control plane. Based on testing here, we can expect a substantial speedup of queries against the production control plane, even where a user has many imputed roles.
No breaking changes to semantics or public APIs:
* `auth_roles()` has a new, optional `min_capability` parameter.
* the role_grants select policy is restricted to require `admin` of the subject and object roles, rather than just `read` of the object role. This was overly permissive and the prior behavior could be considered a bug.
Apply DB migration and enjoy better dashboard performance.
**Documentation links …

control-plane: significantly accelerate authorization checks

---

crates/json/src/schema/formats.rs

- Add special case of `NaN`, `Infinity` and `-Infinity` to jsonschema validation for `format: number`
- See https://github.com/estuary/connectors/issues/543
- Pass `"NaN"` to a field with `type: string, format: number`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/945)

json: add "NaN", "Infinity" and "-Infinity" cases for number

---

supabase/migrations/17_refresh_tokens.sql
supabase/tests/refresh_tokens.test.sql
supabase/tests/stats.test.sql

- Fixes `refresh_tokens` tests by performing actions as authenticated user instead of `postgres` user
- Enable RLS on `refresh_tokens` table (already applied to production)
```
bash supabase/run_sql_tests.sh
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/954)

migrations: fix refresh_tokens and tests

---

Cargo.lock
Cargo.toml
crates/flowctl/Cargo.toml
crates/flowctl/src/auth/mod.rs
crates/flowctl/src/auth/roles.rs
crates/flowctl/src/catalog/delete.rs
crates/flowctl/src/catalog/mod.rs
crates/flowctl/src/catalog/publish.rs
crates/flowctl/src/catalog/pull_specs.rs
crates/flowctl/src/catalog/test.rs
crates/flowctl/src/collection/mod.rs
crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/config.rs
crates/flowctl/src/controlplane.rs
crates/flowctl/src/draft/author.rs
crates/flowctl/src/draft/develop.rs
crates/flowctl/src/draft/mod.rs
crates/flowctl/src/lib.rs
crates/flowctl/src/raw.rs
crates/flowctl/src/typescript/mod.rs

- Use the given `access_token` on at login time to generate a `refresh_token` and use that `refresh_token` to generate new `access_tokens` if they are expired.
```
flowctl auth token --token='YOUR TOKEN'
flowctl draft list
```
- You can also manually edit the JWT token using https://jwt.io/ debugger and set the expiry date to a time in the past to see the refresh logic in action
- - - …

flowctl: generate, persist and use refresh_token for continuous access

---

Cargo.lock
crates/schema-inference/Cargo.toml
crates/schema-inference/src/analyze.rs
crates/schema-inference/src/inference.rs
crates/schema-inference/src/schema.rs
crates/schema-inference/src/shape.rs
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_integer_merging-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_integer_merging.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_back_to_string-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_back_to_string.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-3.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-4.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings-3.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings.snap

- Try to parse strings as integer or fractional, and based on that suggest `format: integer` or `format: number`.
- Take `NaN`, `Infinity` and `-Infinity` into consideration when doing this
- Feed in documents with string fields containing numerical values
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/949)

schema-inference: infer format: integer/number for string values

---

crates/flowctl/src/config.rs
crates/flowctl/src/controlplane.rs
crates/flowctl/src/lib.rs

- In the case where the user has not done an initial login (mostly in non-interactive environments), we want to be able to just provide a refresh token through `FLOW_AUTH_TOKEN` and have `flowctl` use that to generate an `access_token`
- - - …

flowctl: automatically login if FLOW_AUTH_TOKEN is available

---

go/runtime/capture.go
go/runtime/capture_test.go
go/runtime/derive.go
go/runtime/materialize.go

This is a temporary hack to remove ack intents for journals like `ops/tenant/stats` and `ops/tenant/logs` since we have cleared those journals out. Any tasks with ackIntents in their recovery log for these are currently stuck forever retrying to write to the non-existant journal.
It should be reverted once those tasks are unstuck.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/975)

runtime: temporary code to drop ack intents for old ops journals

---

crates/flowctl/src/catalog/publish.rs

The spec md5 checking previously assumed that all specs would have an md5 value. This isn't the case if a local set of specs includes a spec that has been deleted from the remote control plane. In this case the md5 column is `null`.
This is probably not typical, but previous behavior would result in a pretty incomprehensible error message when it happens. This fix allows for the md5 value to be null and handles it appropriately.
N/A
- - - …

flowctl: handle possibility for deleted specs during catalog publish

---

crates/agent/src/publications/builds.rs

Runs `gsutil` with the -q option, which suppresses logs from normal operations completing successfully and instead only outputs errors if they occur.
Notably this will get rid of the `Copying file:///...` types of logs that are included at the end of the log stream when publishing tasks which should simplify interpretation of them, particularly in the case of errors with the publication.
Publish a task and observe the log output.
For example, prior to this change the expanded log output looks like this:
With this change in place the log output looks like this:
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

agent: quiet logging for gsutil

---

crates/schemalate/src/firebolt/firebolt_schema_builder.rs
crates/schemalate/src/firebolt/mod.rs

- Add a new action to schemalate/firebolt to build a drop table query, used by firebolt materialization to drop deleted bindings
- Used in https://github.com/estuary/connectors/pull/623
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/979)

schemalate/firebolt: add action to get drop query

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/http-file.md
site/docs/reference/Connectors/capture-connectors/http-ingest.md

This is a first pass at documentation for the source-http-ingest connector.
(https://go.estuary.dev/http-ingest) was updated to point to the newly added page.
Please feel free to push additional commits to this branch if that's easier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/987)

Add docs for source-http-ingest connector

---

Tiltfile
local/README.md

This adds a new way of running flow locally, as an alternative to `start-flow.sh`. This new method uses [Tilt](https://docs.tilt.dev/), which provides a way to orchestrate the startup of the various components. With the exception of supabase, the components are all run as direct binary invocations, not as docker images.
The motivation for this was to provide a way to have data-plane state persist across restarts when runnign locally. Unlike `start-flow.sh`, the Tiltfile does not use `temp-data-plane`, and instead runs etcd, gazette, and reactor as separate components.
This initial implementation probably still has some issues, especially for mac users. I left `start-flow.sh` in place for the time being, to ensure we can get the bugs worked out and give people time to …

Add Tilt for running Flow locally

---

ops-catalog/ops-log-schema.json
ops-catalog/tests.flow.yaml

We're now using canonical protobuf encoding, and that encoding will omit fields entirely rather then emit them with an empty literal.
Tested locally by updating & running catalog tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/995)

ops-catalog: make message optional in the logs schema

---

go/runtime/ops_publisher.go
go/runtime/task_term.go
go/shuffle/api_test.go
go/shuffle/reader_test.go
go/shuffle/ring.go
go/shuffle/ring_test.go

Swith to a single OpsPublisher having the shard lifetime, that updates with the labels of each task term. Use a Mutex to guard access.
Have a single shuffle.Coordinator that has the Shard's lifetime. This fixes the current cancellation race between the Coordinator (term context) and a replay read (shard context).
Tested on a local stack, where I published a materialization multiple times and confirmed it processed as expected.
Fixes #998
No changes.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/999)

runtime: switch to single coordinator having shard context lifetime

---

supabase/functions/oauth/access-token.ts
supabase/functions/oauth/auth-url.ts

- Implement `code_verifier` generation and `code_challenge` encoding as part of PKCE extension to OAuth2
- We will need the front-end to send back the `code_verifier` when it is sending request to get access token.
- - - …

oauth2: implement PKCE extension's code_verifier and code_challenge

---

Cargo.lock
Cargo.toml
crates/flowctl/Cargo.toml
crates/flowctl/src/auth/mod.rs

Removes the use of `rpassword` crate for reading auth tokens from stdin. Turns out that OSX has a feature called "secure input", which can prevent users from pasting into terminals. This post seems to describe more or less what's going on:
https://fig.io/docs/support/secure-keyboard-input#conflicts-with-password-managers-1password-bitwarden It's of course still possible that users may still have trouble pasting into iterm in some scenarios due to secure input. But removing `rpassword` seems likely to help in most cases.
run `flowctl auth login`. Previously, a secure input was used for the token, so it didn't show up in plain text. Now, it just shows up in plain text.
**Notes for reviewers:** n/a
- - -
This change …

flowctl: use basic stdin readline for auth tokens

---

supabase/functions/oauth/auth-url.ts

- oauth: code_verifier must be between 43 and 128 characters long
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1009)

oauth: code_verifier must be between 43 and 128 characters long

---

supabase/functions/_shared/helpers.ts
supabase/functions/oauth/access-token.ts

airbyte has recently introduced new fields to their OAuth response mappings, which need processing. In this case, we have AirTable which requires the `expires_in` field of response to be added to `now()` and rendered as an RFC3339 date to work. [See here](https://github.com/estuary/airbyte/blob/master/airbyte-integrations/connectors/source-airtable/oauth2.patch.json#L13) So I'm adding a condition here which allows response map to be rendered using a template instead of just jsonpointer.
In hindsight, we can probably just get rid of jsonpointers here and use mustache templates for the responseMap since it can do the same job anyway. For now I'm keeping both.
(list …

oauth: allow using templates in OAuth response template

---

supabase/functions/oauth/access-token.ts

- if a connector specified the content-type header using a different casing than `content-type`, the default content-type would not be overriden and cause issues.
- with this fix, we check for case-insensitive presence of that header and set the default only if the header is not present in the connector's oauth2 spec
- - - …

oauth: fix default content-type not being overriden sometimes

---

Cargo.lock
Cargo.toml
crates/async-process/Cargo.toml
crates/async-process/src/lib.rs
crates/build/src/api.rs
crates/flowctl/src/config.rs
crates/flowctl/src/local_specs.rs
crates/runtime/src/derive/middleware.rs
go/bindings/task_service_test.go

Ultimately, the problem was that `Child::wait()` had to take ownership of `Child::inner`, because [both `wait()` and `kill()` take `&mut self`](https://stackoverflow.com/q/35093869), meaning that if you've called `wait()`, you can't also call `kill()`. 
The solution here was to introduce [`shared_child`](https://docs.rs/shared_child/latest/shared_child/), which lifts that limitation, allowing the `impl Drop` handler to successfully `SIGKILL` the running process, and clean up properly.
**Note:** Because this is in a drop handler, we're `SIGKILL`ing the `temp-data-plane` instead of `SIGTERM`ing it. On linux, we set a flag to instruct the kernel to kill all of `temp-data-plane`'s child processes when it is killed, but we either can't or don't set that flag on MacOS. As a …

Fix `kill_on_drop`

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL.md

Doc updates for https://github.com/estuary/connectors/pull/690. See that PR description for the technical background.
For manual setups these updated docs will instruct the user to create a targeted publication including only the tables they want to capture from rather than a "FOR ALL TABLES" publication which may have unwanted side effects.
- - -
This …

docs: don't recommend 'for all tables' publication for source-postgres

---

crates/derive-sqlite/src/connector.rs
crates/derive-typescript/src/lib.rs
go/runtime/derive.go

Use a default of :memory: only if no DeriveRequestExt is sent (as is the
case with preview).
Then, update the Go runtime to always pass `SqliteVfsUri` with each Open
and re-Open. This resolves a bug where a derivation would re-Open with
a :memory: database, which was not intended.
Tested manually using a local stack. Confirmed that shard unassignment
continues to work correctly (it always had), and that updated
publications now work (where they had not previously).
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing …

derive-sqlite: require that URI is passed with DeriveRequestExt (fixes checkpoint bug)

---

go/flowctl-go/cmd-api-discover.go

This is intended to be temporary and will allow certain captures (salesforce) to succeed with discovery that are currently taking a little longer than 20 seconds to complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1038)

agent: bump up the discovery timeout limit

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/sftp.md

Docs for the new `source-sftp` connector, added in https://github.com/estuary/connectors/pull/713
I don't know what `sidebar_position: 1` does but I saw it that way in some other connectors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1037)

docs: source-sftp connector docs

---

go/runtime/capture.go
go/runtime/derive.go
go/runtime/flow_consumer.go
go/runtime/materialize.go
go/runtime/task_term.go

Adds information about the reactor instance to the ops logs. We had an incident recently where a single reactor instance was faulting due to a problem with the k8s node. While it was easy to see which tasks were assigned to that instance at the time, it was quite difficult to determine that after the fact. So the goal of this commit is to make it easier to troubleshoot this type of thing in the future.
The details of the reactor instance are not added to _all_ logs in order to prevent unnecessary bloat. Instead they are only logged on term initialization and shard failure.
This is a new iteration on #1033, which will be closed.
Example of a logged field from a local instance:
```
{
"ItemID": "materialize/aliceCo/mat1/00000000-00000000",
"MemberZone": "local", …
```

reactor: add reactor instance details to ops logs

---

Cargo.lock
Cargo.toml
crates/flowctl/Cargo.toml
crates/flowctl/src/auth/mod.rs

Fixes #1031 
On some terminals, `flowctl auth login` would fail to read JWTs longer than 1024 characters. This bug was introduced when we removed `rpassword` in favor of `stdin.readline(_)`, which meant that we left the terminal in "cooked" instead of "raw" mode. This commit introduces the `rustyline` library (a pure-rust version of readline) to read the token input. This handles pastes of arbitrarily long strings.
This fix is a little different from what we were previously thinking. We'd previously talked about having the `auth login` command instead print a message telling people to follow up by running `flowctl auth token`. But having found the root cause and a simple solution, it seemed worthwhile to keep the current UX unchanged.
**Workflow steps:** no change …

flowctl: use rustyline for reading login token

---

crates/flowctl/src/lib.rs
crates/flowctl/src/ops.rs
site/docs/guides/flowctl/troubleshoot-task.md

This commit updates the flowctl logs and stats subcommands to be compatible with the new collection names. It allows anyone with a grant to `ops.us-central1.v1/logs|stats` to once again use flowctl to view logs and stats.
This does not yet allow end-users to view their logs or stats. That won't be possible until partition-level authorization gets implemented. So, I've also updated the help messages of the logs and stats subcommands to reflect that and hopefully make things slightly less confusing for users. I also updated the docs page with a similar message.
https://docs.estuary.dev/guides/flowctl/troubleshoot-task/
- - - …

flowctl: fix logs and stats subcommands, sort of

---

site/docs/reference/Connectors/capture-connectors/MySQL.md
site/docs/reference/Connectors/capture-connectors/mariadb.md

Updates the MySQL and MariaDB capture docs for https://github.com/estuary/connectors/pull/715 re: timezone configuration.
Also an update to these docs per https://github.com/estuary/connectors/pull/667 for supported table alterations.
- - - …

docs: timezone configuration for mysql and mariadb captures

---

supabase/functions/_shared/helpers.ts
supabase/functions/oauth/access-token.ts
supabase/functions/oauth/auth-url.ts

- this is a leftover parameter, we don't need it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1051)

functions: compileTemplate doesn't need connector_id

---

crates/agent/src/publications.rs
crates/agent/src/publications/builds.rs
crates/agent/src/publications/specs.rs

When publishing collection specs, the agent will now return `incompatible_collections` when either the `key` or partition fields of a collection have changed. This addresses the scenario where a user re-runs discovery on their endpoint and the connector outputs collections with new keys. In this case, the UI will now suggest re-creating the affected collections with new names.
- Create a SQL capture of table `foo`
- In the source database, change the primary key of `foo` to a different column
- edit a capture
- click "refresh" in the bindings component to discover the collection with a different key
- click save and publish
- With this PR, you'll now see an error like this one, with the suggestion to re-create the collections:
**Documentation links …

agent: better errors when key pointers change

---

crates/schema-inference/src/inference.rs
crates/schema-inference/src/snapshots/schema_inference__analyze__test__generator_with_multiple_values.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__multi_merging.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__nested_values.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__simple_schema_merging.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_integer_merging-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_integer_merging.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_back_to_string-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_back_to_string.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-3.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-4.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings-2.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings-3.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings.snap
crates/schema-inference/src/snapshots/schema_inference__analyze__test__very_nested.snap

- Do not mark any property as `required` since it is hard to revert it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1056)

schema-inference: do not mark any property as required

---

Cargo.lock
Cargo.toml
crates/connector-init/src/lib.rs
crates/proto-grpc/src/capture.rs
crates/proto-grpc/src/consumer.rs
crates/proto-grpc/src/derive.rs
crates/proto-grpc/src/flow.rs
crates/proto-grpc/src/materialize.rs
crates/proto-grpc/src/protocol.rs
go/connector/container.go

Update `tonic` to bring in new message bound behavior added in v0.9 Update capture/derive/materialize services to accept messages of unbounded size from the runtime, as the runtime will ultimiately enforce document size limitations.
- - - …

increase document limit from 16MB => 32MB

---

crates/agent/src/evolution.rs
crates/agent/src/evolution/snapshots/agent__evolution__test__collection_evolution-2.snap
crates/agent/src/evolution/snapshots/agent__evolution__test__collection_evolution.snap
crates/agent/src/evolution/test.rs
crates/agent/src/evolution/test_setup.sql

This addresses a portion of #1063, but it seemed useful on its own and separable from the rest of the work related to it.
There's a big difference between collections that use inferred schemas and those that don't, and the overall aim of this commit is to have the `evolutions` handler do the "right thing" in both cases. This means introducing some special behavior for collections that bear the `x-infer-schema` annotation in their schema.
If a collection is using an inferred schema, then re-creating it is unlikely to help, and can be quite costly and inefficient. So generally in that case we'd prefer to _only_ update the materialization bindings to materialize the existing collection to a new table. But there are still cases where re-creating the collection is necessary. …

agent: evolutions handling inferred schemas

---

go/connector/driver.go
go/protocols/capture/pull_client.go
go/protocols/capture/pull_client_test.go
go/protocols/flow/re_exports.go
go/protocols/materialize/client.go
go/protocols/materialize/client_transactor_test.go
go/protocols/materialize/lifecycle.go
go/protocols/materialize/sql/driver.go
go/runtime/derive.go

Centralize the means by which we unwrap gRPC status codes and map them into canonical Go errors into a single function.
Update to use this function consistently throughout Flow, including coverage of additional places that formerly had not been unwrapped:
- `materialize.TxnClient.writeErr`
- `capture.Open` when reading `Opened`.
- - - …

add flow.UnwrapGRPCError and use it consistently

---

site/docs/concepts/captures.md

"Push captures" or "pull captures" are not a thing anymore.
Instead we implemented the connector network feature (which achieved the same end goal) and now there are only "captures".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1072)

docs: remove reference to pull vs push captures

---

crates/parser/src/main.rs

The actual `message` is what gets picked up as the shard failure reason when a connector fails, and with https://github.com/estuary/connectors/pull/762 this will be logged from the parser when a connector fails due to a parsing error. This changes the logged `message` to include the error details.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1084)

parser: log error details in the message when exiting with an error

---

ops-catalog/stats-production-endpoint.sops.yaml

We won't be using pgBouncer with the updated `materialize-postgres` connector. This changes the database connection to connect to the database directly instead of the pgBouncer address. See https://github.com/estuary/connectors/pull/758
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1082)

ops-catalog: don't use pgBouncer endpoint

---

go/protocols/materialize/client.go

Fixes the materialization client so that the length of the flighted map for the binding that the document is being added to is checked for its current size vs. the maximum allowed.
This still does allow for cases where a materialization has more than 1 binding to exceed the overall txn size limit. At this point I'm not sure that is a big enough problem to worry about since we intend this to be a temporary measure.
Tested on a local stack with an artificially low limit to see that individual transactions are concluded when the limit is reached.
N/A
- - - …

materialize: txn size check fix

---

crates/agent-sql/src/drafts.rs
crates/agent-sql/src/publications.rs
crates/agent-sql/tests/snapshots/publications__publication_data_operations-4.snap
crates/agent/src/publications.rs
crates/agent/src/publications/specs.rs
supabase/migrations/07_drafts.sql
supabase/migrations/09_publications.sql
supabase/pending/built_specs.sql
supabase/pending/remove_ops_grants.sql

As part of a publication the agent will add the built spec to the `live_specs` table.
If the publication is a dry run, the agent will add the built spec and the validated response to the `draft_specs` table for further use in the publication authoring process.
I tested this manually by:
- Start up a local stack on the current main branch (without this change)
- Create a few tasks - they don't have built spec/validated data saved
- Apply the pending migrations in this PR to the local stack supabase
- Re-build the agent from this PR and re-start it
- Create new tasks - now they have built spec & validated data saved to the local stack supabase for their drafts and live specs
Create publications and the additional columns are populated in the control …

agent: add built spec and validate response to control plane db

---

go/protocols/materialize/lifecycle.go
go/protocols/materialize/transactor.go

Export the `Total` field on `StoreIterator` and `LoadIterator`.  From `StoreIterator` this is useful for materializations implementing a transaction delay where the delay may not be applied if a large number of documents were stored in this transaction, which would be indicative of an on-going backfill (see https://github.com/estuary/connectors/pull/774). `LoadIterator` doesn't have an immediate use but it seems like it might be handy to have exported too.
N/A
- - - …

materialize: export load and store iterator total field

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL.md
site/docs/reference/Connectors/materialization-connectors/PostgreSQL.md

Doc updates for https://github.com/estuary/connectors/pull/769 and https://github.com/estuary/connectors/pull/753, which added this parameter for both postgres connectors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1089)

docs: add sslmode advanced config documentation to postgres capture & materialization

---

crates/parser/src/format/mod.rs

Includes the file name in the error message when failing to infer a format.
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1095)

parser: include file name in error message when failing to infer format

---

site/docs/reference/Connectors/materialization-connectors/BigQuery.md
site/docs/reference/Connectors/materialization-connectors/Snowflake.md

Removes the instructions to set the `minTxnDuration` for BigQuery and Snowflake.
BigQuery will have the 2 minute delay built-in, and Snowflake will have a configuration for setting a delay as part of the connector config. See connectors PR https://github.com/estuary/connectors/pull/774
- - - …

docs: update materialization docs to use update delay instead of minTxnDuration

---

Cargo.lock
Cargo.toml
crates/doc/src/validation.rs
crates/flowctl/Cargo.toml
crates/flowctl/src/collection/mod.rs
crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/raw/mod.rs
crates/flowctl/src/raw/suggest_schema.rs
crates/schema-inference/src/server.rs

reads a collection and ops logs of the relevant task, and runs schema inference on documents of the collection and documents that have violated schema validation to come up with a schema that will allow those documents to pass through the task. runs `git diff` on the resulting schema and the original schema to give an idea of how a patch may be constructed.
```
flowctl raw suggest-schema
--collection estuary/marketing/google-ads/campaigns
--task estuary/marketing/google-ads/source-google-ads
```
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief …

flowctl: raw suggest-schema command

---

site/docs/reference/Connectors/materialization-connectors/pinecone.md

Doc updates for `materialize-pinecone` for https://github.com/estuary/connectors/pull/786
These are the doc updates
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1105)

docs: materialize-pinecone docs for new embedding input generation

---

crates/flowctl/src/draft/author.rs
crates/flowctl/src/lib.rs

There was a bug in the `clear_draft` function that caused the function to fail if the draft was not already empty.  This was caused by an incorrect type parameter in the `api_exec_paginated` callsite. The prior type parameter `Vec<Value>` was incorrect because the return type of `api_exec_paginated` is `Vec<T>`, thus the actual type that was expected by the response deserialization logic ended up being `Vec<Vec<Value>>`.  So the fix was to simply change the type parameter to just plain `Value`.
While tracking that down, I added some additional logging to `api_exec`, which seemed useful enough to keep around.
Also included here is a fix for another tiny bug I noticed, where we would panic immediately upon a deserialization error instead of returning the error and letting …

flowctl: fix draft author regression

---

site/docs/concepts/materialization.md

We recently discovered an incorrect example in the materialization docs, and this just fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1097)

docs: fix materialization partitions example

---

go/bindings/trampoline.go

This fixes a deadlock in `flowctl-go api build` that was observed in prod.  The proximal cause of the deadlock is the line in `trampoline.go` that is removed in this PR.  The context was cancelled, and so it never sent the result through the `resolvedCh`. Meanwhile, on [this line](https://github.com/estuary/flow/blob/33844329ca876352c9b0583112c886e17a091de5/go/bindings/build.go#L221) in `build.go`, it's waiting indefinitely on all the results of all trampoline tasks.
In case you're wondering how the context got cancelled, it happened due to our [overall build timeout](https://github.com/estuary/flow/blob/33844329ca876352c9b0583112c886e17a091de5/go/flowctl-go/cmd-api-build.go#L84), which cancelled the parent context.
So the fix is to just get rid of the line that skips …

bindings: ignore context cancellation when sending trampoline results

---

crates/json/src/schema/formats.rs

The current implementation only supports time values with `Z` as timezone identifier, but RFC3339 also supports offset hour and minute in the format of +hh:mm or -hh:mm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1114)

json: support timezone offsets when parsing `format: time` values

---

crates/agent/src/discovers.rs
crates/agent/src/discovers/snapshots/agent__discovers__specs__tests__capture_merge_update.snap
crates/agent/src/discovers/specs.rs
crates/agent/src/evolution.rs
crates/agent/src/publications/specs.rs
crates/flowctl/src/raw/discover.rs
crates/models/src/captures.rs
crates/models/src/derivation.rs
crates/models/src/materializations.rs
crates/sources/src/indirect.rs
crates/sources/src/inline.rs
crates/sources/src/loader.rs
crates/sources/tests/snapshots/schema_generation__catalog_schema_snapshot.snap
crates/validation/src/capture.rs
crates/validation/src/derivation.rs
crates/validation/src/materialization.rs
crates/validation/src/reference.rs
crates/validation/tests/scenario_tests.rs
flow.schema.json

This changes the representation of disabled capture and materialization bindings in Flow specs.  We previously used `target: null` and `resource: null` to represent disabled capture and materialization bindings respctively.  That change was introduced quite recently and has not seen any use yet.  This commit changes both capture and materialization bindings to use `disabled: true`.
Ultimately, the reason for this is to make it easier to programatically manipulate Flow specs.  Say a user runs a discover of an existing capture via the UI. Afterward, the draft could contain a bunch of disabled bindings with `target: null` along with a corresponding collection for each disabled binding. The UI needs those collections so that it can make sure they're included in the draft if …

models: disable bindings using a boolean

---

site/docs/guides/customize-materialization-fields.md

Adds a new guide to the docs. This answers the common user question: "how do I get my output table fields to look how I want?" 
Follow the guide; determine if has the information a user would need to get the desired result.
I was having trouble testing schema inference in the UI (wasn't seeing it as an option when editing a Firestore capture) -- I wrote this given what I understand as the intended behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1119)

docs: Customize materialized fields

---

site/docs/reference/Connectors/materialization-connectors/amazon-redshift.md

Doc updates for `materialize-redshift` PR https://github.com/estuary/connectors/pull/832.
The connector now automatically handles long strings, so the user doesn't need to do any additional configuration.
There is (still) a maximum total record size of 4MB, and a callout in the docs was added for that.
- - - …

docs: update redshift docs

---

crates/connector-init/src/lib.rs
crates/flowctl/src/connector.rs

- With this change, we start listening on the tcp port in `connector-init` as soon as possible, but we don't process the requests while we check the protocol. After we have checked the protocol, we use the incoming stream to serve requests.
- This allows clients to connect to the server earlier and write to it, in a sense buffering some request(s)
- This is motivated by our code in `flowctl`'s `docker_run` not being able to clearly distinguish between a port that it can connect to, and a port that is ready for data to be written to it [here](https://github.com/estuary/flow/blob/master/crates/flowctl/src/connector.rs#L82). It's still a mystery to me how the go implementation of the same connection works fine and waits until the grpc server actually starts processing before …

connector-init: start listening on tcp port before check_protocol

---

crates/flow-web/src/utils.rs
crates/flowctl/src/connector.rs
crates/flowctl/src/ops.rs
crates/flowctl/src/raw/suggest_schema.rs
crates/runtime/src/task_service.rs
go/bindings/task_service.go

These were missed when previously increasing message limits for captures and materializations. Use the same 64MB upper-bound on message size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1130)

runtime: increate derivation gRPC message limits

---

Cargo.lock
Cargo.toml
crates/doc/Cargo.toml
crates/doc/src/inference.rs
crates/json/src/schema/types.rs

Implement `Shape::widen` which enables widening a `Shape` to fit a provided `AsNode`. This sets the groundwork for permanently keeping track of a running inferred schema in the combiner.
Of note, the schemas "inferred" by `widen()` are maximally strict:
* By default, newly inferred objects have have `additionalProperties: false`.
* Object fields initially have `required: true` until we encounter a document missing that field, at which point it will be downgraded to `required: false`. **Note:** This isn't required AFAICT. Should we really do this?
The next piece of work is implementing the stubbed-out `enforce_field_count_limits`. With that, we should have everything we need to implement the running inferred schema and emit it to the ops logs. Also of note is that the `reduce: …

Schema inference: `Shape::widen()`

---

site/docs/reference/Connectors/capture-connectors/postgres-batch.md

This should be improved some time, but since we auto-open the page in a sidebar in our dashboard there needs to be *something* there immediately, and this is the bare minimum IMO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1133)

source-postgres-batch: Add very minimal documentation

---

.vscode/settings.json
rustfmt.toml

Rust analyzer was adding undesired newlines to automatically-generated import statements. Pretty sure this fixes it, at least on my machine 👀 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1136)

Fix `rust-analyzer` adding spaces to `use` statements

---

ops-catalog/schema-inference.flow.yaml
ops-catalog/schema-inference.schema.yaml
ops-catalog/schema-inference.test.flow.yaml
ops-catalog/template-common.flow.yaml
ops-catalog/template-local.flow.yaml
ops-catalog/template-prod.flow.yaml
ops-catalog/tests.flow.yaml

Per convo with @jgraettinger, I added `L1` under `ops.us-central1.v1/private` and `L2` under `estuary/global`
Closes #1140. It works!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1141)

Add schema inference `L1` and `L2` collections, as well as materializing them to the database

---

crates/flowctl/src/preview/mod.rs
ops-catalog/schema-inference.flow.yaml
supabase/migrations/22_inferred_schemas.sql
supabase/tests/inferred_schemas.test.sql

New `inferred_schemas` table is much like `catalog_stats`, and is loaded by the same stats_loader task.
Also add a partition selector to the inferred-schemas L1 derivation, to read only capture logs (for now: in the future we'll add derivations) and to exclude it's own schema inferrences.
Finally, improve `flowctl preview` error when a selector is not matched to explicitly tell the user that no journals were found, and what the evaluated selector was.
New table / API `inferred_schemas` is available. …

supabase: add `inferred_schemas` migration and final fixes

---

crates/flowctl/src/main.rs
crates/flowctl/src/preview/mod.rs

`flowctl preview` would hang indefinitely when an error was encountered running the derivation. This fixes that to return immediately. In order to do that, we needed to explicitly shutdown the runtime, because the reason it was hanging was due to the runtime blocking on a future (reading stdin) that would never complete.
Run `flowctl preview` on a spec that results in a validation error. Previously, it would hang indefinitely. Now it'll return the error immediately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1147)

flowctl: fix preview hanging on error

---

supabase/migrations/20_auto_discovers.sql
supabase/tests/auto_discovers.test.sql

The `next_auto_discovers` view was incorrectly returning the entire `endpoint` to use as the `endpoint_config` of the discover. This resulted in a _deeply_ nested config after many periodic discovers, since the connector it was tested with would accept the broken config. Serves me right for not having a test for that view. I added a test here.
Also fixes a bug where disabled captures would still get discovered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1148)

agent: fix next_auto_discovers view

---

supabase/migrations/20_auto_discovers.sql
supabase/tests/auto_discovers.test.sql

Fixes another bug in the next_auto_discovers view, where it would not respect the `auto_discover_interval` and would publish much more frequently if the publications were successful. This fixes it by considering the `updated_at` timestamp of the `live_specs` table when checking to see if a capture is due for another auto discover.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1149)

control-plane: exclude recently updated specs from next_auto_discovers

---

crates/agent/src/publications/specs.rs
crates/agent/src/resource_configs.rs
crates/derive/src/combine_api.rs
crates/doc/src/ptr.rs
crates/doc/src/reduce/schema.rs
crates/doc/src/shape/limits.rs
crates/doc/src/shape/location.rs
crates/doc/tests/shape_fuzz.rs
crates/flow-web/src/lib.rs
crates/flowctl/src/raw/discover.rs
crates/schemalate/src/markdown.rs
crates/validation/src/collection.rs
go/runtime/capture.go
go/runtime/flow_consumer.go
go/runtime/interfaces.go
go/runtime/task_term.go

* Replace per-subschema field limit with a global complexity limit, currently set at 1000 total fields.
* Add a `--flow.enable-schema-inference` flag to `flowctl-go serve consumer` to enable schema inference for capture tasks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1157)

Improve schema limits

---

examples/derive-patterns/README.md
examples/derive-patterns/entity-attribute-values.flow.yaml
examples/derive-patterns/flow.yaml

Adds an 'entity-attribute-values' example to derive-patterns, which shows how to normalize these values by rolling them up by entity id.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1164)

examples: add derive pattern k/v pairs example

---

site/docs/reference/Connectors/materialization-connectors/mysql.md

Explicitly clarify that we write `DATETIME` fields in UTC timezone
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1168)

materialize-mysql: datetime utc

---

crates/flowctl/src/collection/mod.rs
crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/ops.rs

Replaces the --include-partition and --exclude-partition arguments of `flowctl collections read|list-journals|list-fragments` with a new `--partitions` argument. The new argument accepts a JSON object, which is deserialized into a `models::PartitionSelector`, and thus matches the shape of the selector that's used in catalog specs.
The motivation for this is that the old arguments didn't allow for reading from partitions where the value was a json `null`. When it was written, we didn't allow partitioning on nullable fields. Now that we do, the json syntax seemed desirable as it allows distinguishing between json types, so that `null` can be differentiated from the string `"null"`.
If you'd previously used `--include-partition foo=bar`, then you'll now …

flowctl: change to new --partitions argument

---

crates/derive-typescript/src/main.rs
crates/runtime/src/image_connector.rs

Image connectors can deadlock at high volumes of requests and response due to channel stuffing. Specifically it's not okay to await a send into the container while not concurrently polling for container responses.
Re-work the state machine to forward non-error responses using a separate spawned task, which is joined over only upon terminal error or completion.
**Notes …

runtime: fix flakey connector deadlock

---

crates/agent/src/publications/linked_materializations.rs
crates/agent/src/publications/linked_materializations/snapshots/agent__publications__linked_materializations__test__capture_only_published.snap
crates/agent/src/publications/test_resources/linked_materializations.sql

This updates the handling of materialization `sourceCapture`s in the publications handler, to no longer disable materialization bindings. The agent will now only ever add bindings to linked materializations, and will never disable them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1187)

agent: don't disable linked materialization bindings

---

crates/flowctl/src/connector.rs
crates/flowctl/src/raw/capture.rs
crates/flowctl/src/raw/discover.rs

- Allow specifying `--network` in `flowctl raw` commands, helps with testing locally on endpoints run with docker
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1189)

flowctl: allow specifying --network in `raw` commands

---

supabase/migrations/30_log_lines_index.sql

Replaces the current BRIN index on the `internal.log_lines` table with a btree index.  The BRIN index would require queries to use the `logged_at` timestamp in the where clause in order for it to be effective.  Neither the UI or flowctl do that currently. The btree index works well when only filtering on token, so this changes to just using that.
The main issue this is seeking to address is that clients are getting HTTP 500 responses when they try to fetch log lines during a publication or discover. Another option that might also work to address this would be to add `where logged_at > (now() - '1h'::interval)` to the query in the `view_logs` RPC. I decided to use the btree index instead because it felt somewhat less hacky.
BUT, we may still want a …

control-plane: use btree index for log_lines

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL.md

Edits all examples of `CREATE PUBLICATION` queries to be followed by an `ALTER PUBLICATION p SET (publish_via_partition_root = true)` query.
This is done in a separate `ALTER PUBLICATION` query because it will fail on versions of PostgreSQL <13 which predate the setting, and if the user blindly executes the commands we want the create portion to succeed anyway.
Also adds some text explaining that the flag is recommended but not required, with a brief explanation of why it's recommended / what it does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1199)

docs/source-postgres: Set `publish_via_partition_root` in setup

---

crates/flowctl/src/local_specs.rs
crates/flowctl/src/raw/capture.rs

- `raw capture` was not passing `network` during the validation phase
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1209)

flowctl: pass network parameter to load_and_full_validate

---

Cargo.lock
Cargo.toml
Makefile
crates/derive/src/combine_api.rs
crates/doc/Cargo.toml
crates/doc/src/archived.rs
crates/doc/src/combine/memtable.rs
crates/doc/src/combine/mod.rs
crates/doc/src/combine/spill.rs
crates/doc/src/extractor.rs
crates/doc/src/heap.rs
crates/doc/src/lib.rs
crates/doc/src/owned.rs
crates/doc/src/shape/widen.rs
crates/doc/tests/combiner_perf.rs
crates/doc/tests/spill_merge_fuzz.rs
crates/flowctl/src/raw/mod.rs
crates/runtime/src/derive/combine.rs

This is a series of loosely coupled, incremental refactors detailed in individual commit messages.
* Support multiple bindings via a single combiner.
This allows a single combiner to support materialization and capture workflows operating over multiple bindings simultaneously, with a much tighter bound over memory usage when there are many bindings because they share a common MemTable.
* Validate documents when spilling to disk.
This is expected to increase end-to-end throughput for warehouse connectors because it makes the Store phase of the transaction -- when connectors can't do other useful parallel work -- much shorter when draining a SpillDrainer.
* Removing `drain_while` and adding an owned impl Iterator for MemDrainer / SpillDrainer.
This makes the API much more …

doc::combine: multiple bindings, support iteration, and move up validation

---

crates/models/src/schemas.rs
crates/validation/tests/model.yaml
crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap
crates/validation/tests/snapshots/scenario_tests__keyed_location_wrong_type.snap
crates/validation/tests/snapshots/scenario_tests__storage_mappings_not_found.snap

The sentinel purpose is two-fold:
* It explicitly marks that an inferred schemas was not available.
* It causes downstream tasks to fail on the very first read document, so that they can be re-published with an updated inferred schema.
Tested: end-to-end on a local stack with `source-postgres-batch`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

models: when not found, use an inferred schema sentinel

---

crates/flowctl/src/catalog/delete.rs

fixes #1213
`flowctl catalog delete` was broken by the change to pagination. It doesn't make sense to use pagination for this request anyway, since it's a POST and the response body is empty. This changes it to just use `api_exec`, which works as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1214)

flowctl: fix cataglog delete

---

site/docs/reference/Connectors/capture-connectors/mysql-batch.md

Adds a stub documentation page for the new batch MySQL connector so that the UI sidebar won't be empty.
This (and the corresponding Postgres page) really ought to be fleshed out more once I get back next week, but this should suffice for now.
This creates https://docs.estuary.dev/reference/Connectors/capture-connectors/mysql-batch/
I've already set up https://go.estuary.dev/source-mysql-batch pointing there as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1216)

docs/mysql-batch: Stub so the UI won't look too awful

---

Cargo.lock
crates/flowctl/src/generate/mod.rs
crates/flowctl/src/raw/discover.rs
crates/sources/Cargo.toml
crates/sources/src/bundle_schema_test.yaml
crates/sources/src/indirect.rs
crates/sources/src/inline.rs
crates/sources/src/scenarios/mod.rs
crates/sources/src/scenarios/snapshots/sources__scenarios__test__endpoints_captures_materializations-2.snap
crates/sources/src/scenarios/snapshots/sources__scenarios__test__schema_with_references-2.snap
crates/sources/src/scenarios/snapshots/sources__scenarios__test__test_case-2.snap
crates/sources/src/snapshots/sources__bundle_schema__test__bundle_generation.snap
crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap

When inlining catalog specs, remove the imports of inlined schemas and config resources. These resources are no longer "imported" (they've been inlined), and pragmatically this makes inlining an idempotent operation.
This fixes a current bug in `flowctl generate` where it may attempt to inline a schema twice, producing an invalid JSON schema bundle.
Also add a missing symmetrical case for indirection of local materialization endpoint configs.
Tested:
* All `sources` scenario tests are round-tripped through inlining and then indirection.
* Tested with a substantive real-world catalog as well.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4w …

sources: remove imports of inlined resources

---

Cargo.lock
Cargo.toml
crates/bindings/src/service.rs
crates/build/src/lib.rs
crates/coroutines/Cargo.toml
crates/coroutines/src/lib.rs
crates/derive-sqlite/src/connector.rs
crates/flowctl/src/generate/mod.rs
crates/flowctl/src/preview/mod.rs
crates/journal-client/Cargo.toml
crates/runtime/Cargo.toml
crates/runtime/src/derive/combine.rs
crates/runtime/src/derive/image.rs
crates/runtime/src/derive/local.rs
crates/runtime/src/derive/mod.rs
crates/runtime/src/derive/rocksdb.rs
crates/runtime/src/lib.rs
crates/runtime/src/unary.rs
ops-catalog/schema-inference.flow.yaml

Add a `coroutine` crate to enhance the ergonomics of writing complex stream transformations in Rust.
Begin refactors of the `runtime` crate to use them, and begin transitioning to `anyhow::Result` as the primary stream item type.
Add inferred schema shape tracking, widening, and logging for derivations.
See individual commits for more detail.
Testing:
- End to end on a local stack to verify derivation inference
- With `flowctl preview` of high-volume production derivations (wikipedia sampled)
Derivations automatically produce inferred schemas.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as …

rust coroutines and derivation inference

---

site/docs/reference/Connectors/capture-connectors/mongodb.md

- update mongo capture docs to reflect new oplog access requirement and explanation of how we do backfills
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1196)

docs: source-mongodb docs updates

---

supabase/functions/billing/get_tenant_payment_methods.ts

To make life easy on the UI we are not passing back what tenant was used when getting the payment methods.
N/A
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1229)

Adding in what tenant was being fetched with the payment

---

go.mod
go.sum

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1236)

go.mod: bump gazette to bring in allocator improvements

---

crates/doc/src/combine/memtable.rs
crates/doc/src/combine/mod.rs
crates/doc/src/combine/spill.rs
crates/doc/tests/spill_merge_fuzz.rs

Typically such documents will be reduced with another document, meaning that a validation-on-spill is wasted work because we'll need to re-validate the reduced output.
Cleanup CHUNK_TARGET_SIZE range which no longer had meaning as a range. No functional changes here, this is just a cleanup.
Add new tests of MemTable::spill and SpillDrainer covering validation of reduced and !reduced documents.
(anything that might help …

doc: defer validation of reduced documents on spill

---

supabase/migrations/35_free_tier_credit.sql
supabase/tests/billing.test.sql

The free-tier credit is intended to zero out usage incurred while the tenant is covered by the free tier, before their free trial starting. **If they do not have a trial start date, the free tier credit covers all time.** 
Instead of implementing this as a credit capped at the free tier limits, we decided to built it as a blanket credit for all usage prior to the free trial start date. Reason being, the total due should still be $0 until the free trial is over. If we built it as a capped credit, tenants would be billed for their usage exceeding the free tier limits before they get moved into the free trial, which is not desired.
- - - …

Update billing to include free-tier credit

---

supabase/functions/billing/delete_tenant_payment_method.ts
supabase/functions/billing/get_tenant_invoice_data.ts
supabase/functions/billing/get_tenant_payment_methods.ts
supabase/functions/billing/index.ts
supabase/functions/billing/set_tenant_primary_payment_method.ts
supabase/functions/billing/setup_intent.ts
supabase/functions/billing/shared.ts

Adding the CORS headers to the `billing` functions.
N/A
N/A
This is just to be super safe. Everything is working today but we should probably be including these. This especially helps locally when there can be some wonky CORS issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1233)

Adding the CORS headers to the billing functions

---

supabase/migrations/36_prune_unchanged_draft_specs.sql

Initially, the `unchanged_draft_specs` view was written as being owned by the `authenticated` role in postgres, to ensure that it always used the RLS policies of the caller. But Supabase has revoked the `superuser` attribute of the `postgres` role and no longer provides a way to authenticate as a superuser. This means that `alter view ... set owner to authenticated` no longer works because `authenticated` does not have the necessary permission to create a view. See [this thread](https://github.com/orgs/supabase/discussions/9314) for more.
In this case, we're able to work around this by granting select permission to the `authenticated` role. This works because both `draft_specs_ext` and `live_specs_ext` perform their own enforcement of authZ, so it's safe to bypass RLS. …

control-plane: change authz grants of unchanged_draft_specs view

---

crates/agent-sql/src/publications.rs

When deleting a collection, the `add_inferred_schema_md5` function is still called. This panics because that function included a condition on `spec_type = 'collection'`, which is no longer true for collections being deleted. This results in panic because we explicitly expect one row to always be updated. This removes the condition, so that the live spec is updated by id only.
This bug can be reproduced by deleting any collection spec.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1247)

agent: fix panic on collection deletion

---

crates/doc/src/bump_str.rs
crates/doc/src/bump_vec.rs
crates/doc/src/combine/memtable.rs
crates/doc/src/combine/spill.rs
crates/doc/src/extractor.rs
crates/doc/src/heap.rs
crates/doc/src/lazy.rs
crates/doc/src/lib.rs
crates/doc/src/reduce/mod.rs
crates/doc/src/reduce/schema.rs
crates/doc/src/reduce/set.rs
crates/doc/src/reduce/strategy.rs
crates/doc/src/ser.rs
crates/doc/tests/reduce_annotations_test.rs

LazyNode::Heap no longer owns its HeapNode, and instead takes its value by-reference. This makes reduction non-destructive: it's now possible to perform part of a reduction, realize that the operation cannot complete, and backtrack without destroying its input documents.
No changes to function or semantics in this commit. It's laying groundwork for allowing the combiner to handle non-associative reductions.
BumpStr is marked as Copy (it always has been).
BumpVec is not, but it is safe to re-use its structure -- as LazyNode does when promoting a reference into a HeapNode -- subject to certain conditions (if you mutate a reduced HeapNode, the changes may be visible to other HeapNodes). LazyNode::Heap takes an immutable reference, making it impossible to do this accidentally in the context …

doc: make LazyNode::Heap and reduction by-reference

---

go/runtime/materialize.go

Look for a connector image match in the config, rather than a task name suffix, as not all tasks have that suffix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1253)

go/runtime: activate string truncation feature for select connectors

---

site/docs/reference/Connectors/capture-connectors/alloydb.md
site/docs/reference/Connectors/capture-connectors/google-cloud-sql-sqlserver.md
site/docs/reference/Connectors/materialization-connectors/google-cloud-sql-sqlserver.md

1.  Updates Cloud SQL documentation to support SQL Server password complexity requirements: https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16#password-complexity
2. Modifies the documentation describing the default port for Cloud SQL SQL Server
3. Removed local IP description for SSH tunneling in AlloyDB Docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1258)

AlloyDB and Cloud SQL SQL Server Documentation Fixes

---

crates/agent/src/logs.rs

Sanitizes log lines before persisting them to `internal.log_lines`. We observed a failure in production due to a connector logging a null byte. Postgres does not allow nulls in `TEXT` columns, even though they are valid UTF-8, so this removes them before persisting to postgres. Log lines are left unchanged if they're not being saved to postgres.
I've tested that this doesn't completely break anything, but not that this actually allows us to work end to end with a connector that logs out null bytes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1257)

agent: sanitize null bytes in log lines

---

crates/flowctl/src/draft/mod.rs

The `prune_unchanged_draft_specs` function had a last-minute rename of the argument parameter, which was not reflected at the callsite in flowctl, resulting in failure to publish.
This just updates the parameter to match, which fixes publication failure.
- `flowctl catalog publish --source flow.yaml`
On master, this fails with:
```
Error: pruning unchanged specs
Caused by:
404 Not Found: {"code":"PGRST202","details":"Searched for the function public.prune_unchanged_draft_specs with parameter draft_id or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache.","hint":"Perhaps you meant to call the function public.prune_unchanged_draft_specs(prune_draft_id)","message":"Could not find the function …
```

flowctl: fix draft pruning

---

site/docs/reference/Connectors/capture-connectors/MySQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL.md

Removed recommendations to use a reader or replica in MySQL and PostgreSQL for Aurora. Flow connection must happen with the primary database to enable watermark table writing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1261)

Removed Aurora docs recommending replica/reader

---

crates/runtime/src/unseal/mod.rs

The `runtime::unseal` module was a little aggressive about checking to make sure `sops` and `jq` are both on the path.  This would cause errors, even in cases where the connector configuration wasn't actually sops-enctypted.  This moves those checks to be performed only after it's determined that the config needs to be decrypted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1264)

flowctl: don't require sops unless we actually need it

---

crates/doc/src/ptr.rs
crates/doc/src/shape/limits.rs
crates/doc/src/shape/location.rs
crates/doc/src/shape/mod.rs
crates/json/src/lib.rs
crates/parser/src/decorate.rs

This flake was caught by quickcheck (only sometimes) and was causing Flow CI to intermittently fail.
The one thing I'm not confident on is calling this variant `AdditionalProperties`, since the variant for array's `additionalItems` is called `Token::NextIndex`, not `Token::AdditionalItems`. Thoughts @jgraettinger?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1200)

fix: Differentiate between an object that has a literal `*` field, and a pointer to an object's `additionalProperties` shape.

---

supabase/migrations/38_change_to_gigabytes.sql
supabase/tests/billing.test.sql

Update billing calculations to use `bytes*10^9`, which is the correct definition of "1 Gigabyte", instead of the previous `bytes*2^30` which is technically "1 Gibibyte"
Also remove unused `billing_report`, not to be confused with `internal.billing_report_202308`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1269)

billing: Change to use `10^9` instead of `2^30`

---

crates/doc/src/ser.rs

The `SerPolicy` was panicking due to attempting to split a string in the middle of a utf8 character. Updates the policy to instead truncate strings at the nearest character boundary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1283)

doc: fix panic in `SerPolicy`

---

crates/agent/src/publications.rs
crates/agent/src/publications/builds.rs
crates/agent/src/publications/specs.rs
crates/build/src/lib.rs
crates/flowctl/src/local_specs.rs
crates/flowctl/src/raw/mod.rs

Introduces the `build::BuildOutput` type, which represents the results of a build.  This new type includes all tables, even when there are build errors. It replaces the binary `Result<_,_>` type with one that is able to simultaneously represent both the errors that occurred during the build, as well as the outputs from the successful stages of the build.
The immediate effect of this, and motivation for doing it, is that if fixes a bug that prevented the agent from notifying users about collections with incompatible schema changes.  The agent relies on the presence of `built_materializations` in the output in order to populate the `incompatible_collections` array in the publication status.  The prior `Result` representation didn't propagate `built_materializations` if …

build: return all tables after build failure

---

go/protocols/materialize/lifecycle.go
go/protocols/materialize/transactor.go

- Currently there is a potential for deadlock if the `transactor.Destroy()` of a connector depends on cancellation of the Load phase. For example, this is the case for sqlserver and snowflake which wait for the database connection established for the load phase to be closed, and this closing of the connection blocks until existing operations are terminated. This can be reproduced by having a connector error during commit phase, while still processing its load phase (See [this commit](https://github.com/estuary/connectors/pull/1078/files) which emulates this situation).
- This happens as we do not cancel the load phase's context when there is a failure in the commit stage, this means any pending work in the load phase will never be terminated.
- This pull-request addresses …

materialize/transactor: cancel load before Destroy() if commit fails

---

.github/workflows/flowctl-release.yaml

Instead of ubuntu-latest (22.04).
This should improve compatibility with Linux boxes still running 20.04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1297)

CI: flowctl release uses ubuntu-20.04 runner

---

supabase/functions/alert-data-processing/index.ts

Adding this keyword to the subject allows it to work with a Zenduty feature to automatically resolve alerts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1302)

control-plane: add 'resolved' keyword to alert resolution emails

---

crates/journal-client/src/read/uncommitted.rs

Fixes a panic in `flowctl preview` that could happen after reading through the end of a source collection. Fixes the `continue_after_eof` function so that we no longer return `None` for blocking reads.
This ware reported in [this slack thread](https://estuary-dev.slack.com/archives/C01G7CFNA8K/p1701858388568069)
I was able to reproduce it locally by running `flowctl preview --source flow.yaml` with the following `flow.yaml`:
```yaml
materializations:
phil/test/preview-mat:
endpoint:
connector:
image: ghcr.io/estuary/materialize-sqlite:v1
config: {}
bindings:
- source:
name: phil/test/2023-11-13/webhook-data
resource:
table: webhook_data
```
Prior to this change, that command would return:
```
thread 'main' panicked at crates/flowctl/src/preview/journal_reader.rs:93:28: …
```

flowctl: fix panic in preview

---

crates/runtime/src/rocksdb.rs
go.mod
go.sum
go/runtime/flow_consumer.go
supabase/seed.sql
tests/snapshots/capture_hello_world__basic__stdout.json
tests/test_capture_hello_world.py

Bug fixes for reverted runtime release:
* Fix `consumer.Store` vs `*Materialize` et all nil checks.
* Update gazette pin to bring in relaxed FSM property handling.
* Add a modification-time-based migration for `state.json` vs RocksDB selection for initial checkpoint and connector state.
- - - …

fixes for reverted runtime release

---

crates/runtime/src/capture/connector.rs
crates/runtime/src/derive/connector.rs
crates/runtime/src/lib.rs
crates/runtime/src/materialize/connector.rs

From 4MB => 64MB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1312)

runtime: increase maximum message size for dialed containers

---

go.mod
go.sum

Pick up handling for recovered ACK intents of deleted journals.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1313)

go.mod: bump gazette pin

---

Cargo.lock
Cargo.toml
crates/async-process/Cargo.toml
crates/async-process/src/lib.rs
crates/connector-init/src/capture.rs
crates/connector-init/src/derive.rs
crates/connector-init/src/lib.rs
crates/connector-init/src/materialize.rs
go/flowctl-go/cmd-api-discover.go

Simplify the async-process crate by having it send SIGKILL in its drop
handler, to make sure `docker run` invocations are stopped. This avoids
a wedge we've observed in production where `docker run` doesn't exit
when asked (via SIGTERM) and we later deadlock waiting for its stderr to
close (which never happens).
Since `docker run` is now SIGKILL'd, also add a timeout-based watchdog
to flow-connector-init which ensures that it reliably exits after a
period of inactivity. This lets us avoid relying on docker to proxy
shutdown signals correctly, which in my testing is an iffy proposition.
Testing:
* Confirmed this resolves my (limited) reproduction of deadlocks observed in production.
* Local stack:
* In normal operation `flow-connector-init` continues to run indefinitely.
* When a shard is …

async-process: SIGKILL on drop and connector-init idle timeout

---

site/docs/reference/Connectors/capture-connectors/mongodb.md

- We had a user hit this. They gave us collection permissions for change stream but that does not work for us. We need access on the database.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1335)

source-mongodb: make it explicit that we require database permission

---

site/docs/reference/Connectors/materialization-connectors/Snowflake.md

- Document `TIMESTAMP` and `TIMESTAMP_TYPE_MAPPING` behavior
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1330)

snowflake: document TIMESTAMP_TYPE_MAPPING

---

crates/parser/src/format/character_separated/error_buffer.rs
crates/parser/src/format/mod.rs

- This fixes an issue where if during `prefill_buffer` we would already hit the error limit, we would not log any of the errors.
- Moreover, makes the error limit exceeded exception include the first error in the buffer to make it more informative
- One thing that I find missing though is having the file name that is failing as part of the errors, that makes it a lot more useful for users. Looking at how the plumbing works, I think we need to make that change in `filesource` library in connectors repo to include the file name, but it's a bit tricky given that the parser logs the error and `filesource` abstains from logging anything to leave the parser error as the last log line
**Documentation …

parser: error logs when parsing failes and limit is exceeded

---

crates/agent/src/handlers.rs
crates/agent/src/main.rs

We've observed cases where the agent hangs when shutting down the runtime after an error occurs. This changes it to use the same pattern that's used elsewhere in our code base for shutting down the tokio runtime with a timeout, to prevent it from hanging indefinitely.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1334)

agent: use a timeout when shutting down the runtime

---

crates/derive-typescript/Cargo.lock
crates/derive-typescript/Cargo.toml
crates/derive-typescript/src/lib.rs

Pin to `master` rather than an old work branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1345)

derive-typescript: bump Cargo.toml pin for Flow

---

Tiltfile
crates/flowctl/src/collection/mod.rs
crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/lib.rs
crates/flowctl/src/ops.rs

* Update local-stack certificate generation to create certs that work with rustls, when used with:
SSL_CERT_FILE=~/estuary/data-plane-gateway/local-tls-cert.pem
* When reading ops logs, obtain a DPG token which is authorized for the task name, rather than the ops collection.
* Drop stats for now to remove flowctl surface area.
* Remove deprecated include-partition / exclude-partition (began to panic with auth_prefixes addition to ReadArgs for unknown reasons).
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a …

flowctl: enable self-service task logs

---

go/flowctl-go/cmd-api-discover.go

Adds an exception to our growing list of discover timeout exceptions. I'm sure eventually we'll thread through some configuration of this from the `connector_tags` table 😉 but not today
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1355)

flowctl-go: discover timeout exception for redshift

---

supabase/migrations/08_discovers.sql

The UI needs to set the `update_only` column during capture edit.
This is in support of : https://github.com/estuary/ui/pull/955
N/A
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1360)

Allow authorized users to set the `update_only` column on `discovers`

---

crates/json/src/schema/formats.rs

Previously strings like `"1_234"`, `"123_"`, `"1__2"`, `" _123.3"` (etc.) positively validated as having a format of `integer` or `number`. This is problematic for many systems that will process these downstream that do not have such permissive handling for strings as integers/numbers. It is also a little questionable whether we should consider these strings as numeric values in the first place.
This changes those types of strings to not validate as `integer` or `number`, and will instead cause schema inference to consider them to be strings with no format annotation.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJ …

crates/json: don't validate strings with underscores as integers or numbers

---

crates/runtime/src/capture/connector.rs
crates/runtime/src/container.rs
crates/runtime/src/derive/connector.rs
crates/runtime/src/image_connector.rs
crates/runtime/src/materialize/connector.rs

This should fix an issue encountered by people running a local Flow stack under WSL. The problem is that in that case, Docker containers run in a separate VM to the one hosting the Linux VM, meaning that the container IP address exposed via `docker inspect` is not accessible from the "host". The solution here is to ask Docker to bind a port on the host to the corresponding port inside the container.
In order to prevent binding every task to a host port in production (which runs Linux), we ended up turning off host-port mapping on Linux entirely because we didn't have a better way to identify local vs prod environments.
We have since introduced an `allow_local` flag, and can condition host-port mapping on that, enabling Flow to run inside WSL.
I …

Update `runtime::container::start()` to take a new `allow_local` flag

---

.devcontainer/release.Dockerfile
crates/json/src/number.rs

Fixes a bug in the ordering of JSON numbers that are greater than the maximum signed 64 bit integer.  The previous ordering logic would convert the unsigned integer to signed, which would overflow if the value was larger than `i64::MAX`, leading to an incorrect ordering result.  This fixes that by adding in special cases for comparisons between negative signed integers and unsigned integers. The casts from `u64 -> i64` were replaced with casts from `i64 ->
u64`, relying on the previous checks to ensure that the `i64` value is not negative.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1367)

json: fix ordering of integers greater than i64::MAX

---

site/docs/reference/Connectors/materialization-connectors/starburst.md

Add starburst documentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1363)

Starburst materialization documentation

---

.github/workflows/flow-web.yaml
Cargo.lock
crates/flow-web/Cargo.toml

To import `flow-web` into vitest we need to set the `type` and `main` in the `package.json` file. Right now `wasm-pack` is not including these but there is a PR has merged that should fix this. 
Also hard cording the name for the output to `flow_web` to ensure these new props are set correctly.
N/A
N/A
As called out in the comment in the YAML - this is kind of hacky but is a known hack that folks have been doing to work around the issue. We should probably keep an eye on `wasm-pack` to see when it releases a new version (hopefully with the fix for this)
- - - …

Inserting `type` and `main` into `package.json` for flow-web

---

crates/models/src/journals.rs
crates/models/src/lib.rs
crates/validation/src/storage_mapping.rs

When validating storage configurations, we were previously using the same regex for all types of cloud storage. But it turns out that GCS is more permissive, and Azure is more restrictive.  This introduces separate regexes for each type of cloud storage provider.  For custom storage endpoints, the GCS regex is used, as it's the most permissive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1370)

validation: fix bucket name validation for GCS and Azure

---

Tiltfile
crates/agent/src/connector_tags.rs
crates/agent/src/discovers.rs
crates/agent/src/jobs.rs
crates/agent/src/main.rs
crates/runtime/src/container.rs
crates/runtime/src/image_connector.rs
go/flowctl-go/cmd-api-discover.go

When running locally using `tilt up` on a mac, I noticed I was unable to run any connectors.  This turned out to be caused by a recent change to have the runtime expose ports based on the presence of that flag, instead of being based on the host OS type.  When running on mac, exposing the ports is required, or else the runtime itself can't connect to the containers.  So this carries on the previous work, and threads through the `--allow-local` argument in the couple of places where it was missing.  The end result is that running locally once again works on mac.
Run `tilt up` ;)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1374)

thread through `--allow-local` argument when running locally

---

crates/validation/src/materialization.rs
crates/validation/tests/scenario_tests.rs

Updates our valiation logic to only consider unsatisfiable constraints an error in the case that the field isn't explicitly excluded. This allows users to change the type of a field without needing to backfill, as long as they exclude the changed field.
- materialize a collection that has `fieldA: { type: string }`, using one of the database connectors
- Update the source collection schema to change to `fieldA: { type: integer }`
- The publication should fail due to the unsatisfiable constraint
- Explicitly exclude `fieldA` from the field selection
- Now, the publication should succeed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1375 …

validation: allow unsatisfiable constraints on excluded fields

---

site/docs/concepts/advanced/evolutions.md
site/docs/reference/Connectors/capture-connectors/zendesk-support.md
site/docs/reference/Connectors/materialization-connectors/amazon-redshift.md
site/docs/reference/Connectors/materialization-connectors/motherduck.md
site/docs/reference/Connectors/materialization-connectors/pinecone.md
site/docusaurus.config.js
site/package-lock.json
site/package.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1386)

site: update docusaurus and unbreak the documentation site

---

.github/workflows/derive-typescript.yaml
.github/workflows/flow-web.yaml
.github/workflows/flowctl-release.yaml
.github/workflows/flowctl-test.yaml
.github/workflows/main.yml
go.sh

We can remove this once off of Ubuntu 20.04
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1391)

go.sh: add explicit flag for c++17

---

crates/connector-init/src/lib.rs

It's not valid to leave it as zero (INVALID).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1400)

connector-init: set connector_type on protocol check Spec

---

crates/agent/src/connector_tags.rs

Use the `build::CONNECTOR_TIMEOUT` for spec requests, since the 10 second timeout was likely causing more failures than necessary with how long docker image pulling can take. Currently `build::CONNECTOR_TIMEOUT` is set to 5 minutes.
- - - …

agent: use 5 minute timeout for spec runs

---

supabase/migrations/44_draft_associated_collections.sql
supabase/tests/draft_collections_eligible_for_deletion.test.sql

Facilitate the deletion of a capture and its associated collections in the UI by populating a specified draft with the collections eligible for deletion. A collection is eligible for deletion if it is not consumed by an active task.
1. Initialize a draft with a capture pending deletion.
1. Execute the `draft_collections_eligible_for_deletion` procedure, supplying the live spec ID of the capture of interest and the ID of the draft created in the previous step.
1. Observe that the collections that are not consumed by another active task in the system are added to the draft and slated for deletion.
N/A
This is a dependency of `ui` [issue 939](https://github.com/estuary/ui/issues/939). Integration …

Draft collections eligible for deletion

---

go/shuffle/read.go

Time out and cancel reads after about a couple minutes of inactivity, rather than 35 minutes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1405)

go/shuffle: lower the read channel capacity

---

crates/models/src/journals.rs
crates/models/src/lib.rs
crates/sources/src/scenarios/snapshots/sources__scenarios__test__storage_mappings-2.snap
crates/sources/src/scenarios/snapshots/sources__scenarios__test__storage_mappings-3.snap
crates/sources/src/scenarios/snapshots/sources__scenarios__test__storage_mappings.snap
crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap

Allows setting the region for S3 storage mappings, for buckets that are not in the `us-east-1` region.
See also: https://github.com/gazette/core/pull/365. We will need to be running on this version of Gazette prior to deploying the changes here.
Closes https://github.com/estuary/flow/issues/1409
Create a storage mapping like this, and it will now work:
```json
{
"stores": [
{
"provider": "S3",
"bucket": "my-bucket-in-us-west-2",
"region": "us-west-2",
"prefix": "collection-data/"
}
]
}
```
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief …

models/journals: region configuration for S3 storage mappings

---

crates/doc/src/bump_vec.rs

There was a recent change in the rust compiler that changed the aligmnent of u128 values. See: https://blog.rust-lang.org/2024/03/30/i128-layout-update.html This updates a BumpVec test that had asserted the old values, so that the test now hopefully passes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1430)

Fix BumpVec test after change to u128 alignment

---

crates/flowctl/src/ops.rs
crates/flowctl/src/raw/mod.rs

`flowctl stats` was removed a few months ago due to concerns about UX. I've really missed having it, though, because the process for finding and reading from the stats journal using `flowctl-go` and port-forwarding is a pain. So this adds the subcommand back in, but moves it under `flowctl raw` to address the UX issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1432)

flowctl: resurrect stats subcommand under raw

---

supabase/migrations/47_registered_avro_schemas.sql
supabase/tests/registered_avro_schemas.test.sql

This table provides a global namespace for u32 schema IDs which appear within encoded Kafka keys and values.
IDs are integrated into our catalog authorization model, so one is still only allowed to inspect a schema to which one is read authorized, but the table still facilitates deduplication of common schema shapes.
To register or retrieve a schema, a user must only be read-authorized to its corresponding catalog name. This means that all readers of a shared collection are able to re-use the same schema ID.
Testing:
* I've performed end-to-end testing on a local stack with `dekaf`, which uses the table for registering content-addressed AVRO schemas. PR for that forthcoming.
(list …

supabase: add `registered_avro_schemas` table

---

go.mod
go.sum

Bring in update that effectively disables connection-level flow control to gazette brokers (while retaining stream-level flow control).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1444)

go.mod: bump gazette to d612fdc

---

.devcontainer/release.Dockerfile
crates/agent-sql/src/directives/mod.rs
crates/agent-sql/src/directives/storage_mappings.rs
crates/agent/src/directives/accept_demo_tenant.rs
crates/agent/src/directives/beta_onboard.rs
crates/agent/src/directives/click_to_accept.rs
crates/agent/src/directives/grant.rs
crates/agent/src/directives/mod.rs
crates/agent/src/directives/storage_mappings.rs
crates/agent/src/logs.rs
crates/agent/src/main.rs
crates/models/src/journals.rs
crates/models/src/references.rs
crates/models/src/snapshots/models__journals__test__storage-json-schema.snap
supabase/migrations/47_republish_prefix.sql
supabase/migrations/48_storage_mapping_directive.sql

Introduces two different pieces of backend functionality in support of a UI for updating storage mappings. The first is a directive for updating the actual storage mappings, including validating the new mapping by ensuring we have appropriate permissions to the bucket. The second is a postgres function that creates a publication of all the existing specs under a given prefix.
Only top-level tenant prefixes are supported at this time. It shouldn't be too hard to support adding new prefixes in the future, but it seemed wise to avoid the complexity for now.
The directive is meant to validate our access to the users storage buckets. It only supports GCS and S3 at this time, but it shouldn't be too hard to add support for azure and even custom storage endpoints. The checks are …

agent: backend support for updating storage mappings

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL/PostgreSQL.md

Adds a section to the `source-postgres` docs discussing replication slot `confirmed_flush_lsn` vs `restart_lsn`, what happens if the slot stops advancing due to capture downtime or long-running transactions, how the `max_slot_wal_keep_size` setting can be used to protect a production database from running out of disk space, and what the potential downsides are of doing that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1449)

docs/source-postgres: Add discussion of WAL retention

---

supabase/migrations/49_tenant_hide_preview.sql

- Tested with https://github.com/estuary/ui/pull/1100 and it works as expected 👍🏽 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1455)

tenants: "hide_preview" column to hide collection data preview

---

crates/flowctl/src/local_specs.rs
crates/flowctl/src/preview/mod.rs
crates/json/src/number.rs
crates/runtime/src/harness/capture.rs
crates/runtime/src/harness/fixture.rs
crates/runtime/src/harness/materialize.rs

- The existing implementation only supported cases where bindings had a 1:1 relation with collections, but multiple bindings may read from the same collection, and we use this in our materialization integration tests. This pull-request introduces the ability to have multiple bindings read from the same collection.
- Added the `output_state` and `output_apply` options to preview so that the state and action description of a connector may also be output by `flowctl preview`, these are useful for materialization integration tests
- Required by https://github.com/estuary/connectors/pull/1571 …

flowctl(preview): multiple bindings may read from one collection

---

go.sh

This is required for building on ARM macs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1470)

build: add SystemConfiguration framework CGO flag for Darwin builds

---

Cargo.lock
crates/doc/Cargo.toml
crates/doc/src/reduce/mod.rs
crates/doc/src/reduce/parsed_number.rs
crates/doc/src/reduce/strategy.rs
crates/json/src/number.rs

Refactor checked_add out of json::Number, and add doc::ParsedNumber which additionally supports BigDecimal representations parsed from JSON string types.
Update the `sum` reducer to know about these and handle them.
- - - …

crates/doc: support arbitrary precision with `sum` annotation

---

crates/doc/src/shape/inspections.rs
crates/validation/tests/snapshots/scenario_tests__shape_inspections.snap
examples/reduction-types/sum.flow.yaml

Improve the error message to relate that `format: number` may be used.
Update catalog test to provide coverage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1481)

crates/doc: relax `sum` inspection to allow numeric strings

---

go/flowctl-go/cmd-api-discover.go

We no longer use YAML here (this whole subcommand is vistigial) and can directly thread through bytes without any potential for re-ordering (which breaks SOPS MACs).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1475)

flowctl-go: api discover should pass-through config directly

---

crates/agent/src/publications.rs
crates/agent/src/publications/builds.rs
crates/agent/src/publications/handler.rs

Updates the publisher to store test errors separately from other types of errors, and to set the `TestFailed` status if any test errors are present. Previously, test failures would result in a `BuildFailed` status, which was unhelpful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1499)

agent: return TestFailed status when tests fail

---

Cargo.lock
crates/agent/src/controllers/capture.rs
crates/agent/src/controllers/catalog_test.rs
crates/agent/src/controllers/collection.rs
crates/agent/src/controllers/materialization.rs
crates/agent/src/controllers/mod.rs
crates/agent/src/controllers/publication_status.rs
crates/agent/src/controllers/snapshots/agent__controllers__test__status_json_schema.snap
crates/agent/src/draft.rs
crates/agent/src/publications/status.rs

Adds an automatically generated json schema for the agent controller status objects. The goal is just to make it easier to consume status information.
Also updates the default publication history length from 3 to 5, which has just felt like a better number to ease debugging schema evolution issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1500)

agent: generate JSON schema for controller status

---

crates/agent/src/controllers/publication_status.rs
crates/agent/src/controlplane.rs
crates/agent/src/publications/specs.rs
supabase/migrations/51_backfill_controllers.sql

Adds some logging and better errors when failures occur due to `built_spec` being null
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1503)

agent: add logging and errors around null built_specs

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/dropbox.md

Create documentation for estuary/connectors#1751, the new `source-dropbox` connector.
These docs were based off of the existing connectors that use the `filesource` package, like [SFTP](https://docs.estuary.dev/reference/Connectors/capture-connectors/sftp/), [Amazon S3](https://docs.estuary.dev/reference/Connectors/capture-connectors/amazon-s3/), and [Google …

docs: Create documentation for source-dropbox connector.

---

Cargo.lock
Cargo.toml
crates/doc/src/reduce/schema.rs
crates/doc/src/shape/limits.rs
crates/doc/tests/shape_fuzz.rs
crates/gazette/src/uuid.rs
crates/runtime/src/capture/protocol.rs
crates/runtime/src/derive/protocol.rs

Introduces a `depth_limit` to `enforce_shape_complexity_limit` to prevent inferred schemas from becoming too deeply nested. Deeply nested json can present problems, as essentially all parsers have a limit on the amount of nesting that they will accept. We've found that deeply nested documents will result in schemas with roughly double the levels of nesting because of things like `properties: { ... }`. And deeply nested JSON schemas also just aren't that useful in Flow, anyway, since if someone has 64 layers of nesting, they likely don't want us flattening out all their fields into separate columns. So this sets the limit to 63 levels of nesting, which was chosen as the most conservative value that results in schemas that can be parsed by `serde-json`.
**Also fixes CI** …

doc: limit maximum depth of schema inference

---

site/docs/reference/Connectors/capture-connectors/snowflake.md

It says "materializations" where it ought to say "captures"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1542)

docs: Fix example capture spec for Snowflake CDC

---

Cargo.lock
crates/doc/Cargo.toml
crates/doc/src/extractor.rs
crates/doc/src/shape/limits.rs
crates/gazette/src/lib.rs
crates/proto-gazette/Cargo.toml
crates/proto-gazette/src/lib.rs
crates/proto-gazette/src/uuid.rs
crates/runtime/src/uuid.rs

See commits. 
`flow_published_at` will now produce RFC-3339 date-times which preserve total order.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1548)

uuid Clocks preserve low bits of precision when mapped into Unix timestamps

---

supabase/migrations/56_delete_old_rows_faster.sql
supabase/tests/delete_old_rows.test.sql

Previously we used the `internal.delete_old_rows()` function to cleanup data that was past its retention period. This function takes long enough that it frequently times out, leaving old data in place and exacerbating the timeout issue, leading to no old data being cleaned up.
Testing has shown that the solution is simply to run the delete commands much more frequently, as it runs significantly faster when there are fewer rows to delete. Additionally, I split up the `delete_old_rows` function into separate functions for each delete statement, in order to prevent timeouts/errors in one from affecting the others.
While doing this, I also came across an important detail in the pg_cron docs: it does not automatically clean up old `cron.job_run_details`. Given the …

control-plane: delete old data with multiple jobs

---

crates/doc/src/reduce/mod.rs
crates/doc/src/reduce/schema.rs
crates/doc/src/shape/intersect.rs
crates/doc/src/shape/union.rs
crates/json/src/number.rs

This fix addresses the following scenario with inferred schemas:
- The captured data has a mix of integer and float values.
- The `minimum` and `maximum` values in the inferred schemas thus also have a mix of integer and float values, where the values themselves are equal except for some have a `.0` decimal and others do not.
- When we reduce the inferred schemas, the result will arbitrarily select either the decimal or integer value, as it considers them to be equal.
A consequence of that behavior is that it's possible for an inferred schema to flip back and forth between the decimal and integer representations, causing unnecessary publications of the inferred schema.
The fix is to adjust the behavior of `NumericShape::union`, which is used for schema reductions. This …

doc: fix numeric bounds in schema reductions

---

Cargo.lock
Cargo.toml
crates/agent/Cargo.toml
crates/agent/src/main.rs

Switches `agent` to use `jemalloc` from the allocator crate. This is being done in order to facilitate debugging of memory issues using jemalloc's built-in profiling features.
This enables the use of the `_RJEM_MALLOC_CONF` env variable for selectively enabling profiling. For example: `_RJEM_MALLOC_CONF=prof_leak:true,lg_prof_sample:0,prof_final:true`, which is recommended in the [jemalloc docs on leak detection](https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Leak-Checking). (The `_RJEM_` prefix is added by the `jemalloc-sys` crate.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1559)

agent: switch to jemalloc allocator

---

go/protocols/flow/re_exports.go
go/runtime/capture.go

We must wait for the OpFuture to resolve successfully before polling for the next capture transaction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1565)

runtime: when polling capture, wait for OpFuture to resolve

---

crates/derive-typescript/Cargo.lock
crates/derive-typescript/src/codegen/mapper.rs

Updates the dependencies of the derive-typescript crate (ran `cargo update`),
and also makes some required modifications to the tests to get the build to
work.
The image built from this should bring in the protocol changes from https://github.com/estuary/flow/commit/bba5ae475f129366e1ec51a3f357306213da7be8.
- - - …

derive-typescript: update dependencies

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL/neon-postgres.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1567)

docs: Add docs for Neon PostgreSQL variant

---

site/docs/concepts/connectors.md
site/docs/getting-started/tutorials/real-time-cdc-with-mongodb.md
site/docs/guides/connect-network.md
site/docs/reference/Connectors/capture-connectors/MariaDB/MariaDB.md
site/docs/reference/Connectors/capture-connectors/MariaDB/amazon-rds-mariadb.md
site/docs/reference/Connectors/capture-connectors/MySQL/MySQL.md
site/docs/reference/Connectors/capture-connectors/MySQL/amazon-rds-mysql.md
site/docs/reference/Connectors/capture-connectors/MySQL/google-cloud-sql-mysql.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/PostgreSQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/amazon-rds-postgres.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/google-cloud-sql-postgres.md
site/docs/reference/Connectors/capture-connectors/SQLServer/amazon-rds-sqlserver.md
site/docs/reference/Connectors/capture-connectors/SQLServer/google-cloud-sql-sqlserver.md
site/docs/reference/Connectors/capture-connectors/SQLServer/sqlserver.md
site/docs/reference/Connectors/capture-connectors/apache-kafka.md
site/docs/reference/Connectors/capture-connectors/mongodb.md
site/docs/reference/Connectors/capture-connectors/sftp.md
site/docs/reference/Connectors/materialization-connectors/Elasticsearch.md
site/docs/reference/Connectors/materialization-connectors/MySQL/amazon-rds-mysql.md
site/docs/reference/Connectors/materialization-connectors/MySQL/google-cloud-sql-mysql.md
site/docs/reference/Connectors/materialization-connectors/MySQL/mysql.md
site/docs/reference/Connectors/materialization-connectors/PostgreSQL/PostgreSQL.md
site/docs/reference/Connectors/materialization-connectors/PostgreSQL/amazon-rds-postgres.md
site/docs/reference/Connectors/materialization-connectors/PostgreSQL/google-cloud-sql-postgres.md
site/docs/reference/Connectors/materialization-connectors/SQLServer/amazon-rds-sqlserver.md
site/docs/reference/Connectors/materialization-connectors/SQLServer/google-cloud-sql-sqlserver.md
site/docs/reference/Connectors/materialization-connectors/SQLServer/sqlserver.md
site/docs/reference/Connectors/materialization-connectors/amazon-redshift.md
site/docs/reference/Connectors/materialization-connectors/mongodb.md

This just updates docs to reflect the three current possible egress IP's for Flow. 
It's all documentation, so every doc in the commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1566)

Doc updates for egress IP addresses

---

site/docs/reference/Connectors/capture-connectors/zendesk-support.md

Doc update for estuary/connectors#1832. `source-zendesk-support`'s OAuth works now, so the docs are updated to list OAuth as another authentication method. Credentials are also marked as required in the endpoint properties section.
- - - …

docs: add OAuth to source-zendesk-support

---

site/docs/getting-started/installation.mdx

Updates docs to reflect the fact that we no longer require S3 buckets to be in the us-east-1 region.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1591)

docs: we no longer require us-east-1 S3 buckets

---

crates/dekaf/src/read.rs
crates/gazette/src/journal/read_json_lines.rs
crates/gazette/src/lib.rs
crates/simd-doc/src/lib.rs
crates/simd-doc/src/tests/fixtures.rs
crates/simd-doc/src/tests/fuzz.rs
crates/simd-doc/src/tests/mod.rs
crates/simd-doc/src/transcoded.rs
crates/simd-doc/tests/parser_perf.rs

Update Parser to support continued parsing after an error in parsing a JSON document. Use a polling-based design, where a caller can add one or more chunk()'s to a Parser and then repeatedly poll it to drain all parsed or transcoded documents and errors.
Also update error tracking to provide fine-grain localization of exactly where, in the input stream, the erroring document is located.
Enhance fuzz tests to mix in errors alongside valid documents, and verify that parsing and transcoding give exactly the same outcomes.
Resolves #1584
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, …

simd-doc: allow for continued parsing after errors

---

.devcontainer/release.Dockerfile

From debian:trixie-slim. The package index is subtly different (docker-cli is required for CLI tools on debian now). Make the release image consistent with our CI environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1598)

.devcontainer/release.Dockerfile: switch to ubuntu:noble

---

site/docs/reference/Connectors/dekaf/README.md
site/docs/reference/Connectors/dekaf/dekaf-startree.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1581)

docs: Add StarTree Dekaf integration docs

---

crates/sources/src/merge.rs
crates/sources/src/merge_test_src.yaml
crates/sources/src/merge_test_tgt.yaml
crates/sources/src/snapshots/sources__merge__test__merging.snap

Use the _local_ scope, NOT the remote one, to determine the existing local scope of a resource which is being kept or over-written.
We must also clear out imports of a local spec which is being replaced, because the replacement is a fully inline model, and we're typically going to indirect it before writing out resources, which would otherwise result in duplicated imports.
Fixes #1590
Fixes #1558
(anything that might …

crates/sources: extend_from_catalog fixes

---

crates/runtime/src/materialize/task.rs

BigQuery actually has a limit of 20MiB on an individual row that can be returned via its Query API. Although we can store a row with a `flow_document` that large, we then can't read it back out using the conventional query mechanism the materialization connector currently uses.
This adds `materialize-bigquery` to the list of connectors that use `ser_policy`, which should generally reduce how often we store rows that are excessively large.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief …

runtime: hard code `materialize-bigquery` in `ser_policy`

---

site/docs/reference/Connectors/capture-connectors/MariaDB/MariaDB.md
site/docs/reference/Connectors/capture-connectors/MariaDB/amazon-rds-mariadb.md
site/docs/reference/Connectors/capture-connectors/MySQL/MySQL.md
site/docs/reference/Connectors/capture-connectors/MySQL/amazon-rds-mysql.md
site/docs/reference/Connectors/capture-connectors/MySQL/google-cloud-sql-mysql.md

This PR started out as just removing all mentions of watermark tables from our MySQL setup documentation, but then I couldn't help correcting a few other things where the docs were _really_ woefully out of date and/or simply incorrect, most notably softening our stance on binlog retention requirements and removing the bits where we officially recommended using a read replica as part of our RDS docs [1].
This is part of https://github.com/estuary/connectors/issues/1859
- https://docs.estuary.dev/reference/Connectors/capture-connectors/MySQL/
- https://docs.estuary.dev/reference/Connectors/capture-connectors/MySQL/amazon-rds-mysql/
- https://docs.estuary.dev/reference/Connectors/capture-connectors/MySQL/google-cloud-sql-mysql/
- …

docs/MySQL: Remove all mention of watermarks, plus other cleanups

---

site/docs/reference/Connectors/capture-connectors/MariaDB/MariaDB.md
site/docs/reference/Connectors/capture-connectors/MariaDB/amazon-rds-mariadb.md
site/docs/reference/Connectors/capture-connectors/MySQL/MySQL.md
site/docs/reference/Connectors/capture-connectors/MySQL/amazon-rds-mysql.md
site/docs/reference/Connectors/capture-connectors/MySQL/google-cloud-sql-mysql.md

Fixes a handful of spots where MySQL docs referred to it as MariaDB and vice versa.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1616)

docs: Trivial MySQL/MariaDB naming tweaks

---

supabase/migrations/06_connectors.sql
supabase/migrations/08_discovers.sql
supabase/migrations/09_publications.sql
supabase/migrations/15_directives.sql
supabase/migrations/19_evolutions.sql

Since we now using polling for discovers we no longer rely on the Supabase realtime capabilities. I have been keeping an eye on the project but I have a feeling they will [never guarantee messages](https://github.com/supabase/realtime#does-this-server-guarantee-message-delivery). This means all solutions we think about in the UI are based around using polling and I believe we can disable this functionality as we are not using it.
N/A
N/A
We can manually disable these settings in Supabase dashboard to cause these changes right now. This will keep that setting from getting flipped back on later.
- - - …

Disable use of `realtime`

---

crates/flowctl/src/catalog/mod.rs

I was having a weird issue where `flowctl catalog pull-specs --captures=true --collections=true` wasn't returning any captures, but `flowctl catalog pull-specs --captures=true --collections=false` was, and realized that the first command was returning 1001 specs, which is suspiciously close to PostgREST's max row limit. Turns out that even though we're paginating the inputs, we still need to paginate the queries themselves.
```
$ flowctl catalog pull-specs --captures=true --collections=true --prefix <...>
Wrote 1001 specifications under file:///Users/js/Documents/estuary/automatic-backfills/test/flow.yaml.
```
```
$ /usr/local/bin/flowctl catalog pull-specs --captures=true --collections=true --prefix <...>
Wrote 1732 specifications under …
```

fix: `flowctl catalog` does need pagination after all

---

crates/flowctl/src/catalog/mod.rs
crates/flowctl/src/draft/author.rs
crates/flowctl/src/pagination.rs

When pagination was originally introduced, this code-path was incorrectly switched to use it, despite it actually being an upsert which doesn't support pagination
https://github.com/estuary/flow/blob/f618926ccd4344233a9a972da7ec0907fc9c905c/crates/flowctl/src/draft/author.rs#L118-L124
Requests that don't support pagination just straight up ignore the `range` header. That wasn't a problem because the pagination logic only tried to fetch the next page if it got back _exactly_ the number of rows in its requested range:
https://github.com/estuary/flow/blob/f618926ccd4344233a9a972da7ec0907fc9c905c/crates/flowctl/src/pagination.rs#L124
So, this was an extremely rare edge case that would only get hit if you tried to publish exactly 1000 specs. **But**, I noticed that for …

flowctl: Batch draft spec upserts, rather than incorrectly attempting to paginate the response

---

crates/flowctl/src/pagination.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1637)

flowctl: Update pagination to use 0-indexed inclusive ranges, and page by response length rather than fixed page size.

---

crates/agent/src/controllers/materialization.rs
crates/agent/src/integration_tests/source_captures.rs

When updating the materialization spec in response to new bindings on the `sourceCapture`, ensure that `is_touch` is set to false. Otherwise, the publication will fail because the model has been changed.
This fixes a bug where controllers will fail to update the materialization because the publication fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1639)

agent: fix materialization sourceCapture updates

---

crates/agent/src/controllers/materialization.rs
crates/agent/src/controllers/publication_status.rs

Ensure that the materialization controller will always use a new publication id when applying onIncompatibleSchemaChange actions. Previously, it would re-use the publication id of the one that had failed. That doesn't work if the failed publication was a "touch" publication. Applying `onIncompatibleSchemaChange` actions modifies the model, and so the publication id must be greater than `last_pub_id`. Generating a new id ensures that is always the case.
Also includes some minor cleanups that didn't make it into the previous pr (#1639) to eliminate the duplicated `is_touch` property in favor of just checking the draft rows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1641 …

agent: use new pub_id when evolving materializations

---

go.mod
go.sum

Causes grpc-gateweay responses to include explicit zero-valued fields, rather than omitting them in responses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1654)

go.mod: bring in Gazette grpc-gateway explicit defaults

---

Cargo.lock
crates/agent/src/connector_tags.rs
crates/agent/src/controllers/materialization.rs
crates/agent/src/controllers/mod.rs
crates/agent/src/controllers/snapshots/agent__controllers__test__materialization-status-round-trip.snap
crates/agent/src/controllers/snapshots/agent__controllers__test__status_json_schema.snap
crates/agent/src/integration_tests/dependencies_and_activations.rs
crates/agent/src/integration_tests/harness.rs
crates/agent/src/integration_tests/source_captures.rs
crates/agent/src/integration_tests/user_publications.rs
crates/agent/src/publications.rs
crates/agent/src/publications/specs.rs
crates/agent/src/resource_configs.rs
crates/flowctl/Cargo.toml
crates/flowctl/src/generate/mod.rs
crates/flowctl/src/generate/snapshots/flowctl__generate__test__stub_config_resource_spec_pointers.snap
crates/models/src/lib.rs
crates/models/src/materializations.rs
crates/models/src/source_capture.rs
crates/sources/tests/snapshots/schema_generation__catalog_schema_snapshot.snap
crates/tables/src/dependencies.rs
crates/tables/src/draft.rs
flow.schema.json

- Sets the base for supporting threading through of the schema name from the second-to-last part of collection name
- Added tests for both cases (stub config) and sourceCapture
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1572)

flow: x-schema-name annotation for 2nd-to-last resource path

---

supabase/migrations/67_pub_specs_perf.sql

Fixes #1677 
Updates the `publication_specs_ext` view to fix the performance when queried by a user with many role grants, like `estuary_support/`.
I tested this against the production database, and found it to execute in under a second, even with the `estuary_support/` role.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1681)

control-plane: make publication_specs_ext work with estuary_support/

---

supabase/migrations/68_capability_constraint.sql

Ensures that no user or role grants can be created with the placeholder capabilities.
Fixes #1675
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1684)

control-plane: add constraint for grant_capability

---

crates/agent/src/publications/handler.rs
crates/agent/src/publications/specs.rs

Fixes a bug that was introduced during the publciations refactor, where the `built` and `validated` columns of `draft_specs` were no longer populated after a `dry_run` publication. This adds that back in, so that the "Field Selection" UI will work again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1687)

agent: add built specs to draft (bugfix)

---

Cargo.lock
crates/agent/Cargo.toml
crates/agent/src/main.rs

Fixes a crash in `agent` due to missing a `CryptoProvider` for `rustls` TLS connections.
I was able to reproduce this locally, and confirmed that the fix is working.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1688)

agent: setup rustls CryptoProvider

---

Cargo.lock
crates/flowctl/Cargo.toml
crates/flowctl/src/main.rs

Add the required initialization for the `rustls` crypto provider to the beginning of the agent main function, so that TLS will work again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1692)

flowctl: initialize rustls crypto provider

---

.github/workflows/flowctl-release.yaml

Switches to using clang instead of GCC in order to work around a compilation error in one of our dependencies, which is due to a bug in GCC 9. See:
https://github.com/rustls/rustls/issues/1967
Unfortunately, I can't think of a way to test this locally, since there's no way to pull the github runner image. I think we'll just need to merge and try the release again and see whether it works :grimacing:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1699)

flowctl: build using clang instead of gcc

---

crates/dekaf/src/main.rs

Require that clients send a request within thirty seconds, or close the connection.
Tested with a shorter timeout using a local franz-go client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1700)

dekaf: apply a 30 second idle session timeout

---

crates/derive/src/extract_api.rs

Allows us to see the actual cause of these errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1704)

reactor: show original error when document parse fails

---

go.mod
go.sum

Pulls in an enhancement to a panic message, to help troubleshoot a panic being observed in production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1706)

update gazette dependency to commit 2204057

---

crates/automations/src/executors.rs
crates/automations/src/lib.rs
crates/automations/tests/fibonacci.rs

Improve the Executor interface to allow for side-effects which commit with the task poll outcome.
Issue #1697 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1709)

improve `automations` interface

---

go/network/sni.go
go/network/sni_test.go
go/runtime/capture.go
go/runtime/derive.go

See commits:
* A task term context cancellation shouldn't prevent us from creating physical partitions
* A task delete-then-recreate shouldn't invalidate the SNI cache used for connector networking
- - - …

two fixes of observed production issues

---

crates/assemble/src/lib.rs
crates/validation/tests/model.yaml
crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap

This feature is unused but has been broken, because we expect users to provide length limits in MBs but then cast them to bytes.
Fix it to consistently interpret length as MB which are mapped into bytes when assembling JournalSpecs.
- - - …

assemble: correct handling of fragment length

---

crates/runtime/src/container.rs

- Add `--log-driver=none` for container connectors, since we don't want to retain their logs, given that their logs are available as gazette journals
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1735)

runtime/container: --log-driver=none for connector containers

---

crates/simd-doc/src/ffi/simd-doc.hpp

I've been having to patch my local `simd-doc.hpp` for a while now in order to get anything to build. Not sure why nobody else has encountered this (or maybe everyone has just been silently patching it like me!). Any reason we shouldn't do this?
Build error:
```
cargo:warning=In file included from /Users/js/Documents/estuary/flow/target/release/build/simd-doc-2758ffc3fafe2976/out/cxxbridge/sources/simd-doc/src/ffi/mod.rs.cc:1:
cargo:warning=/Users/js/Documents/estuary/flow/target/release/build/simd-doc-2758ffc3fafe2976/out/cxxbridge/crate/simd-doc/src/ffi/simd-doc.hpp:15:10: error: no member named 'endian' in namespace 'std'
cargo:warning=    std::endian::native == std::endian::little,
cargo:warning=    ~~~~~^
cargo:warning=/Users/js/Documents/estuary/flow/target/release/build/simd-doc-2758 …
```

fix: `simd-doc` build on MacOS (am I the only one getting this?)

---

Cargo.lock
Cargo.toml
crates/agent/src/api/create_data_plane.rs
crates/data-plane-controller/Cargo.toml
crates/data-plane-controller/src/controller.rs
crates/data-plane-controller/src/lib.rs
crates/data-plane-controller/src/logs.rs
crates/data-plane-controller/src/main.rs
crates/data-plane-controller/src/repo.rs
crates/data-plane-controller/src/stack.rs
crates/flowctl/src/poll.rs
crates/flowctl/src/raw/mod.rs
supabase/migrations/20241022035435_view_logs_and_pulumi_stack.sql

The controller uses the recent `automations` crate to monitor structured
changes to a bound data_planes and drive the data-plane to convergence.
It's modeled as a CI/CD pipeline, where an indicated branch of our
dry-dock repo (containing Pulumi and Ansible infrastructure) is deployed
for the given data-plane.
The controller performs the full lifecycle required for rolling updates:
- `pulumi up` to create new resources or respond to replacements
- Awaiting DNS propagation
- Running the Ansible playbook to provision instances
- Running `pulumi up` to reflect readiness of started instances
- Awaiting DNS propagation (again)
It also periodically refreshes a stack from remote providers to detect
changed or deleted resources, such as EC2 instance replacements, and
responds …

data-plane-controller for managing data-plane life cycles

---

crates/models/src/raw_value.rs
crates/tables/src/draft.rs
crates/validation/src/capture.rs
crates/validation/src/collection.rs
crates/validation/src/lib.rs
crates/validation/src/materialization.rs
crates/validation/src/test_step.rs
crates/validation/tests/common.rs
crates/validation/tests/transition_tests.rs

Introduce a carve-out which prevents raising an error for a materialization field selection exclude which does not exist as a projection, IF that exclusion is also present in the live model.
This allows an exclusion to carry forward and not error if (for example) the source schema is changed by automations or another user to remove the excluded location, while still catching and flagging newly-introduced exclusions which don't actually exist.
Fixes #1743
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or …

validation: relax error checks of pre-existing exclusions

---

site/docs/reference/Connectors/capture-connectors/google-analytics-4.md
site/docs/reference/Connectors/capture-connectors/google-analytics.md

Couple updates to google analytics connector docs
Modifying
- https://docs.estuary.dev/reference/Connectors/capture-connectors/google-analytics/
- https://docs.estuary.dev/reference/Connectors/capture-connectors/google-analytics-4/
1. I'm new here, open to feedback/correction
2. I couldn't preview the danger block in github.com preview so not sure it's formatted correctly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1672)

Google Analytics Connector doc updates

---

Cargo.lock
crates/agent/src/proxy_connectors.rs
crates/data-plane-controller/src/controller.rs
crates/data-plane-controller/src/lib.rs
crates/derive-sqlite/src/snapshots/derive_sqlite__validate__test__stub_generation.snap
crates/derive-sqlite/src/validate.rs
crates/flowctl/src/poll.rs
crates/flowctl/src/raw/mod.rs
crates/gazette/Cargo.toml
crates/gazette/src/journal/list.rs
crates/gazette/src/journal/mod.rs
crates/gazette/src/journal/read.rs
crates/gazette/src/lib.rs
crates/gazette/src/router.rs
crates/gazette/src/shard/mod.rs
crates/runtime/src/container.rs
go/runtime/derive.go

This is a stack of small, unrelated minor fixes and improvements. Please see individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1752)

various unrelated small fixes and tweaks

---

crates/doc/src/ser.rs
crates/runtime/src/capture/protocol.rs
crates/runtime/src/materialize/protocol.rs
crates/runtime/src/materialize/serve.rs

Restrict the maximum serialization depth of documents to < 128, which guarantees they can be parsed by serde_json and other tools like `jq` which limit maximum recursion.
We want this to be universal, because we never want serde_json to be unable to parse collection documents or loaded `flow_document` columns, and its limit on maximum depth has well-founded motivations: it would be inappropriate to, for example, completely disable limits on recursion, so we follow serde_json's lead in this regard.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've …

bound maximum serialization depth to < 128, similar to serde_json

---

crates/schemalate/src/firebolt/firebolt_queries.rs
crates/schemalate/src/firebolt/firebolt_schema_builder.rs
site/docs/reference/Connectors/materialization-connectors/Firebolt.md

New version of Firebolt has changed authentication. Now all programmatic access is done via [service accounts](https://docs.firebolt.io/Guides/managing-your-organization/service-accounts.html). Engine URL is no longer available, instead engine name should be used to connect.
This PR also fixes SQL syntax and tries to to address issues with internal keys added by Flow that don't have a defined type in the schema. 
No usage changes for Firebolt, only authentication.
Fields removed:
* Username
* Password
* Engine URL
Added fields:
* Client ID
* Client Secret
* Account Name
* Engine Name
Reflected changes in authentication in the relevant doc below, original in [Firebolt …

feat(firebolt): Update firebolt auth and sql

---

crates/derive-sqlite/src/dbutil.rs
go/shuffle/read.go

* Best-effort filtering of empty derive-SQLite blocks
* Don't wait for reader watch updates when there are no bindings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1771)

two minor runtime fixes 

---

.github/workflows/deploy-agent-api.yaml
.github/workflows/deploy-data-plane-controller.yaml
crates/agent/Dockerfile
crates/agent/entrypoint.sh
crates/automations/Cargo.toml
crates/automations/src/server.rs
crates/data-plane-controller/Dockerfile
crates/data-plane-controller/entrypoint.sh
crates/data-plane-controller/src/lib.rs
crates/data-plane-controller/src/stack.rs

Introduce workflow_dispatch actions for building and deploying these control-plane services to Cloud Run, using workload identity federation.
Include Dockerfile infrastructure and entrypoints for placing secrets into exepected locations.
Minor tweaks to data-plane-controller, adjusting defaults to work better with Cloud Run and also to support IPv4 addresses for Ansible hosts, which is required due to our dependency on Cloud Run (which only supports IPv4, paired with Cloud NAT).
Fixes #1767 
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) …

.github: deployment automation for data-plane-controller and agent-api

---

go.mod
go.sum

This brings in a new Etcd watch restart retry for gRPC status code `Unknown`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1784)

bump gazette pin to 298d8931dc89716d4481eaeccf00b20ddb6e8b69

---

site/docs/reference/Connectors/capture-connectors/facebook-marketing.md

Documentation updates for https://github.com/estuary/connectors/pull/2162.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1790)

docs: update source-facebook-marketing for multiple account ids

---

crates/agent/src/controllers/publication_status.rs

This updates the publication history in the controller status. We already reduced consecutive touch publications in the history. This is important because it prevents touch publications, which can sometimes number in the hundreds per day, from quickly pushing out other relevant information from the publication history.  But it turns out there's another case where repeated publications can clog up the history. This happens from repeated build failures, since we retry them indefinitely.
Previously, the rule was that we'd never combine non-touch publications. The goal was to make sure that we always show distinct history entries for publications that modify the model.  This tweaks that rule so that we will combine _unsuccessful_ non-touch publications. The result is that the publications …

agent: combine regular failed publications in status history

---

crates/schemalate/src/firebolt/firebolt_schema_builder.rs

Previously a fresh setup of S3 source -> Firebolt sink would lead to an error by default due to the internal `_meta/flow_truncated` field's type not being resolved. 
In this PR I'm trying to ensure we try to resolve the type via the projection whenever we're not able to do so with the explicit mapping from the Shape object.
Now setting up an S3 source and Firebolt sink should work by default.
N/A
Added relevant tests to illustrate and test the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1800)

fix(firebolt-schema-builder): better fallback to projection type resolution

---

site/docs/getting-started/comparisons.md
site/docs/guides/derivation_tutorial_sql.md
site/docs/guides/howto_join_two_collections_typescript.md
site/docs/guides/transform_data_using_typescript.md
site/docs/reference/Connectors/capture-connectors/stripe.md

The new version of the Stripe Capture connector is no longer third-party. This docs update removes information related to the deprecated version.
It also includes some other minor typo fixes, notably correcting `flowctl` spelling across various pages.
Provides updates for:
- [Stripe capture connector](https://docs.estuary.dev/reference/Connectors/capture-connectors/stripe/)
- [Getting started comparisons](https://docs.estuary.dev/getting-started/comparisons/)
- [Derivation tutorial SQL](https://docs.estuary.dev/guides/derivation_tutorial_sql/)
- [How to join two collections TypeScript](https://docs.estuary.dev/guides/howto_join_two_collections_typescript)
- [Transform data using TypeScript](https://docs.estuary.dev/guides/transform_data_us …

Docs: update Stripe connector, fix typos

---

go/protocols/ops/log_write_adapter.go
go/protocols/ops/log_write_adapter_test.go

Previously we could parse an apparently valid Log if a Write happened to occur on a JSON object boundary. Instead, ensure we explicitly discard all line content until a newline is reached.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1803)

go/protocols/ops: ensure we discard to-long ops logs through the newline

---

.github/workflows/deploy-agent-api.yaml
.github/workflows/deploy-data-plane-controller.yaml
crates/connector-init/src/capture.rs
crates/connector-init/src/derive.rs
crates/connector-init/src/materialize.rs
crates/data-plane-controller/src/controller.rs
go/network/auth.go
go/network/frontend.go

* deploy-agent-api, deploy-data-plane-controller, and derive-typescript are merged.
* `name:prefix` support has been live for some time now.
* Continue to clear the `internal` field in flow-connector-init. There's no use case for sending it into connectors.
* No current plan to implement a Destroy data-plane-controller message.
* Current UI is generating tokens via /authorize/user/task
(anything that might help someone …

close out a number of TODOs which have been resolved

---

crates/flowctl/src/raw/spec.rs

Adds support for the `flowctl raw spec` command to work with materializations too.
It changes the command from `flowctl raw spec --capture ...` to `flowctl raw spec --task ...`, which can work with both captures and materializations. This is is technically a breaking change, but since it is in `flowctl raw` I don't think it will have any practical impact. …

flowctl: add `raw spec` support for materializations

---

site/docs/reference/Connectors/capture-connectors/http-ingest.md

Adds docs to go along with estuary/connectors#2198
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1823)

docs: document path parameters in source-http-ingest

---

.github/workflows/dekaf.yaml

Dekaf depends on multiple protocol crates including `proto-flow` and `proto-gazette`, so it should be rebuilt when one of those changes. As a simplification, this modification will run the dekaf CI whenever any `proto-***` crate changes.
Future work may consider building dekaf like we do other rust binaries and packaging it similarly to reactor or agent. …

dekaf: rebuild on protocol changes

---

crates/flowctl/src/raw/mod.rs
crates/flowctl/src/raw/shards.rs
crates/proto-gazette/src/lib.rs

Resolves #1710
Adds `flowctl raw list-shards`, which fetches shard information for a given task. It's not yet clear whether this will have relevance to most users, since we plan to integrate shard status into the higher-level "status". But it's pretty inconvenient to use `flowctl-go` with legacy data planes, so this is just meant to give us a debugging tool that we can use in the meantime.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1831)

flowctl: add raw list-shards subcommand

---

crates/agent/src/controllers/collection.rs
crates/agent/src/controllers/periodic.rs
crates/agent/src/integration_tests/periodic_publications.rs

Updates the periodic publication controller so that it applies only to tasks. Previously, we deployed periodic publications and then reverted it because the number of collection publications was overwhelming. The original reason for publishing collections was only to ensure that built specs were all reasonably up to date, but we've decided that no longer seems worth the effort of doing so many publications. So this excludes collections from the periodic publications. The main objective of letting us expire old build databases from the cloud storage bucket is still met by periodically publishing captures, derivations, and materializations. I couldn't think of a reason to exclude catalog tests from periodic publication, so I just left it.
- - - …

agent: limit periodic publications to tasks only

---

.github/workflows/deploy-agent-api.yaml

This is required now, and was missing from the cloud-run deployment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1839)

agent: add CONTROL_PLANE_JWT_SECRET to agent-api deployment

---

site/docs/reference/Connectors/materialization-connectors/README.md
site/docs/reference/Connectors/materialization-connectors/apache-kafka.md

New docs for the new materialization connector to Apache Kafka.
See https://github.com/estuary/connectors/pull/2196
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1838)

docs: materialize-kafka

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/shopify.md

Our docs were missing Shopify documentation in the Capture Connectors Reference section. This update adds new docs based on the information in [the Shopify connector README](https://github.com/estuary/connectors/blob/main/source-shopify/source_shopify/README.md) and [schema configuration](https://github.com/estuary/connectors/blob/main/source-shopify/source_shopify/tap_shopify/tap.py), formatted to match our reference docs.
Will add a new page using the path: https://docs.estuary.dev/reference/Connectors/capture-connectors/shopify/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flo …

Docs: Add Shopify reference docs

---

site/docs/getting-started/installation.mdx

Added "Migrating your existing data to the new storage mapping" section.
Added instructions to backfill captures to migrate data to new storage mapping
**Documentation links affected:** 
https://docs.estuary.dev/getting-started/installation/
From slack chat with @jshearer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1859)

Adding instructions for migrating data after storage mapping changes

---

crates/runtime/src/container.rs

When set, use the desginated cgroup as the parent of started connector containers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1829)

runtime: add support for CONNECTOR_CGROUP_PARENT

---

site/docs/reference/Connectors/materialization-connectors/README.md
site/docs/reference/Connectors/materialization-connectors/apache-kafka.md

The list of materialization connectors on the overview page was out of date. This update refreshes the list, adding connectors like Google Sheets, Webhooks, Slack, etc. A few notable points have also been added to the Kafka reference.
Mainly updates the list at: https://docs.estuary.dev/reference/Connectors/materialization-connectors/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1869)

Docs: Refresh materialization references

---

crates/data-plane-controller/src/stack.rs

AWS assume-role configuration which is passed through to est-dry-dock for BYOC data-plane setups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1870)

data-plane-controller: extend DataPlane model with AWSAssumeRole

---

site/package-lock.json

Multiple months-old dependabot PRs bumping various dependencies were merged yesterday in quick succession. For whatever dependency-related reason, they caused the GH actions for doc deployments to start failing. Downgrading `dompurify` to 3.1.6 fixes the dependency issue.
- - - …

chore: downgrade dompurify to 3.1.6 due to compatibility issues from dependabot bumps

---

crates/assemble/src/lib.rs
crates/assemble/src/snapshots/assemble__test__inference.snap
crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap

Includes the "array" information in projection inference if it is available.
Should not be deployed until an updated version of dekaf is deployed - see https://github.com/estuary/flow/pull/1826.
Users will also need to update to the latest version of `flowctl` to work with specs that start to include this information.
- - - …

assemble: add array information to inference

---

go.mod
go.sum

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1879)

go.mod: bump gazette pin to 9f78463

---

crates/runtime/src/materialize/task.rs

Kafka has a default maximum message size of 1MiB.
This adds `materialize-kafka` to the list of connectors that use `ser_policy`, which should generally ensure that documents with individual extremely large string, array, or object fields don't exceed the message size limit for Kafka.
This simple heuristic may not always be 100% what users desire, but in general it seems better to have the connector at least sort-of-work rather than crash in a way that would require a more complicated fix (possibly a derivation) to best
support data exploration / PoC use cases.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9 …

runtime: add materialize-kafka to ser_policy

---

crates/data-plane-controller/src/stack.rs

- We now have an optional private ip6 that azure uses
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1893)

data-plane-controller: add optional private_ip6 to AnsibleHost

---

site/docs/concepts/flowctl.md
site/docs/guides/howto_join_two_collections_typescript.md

Developers were running into issues when following the TypeScript join tutorial, such as erroring out when flowctl couldn’t find a referenced orders schema or when flowctl couldn’t find the `customer_id` field in the collection schema.
This update should address those issues: a simple orders schema is now provided in-line rather than relying on a separate file. The missing `customer_id` field cropped up when the Google Sheet sources didn’t freeze their header row, leading Flow to assign generic field names. The example datasets were updated and a note added to indicate this requirement.
The update also attempts to head off other issues, simplifying or clarifying instructions throughout the guide.
Mainly affects: …

Docs: Revamp TypeScript Join Tutorial

---

site/docs/guides/dbt-integration.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1763)

docs: Add docs on dbt Cloud integration

---

crates/flowctl/src/catalog/publish.rs
crates/flowctl/src/collection/read/mod.rs
go.mod
go.sum
go/runtime/authorizer.go
go/runtime/capture.go
go/runtime/connector_proxy.go
go/runtime/control_plane.go
go/runtime/derive.go
go/runtime/flow_consumer.go
go/runtime/materialize.go
go/runtime/task.go
go/runtime/testing.go

Various minor improvements and refactor cleanups which were rebased / extracted from an abandoned work branch.
No functional changes aside from improved `flowctl` errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1873)

misc cleanups & bump gazette

---

crates/dekaf/src/read.rs
crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/preview/journal_reader.rs
crates/gazette/src/journal/append.rs
crates/gazette/src/journal/list.rs
crates/gazette/src/journal/mod.rs
crates/gazette/src/journal/read.rs
crates/gazette/src/journal/read_json_lines.rs
crates/gazette/src/lib.rs
crates/gazette/src/router.rs
crates/gazette/src/shard/mod.rs
crates/proto-gazette/build.rs
crates/proto-gazette/src/protocol.rs
crates/simd-doc/src/lib.rs

Previously, gazette routing was previously broken in some subtle ways:
* The process ID of a prior response was sent in the next request, causing "ProcessID doesn't match our own" errors in production.
* Improperly assuming that endpoints present in response headers are reach-able from the client. We need to condition that assumption on the `do_not_proxy` flag.
* `append` routine was not leveraging a prior response header to route its next attempt.
Sleep-based backoffs are also introduced to retry-able client routines, rather than making them a responsibility of the caller. This standardizes handling and prevents accidental thundering-herds of retries if a caller forgets to put in a backoff. Now callers don't need to worry about it, and must only decide whether to re-poll, drop to cancel, …

gazette: refactor retry, introduce backoffs, and fixing routing

---

site/docs/reference/Connectors/capture-connectors/MongoDB/amazon-documentdb.md
site/docs/reference/Connectors/capture-connectors/MongoDB/azure-cosmosdb.md
site/docs/reference/Connectors/capture-connectors/MongoDB/mongodb.md
site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/brevo.md
site/docs/reference/Connectors/capture-connectors/criteo.md

This update adds connector reference docs for Amazon DocumentDB, Azure Cosmos DB, Brevo, and Criteo. DocumentDB and Cosmos DB are variants of MongoDB, with some modifications (ex. DocumentDB does not support CDC).
Will add pages for:
* [Amazon DocumentDB](https://docs.estuary.dev/reference/Connectors/capture-connectors/MongoDB/amazon-documentdb/)
* [Azure Cosmos DB](https://docs.estuary.dev/reference/Connectors/capture-connectors/MongoDB/azure-cosmosdb/)
* [Brevo](https://docs.estuary.dev/reference/Connectors/capture-connectors/brevo/)
* [Criteo](https://docs.estuary.dev/reference/Connectors/capture-connectors/criteo/)
And adds minor modifications to the main connector reference page and existing MongoDB reference.
**Notes for …

Docs: Connector references for MongoDB variants, Brevo, Criteo

---

go.mod
go.sum

to include https://github.com/gazette/core/pull/419
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1924)

deps: bump gazette version to latest

---

crates/agent/src/controllers/collection.rs
crates/agent/src/integration_tests/schema_evolution.rs
crates/flow-web/src/lib.rs
crates/models/src/fixture.schema.json
crates/models/src/lib.rs
crates/models/src/schemas.rs
crates/models/src/snapshots/models__schemas__test__references_and_add_defs.snap
crates/models/src/snapshots/models__schemas__test__relaxation.snap

Define a new flow://relaxed-write-schema reference for use within read schemas, and a Schema::to_relaxed_schema() routine for relaxing a Schema.
Make Schema::add_defs() public and the primary interface for adding definitions. Begin to deprecate Schema::extend_read_bundle() and Schema::build_read_schema_bundle(). These will be replaced with direct usage of Schema::add_defs().
Update flow-web to use Schema::add_defs() and to support flow://relaxed-write-schema.
Update the agent to drop support for removing a historically inlined flow://write-schema instances, as we've already removed these.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1 …

models: refactor Schema APIs and introduce relaxation

---

crates/json/src/schema/types.rs
crates/validation/src/errors.rs
crates/validation/tests/snapshots/scenario_tests__keyed_location_wrong_type.snap

This reverts commit d7f30082aa31b720b63af1a09026c4982fd19d41.
We resolved this concern by instead establishing a policy with source-postgres and other connectors, they they use `type: string, format: number` for keyed locations which are numeric.
- - - …

Revert "validation: allow numbers to be keyed locations"

---

site/docs/concepts/advanced/evolutions.md
site/docs/concepts/advanced/shards.md
site/docs/concepts/derivations.md
site/docs/concepts/flowctl.md
site/docs/concepts/import.md
site/docs/concepts/materialization.md
site/docs/concepts/schemas.md
site/docs/concepts/web-app.md
site/docs/getting-started/deployment-options.md
site/docs/getting-started/quickstart/quickstart.md
site/docs/guides/edit-data-flows.md
site/docs/guides/flowctl/create-derivation.md
site/docs/guides/get-started-with-flowctl.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/PostgreSQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/Supabase.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/amazon-rds-postgres.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/google-cloud-sql-postgres.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/neon-postgres.md
site/docs/reference/Connectors/capture-connectors/confluence.md
site/docs/reference/Connectors/capture-connectors/gitlab.md
site/docs/reference/Connectors/capture-connectors/google-analytics.md
site/docs/reference/Connectors/capture-connectors/netsuite-suitetalk.md
site/docs/reference/authentication.md
site/docs/reference/organizing-catalogs.md
site/docs/reference/working-logs-stats.md

Docs builds exposed a number of lingering issues with anchor links. This update resolves remaining broken links, redirecting or removing links to account for renamed, moved, or deleted sections.
Closes #1935 
Various across docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1951)

Docs: Clean up broken anchor links

---

site/docs/reference/Connectors/capture-connectors/SQLServer/amazon-rds-sqlserver.md
site/docs/reference/Connectors/capture-connectors/SQLServer/google-cloud-sql-sqlserver.md
site/docs/reference/Connectors/capture-connectors/SQLServer/sqlserver.md

Now that github.com/estuary/connectors/pull/2385 is merged the default capture behavior for new users will be read-only, which requires the `VIEW DATABASE STATE` permission but doesn't use a watermarks table. This updates the docs to reflect that.
Part of https://github.com/estuary/connectors/issues/2339
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1953)

docs/SQLServer: Remove mention of watermarks

---

site/docs/reference/Connectors/capture-connectors/PostgreSQL/PostgreSQL.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/amazon-rds-postgres.md
site/docs/reference/Connectors/capture-connectors/PostgreSQL/google-cloud-sql-postgres.md

Adds a section to our docs discussing the "Read-Only Capture" advanced option, the conditions for using it, and how it can be applied to capturing from a read-only standby (and the extra setup that requires).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1970)

docs/source-postgres: Discuss read-only captures

---

crates/data-plane-controller/src/controller.rs
crates/data-plane-controller/src/stack.rs
supabase/migrations/20250224150353_data_plane_bastion.sql

- Skip DNS await if nothing changed. Tested this by running data-plane-controller locally
- add bastion info columns
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1964)

data-plane-controller: skip DNS await if nothing changed in pulumi up

---

crates/flowctl/src/collection/read/mod.rs

I needed this to debug Dekaf, and figured it would be a useful addition to our arsenal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1975)

flowctl: Add support for `flowctl collections read --offset`

---

crates/agent-sql/src/publications.rs

Rather than just exact matches. Verified (on a local stack) that his allows a tenant to be set up with sub-mappings (only), and that they're correctly used.
- - - …

agent-sql: storage mapping query should pull all mappings prefixed by tenant

---

go.mod
go.sum

Bump gazette to pick up a reduction in memory usage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1981)

go.mod: bump gazette pin to 7ffcbe3

---

site/docs/reference/Connectors/dekaf/README.md
site/docs/reference/Connectors/materialization-connectors/Dekaf/bytewax.md
site/docs/reference/Connectors/materialization-connectors/Dekaf/clickhouse.md
site/docs/reference/Connectors/materialization-connectors/Dekaf/imply-polaris.md
site/docs/reference/Connectors/materialization-connectors/Dekaf/materialize.md
site/docs/reference/Connectors/materialization-connectors/Dekaf/singlestore.md
site/docs/reference/Connectors/materialization-connectors/Dekaf/startree.md
site/docs/reference/Connectors/materialization-connectors/README.md

Adds docs for new Dekaf connector variants, updating the information from their original tutorials where necessary.
Mainly adds new pages under the [Dekaf materialization section](https://docs.estuary.dev/reference/Connectors/materialization-connectors/Dekaf/) and updates connector lists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1983)

Docs: Add Dekaf variants

---

crates/dekaf/src/session.rs

This was broken a while ago while introducing support for data-preview UIs. I'm pretty sure that this is the cause of the infrequent missing rows that we're seeing:
Read through offset X, successfully commit, then read X+1 and fail to commit, rejoin group and get back X as the last committed offset, try to read at offset X but there’s a pending read that doesn’t get correctly reset back to X, so you miss X+1 and continue on to X+2.
I'm working on splitting up this `read` function as it has a lot of nesting/complexity, but I just wanted to get this minimal fix out and building to confirm whether it fixes the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1982)

dekaf: Fix read offset jumps

---

site/docs/reference/Connectors/materialization-connectors/Snowflake.md

Updating Snowflake materialization docs to remove password authentication option
Snowflake is deprecating username/password in April, so I'm emailing customers about this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2014)

Updating Snowflake mat docs to remove password authentication option

---

crates/data-plane-controller/src/controller.rs
crates/data-plane-controller/src/stack.rs
supabase/migrations/20250319105337_data_plane_azure_client_id.sql

- This is necessary to construct the URL for authorizing the Azure Application access to customer storage in `est_dry_dock details` and potentially in the future in the UI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2017)

data-plane-controller: add azure_application_client_id to table

---

site/docs/getting-started/sso-setup.md

Adds a page in the Getting Started docs section on setting up the SSO login option. Includes the information developers will need to send to us, steps for adding new users, and Estuary configuration information.
Will add the page: [Log into Estuary Using SSO](https://docs.estuary.dev/getting-started/sso-setup/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2016)

Docs: Add instructions on setting up SSO

---

site/docs/reference/openmetrics-api.md

Adds a new docs page on the OpenMetrics API with details on how to use it by itself or in conjunction with Prometheus or Datadog. Provides a complete list of included metrics.
Will add a new page at [OpenMetrics API](https://docs.estuary.dev/reference/openmetrics-api/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2030)

Docs: OpenMetrics API usage

---

crates/agent/src/api/authorize_dekaf.rs
crates/agent/src/api/authorize_task.rs
crates/agent/src/api/authorize_user_collection.rs
crates/agent/src/api/authorize_user_task.rs
crates/agent/src/api/create_data_plane.rs
crates/agent/src/api/error.rs
crates/agent/src/api/mod.rs
crates/agent/src/api/snapshot.rs
crates/agent/src/api/update_l2_reporting.rs
crates/tables/src/behaviors.rs

Return considered status codes for most every error response.
Notably, return 404 if a valid task is attempting to authorize a collection which doesn't exist, as this lets the task recover if it's attempting to write ACK intents to a since-deleted collection.
Also refactor authorize_task() and authorize_dekaf() to validate the request token against its declared data-plane before doing anything else. This ensures the requestor is in possession of a correct data-plane HMAC key before we could possibly leak any information about whether the subject task exists or not.
Tested all APIs **except for authorize_dekaf** on a local stack. …

agent: update all APIs to use ApiErrorExt

---

crates/flowctl/src/catalog/delete.rs
crates/flowctl/src/catalog/mod.rs
crates/flowctl/src/catalog/pull_specs.rs

- Going to use this in est-dry-dock to clean up all tasks and collections of a data-plane, also generally useful
Tested manually using:
```
flowctl catalog pull-specs --data-plane-name ops/dp/private/estuarysupport/az-eastus-c1
flowctl catalog pull-specs --data-plane-name ops/dp/private/estuarysupport/az-eastus-c1 --prefix nonexistentTenant/
flowctl catalog list --data-plane-name ops/dp/private/estuary_support/aws-us-west-2-c1
flowctl catalog delete --data-plane-name ops/dp/private/estuarysupport/az-eastus-c1 --prefix estuary/az-
```
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) …

flowctl: add --data-plane-name filter to catalog list

---

crates/runtime/src/materialize/task.rs

Azure Fabric Warehouse has a 1MB size limit on VARCHAR(MAX) columns, so we need to try to stay below that size for any individual string field, and probably more importantly the entire document, since the document is stored in such a column.
- - - …

runtime: add materialize-azure-fabric-warehouse to ser_policy

---

crates/agent/src/controllers/capture.rs

Fixes an issue that causes the agent to rapidly re-run controllers in certain scenarios when a spec is disabled after previously encountering repeated auto-discover failures. This removes the `next_at` whenever the spec is disabled to ensure that we won't keep running the controller in a tight loop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2072)

agent: fix skipping auto-discovers for disabled tasks

---

crates/agent/src/controllers/capture.rs
crates/agent/src/controllers/collection.rs
crates/agent/src/controllers/executor.rs
crates/agent/src/controllers/materialization.rs
crates/agent/src/controllers/mod.rs
crates/agent/src/controllers/periodic.rs
crates/agent/src/integration_tests/dependencies_and_activations.rs

Implements a number of fixes and improvements to controller error handling.
This addresses an acute issue, where it was possible for a controller to fail in a tight loop. That was happening in cases where auto-discovers or periodic publications were failing, and there was also a failure to publish in response to a change in dependencies. In that case, the next run was computed based on the time of the next desired auto-discover or periodic publication, which was in the past due to the failures.
It also addresses an issue with captures, where a dependency update publication would fail, preventing auto-discovers from being attempted.  In some cases, the dependency update publication was failing due to tables being dropped from a source database, and an auto-discover would have removed the …

agent: more robust controller error handling

---

site/docs/reference/Connectors/capture-connectors/google-analytics-data-api-native.md

Documentation updates for https://github.com/estuary/connectors/pull/2685.
Users have also run into issues with editing custom reports, not re-discovering bindings so those changes are reflected in the spec & schema, then run into schema issues. I added a tip to try & help users troubleshoot this when editing custom reports.
- - - …

docs: add `metricAggregations` support for `source-google-analytics-data-api-native`

---

Cargo.lock
Tiltfile
crates/activate/src/lib.rs
crates/activate/src/snapshots/activate__test__create.snap
crates/activate/src/snapshots/activate__test__create_and_delete.snap
crates/activate/src/snapshots/activate__test__shard_splits.snap
crates/activate/src/snapshots/activate__test__update-disabled.snap
crates/activate/src/snapshots/activate__test__update.snap
crates/gazette/src/shard/mod.rs
crates/labels/src/lib.rs
crates/migrate/Cargo.toml
crates/migrate/src/lib.rs
crates/migrate/src/main.rs
crates/proto-gazette/src/consumer.rs
crates/proto-gazette/src/consumer.serde.rs
go.mod
go.sum
go/labels/labels.go
go/runtime/authorizer.go

* [required] Handle (in the runtime) a task which is migrated and awakes in a new data-plane, and must discard its stats ACK intent.
* [nice to have] support a new `estuary.dev/cordon` data-plane label, which is attached to ShardSpecs and JournalSpecs to disable them / mark them read-only, and preserved in future activations
* [nice to have] refactor `activate` and add new checks against races and expected ordering
* [nice to have] shard Apply RPC supports setting `primary_hints`, and related support in `gazette` & `activate`
* [nice to have] `migrate` crate implementing a prototype CLI for task and collection migration
Future PRs will include:
* a prototype migration CLI for task migration
* authorization API support for cordoning of tasks to support hot migration …

basic control-plane and runtime support for task migration

---

crates/data-plane-controller/src/stack.rs

This lets the data plane controller parse deployments of the `Dekaf` role, and is needed to test the corresponding dry-dock changes to deploy Dekaf in new-style data-planes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2094)

data-plane-controller: Add `Dekaf` role

---

supabase/functions/azure-dpc-oauth/index.ts

- For adding data-plane-controller app to Azure tenants to enable BYOC, users need to go through an OAuth flow
- We currently redirect to estuary.dev, which doesn't tell customers if the OAuth process was successful or not
- The simplest implementation to show error if there is one, or tell the customer if it was successful, to avoid confusions.
- - - …

functions: azure-dpc-oauth for redirect_url of Azure BYOC OAuth

---

crates/agent-sql/src/data_plane.rs
crates/agent/src/controlplane.rs

Fixes #2111 
Previously, ops collections were required to exist whenever activating or deleting specs in the data plane.  This made it so that the ops collections themselves could never be deleted successfully, which prevents us from gracefully tearing down a data plane.  Now the ops collections are only required to exist when activating, and are allowed to be missing during deletion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2117)

agent: allow ops collections to be missing when deleting

---

crates/agent/src/api/authorize_dekaf.rs
crates/agent/src/api/authorize_task.rs
crates/agent/src/api/authorize_user_collection.rs
crates/agent/src/api/authorize_user_task.rs
crates/agent/src/api/error.rs
crates/agent/src/api/mod.rs
crates/agent/src/api/public/mod.rs
crates/agent/src/api/public/open_metrics.rs
crates/agent/src/api/public/status.rs
crates/agent/src/api/snapshot.rs
crates/migrate/src/lib.rs
crates/models/src/authorizations.rs
supabase/migrations/20250418224209_cordon.sql

This PR updates authorization snapshot mechanisms to introduce a concept of scheduled "cordons", where granted authorizations will bound their expiration time to a future scheduled migration timestamp. Upon reaching this timestamp, authorization APIs ask clients to retry periodically until the cordon condition is resolved.
This allows, for example, a running materialization -- which is _not_ migrated -- to gracefully handle a collection which _is_ migrated. Its reads of the collection proceed normally until the cordon timestamp, at which point it spins attempting to fetch a new authorization. Meanwhile, a migration of the collection is performed, and the cordon condition removed. The materialization authorization request can then proceed, and receives an authorization …

support "hot" migration through authorization cordons

---

crates/validation/src/capture.rs
crates/validation/src/derivation.rs
crates/validation/src/errors.rs
crates/validation/src/materialization.rs
crates/validation/tests/common.rs
crates/validation/tests/snapshots/transition_tests__updates_with_clobbered_backfill_counter.snap
crates/validation/tests/transition_tests.rs

Compare the draft backfill with the last active or inactive spec under the same validated resource path, and ensure that backfills remain monotonic.
This avoids a class of confusing errors where users (typically using flowctl) accidentally clobber the backfill counter of a running task binding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

validation: add a new check that backfill counters are monotonic

---

supabase/migrations/20250502201326_fix-estuary-support.sql

Updates the new tenant provisioning to only add newly created tenants to the `estuary_support/` role.  Previously it was adding all tenants to the role whenever any tenant was provisioned, which would re-add tenants that we had removed. Now they stay removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2127)

control plane: only add new tenants to estuary_support/ role

---

crates/models/src/journals.rs
crates/models/src/snapshots/models__journals__test__storage-json-schema.snap

We're going to incrementally transition the storage mapping concept to also hold details of preferred (eventually: perhaps required) data-plane for new tasks or collections under a prefix.
As a first step, accept a `data_plane` field but don't do anything with it. This will allow us to populate this field and use it within the UI to default the data-plane used in new task creation.
(anything that might help someone …

models: accept a `data_plane` field on a StorageDef

---

crates/activate/src/lib.rs
crates/activate/src/snapshots/activate__test__create-no-splits.snap

This was missed in the previous refactor of `activate`. Dekaf tasks are activated with empty shard splits and an enabled task. We still need to create ops journals for it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2135)

activate: create ops journals when the task is enabled, even without splits

---

crates/agent/src/api/authorize_user_collection.rs
crates/agent/src/api/authorize_user_prefix.rs
crates/agent/src/api/authorize_user_task.rs
crates/agent/src/api/mod.rs
crates/agent/src/api/snapshot.rs
crates/flow-client/src/client.rs
crates/flow-client/src/lib.rs
crates/flowctl/src/raw/mod.rs
crates/models/src/authorizations.rs

User authorization APIs can now escalate the capability of a signed token if the user has sufficient privilege. This can be used for administrative actions like journal splitting.
Also add a new prefix authorization API which signs an authorization token valid for a requested and authorized prefix and capability, directed at a specific data-plane.
Add a new, advanced flowctl subcommand for authorizing and printing environment variables for direct gazette access of an authorized prefix.
Use `flowctl` to obtain a temporary authorization to an entire (authorized) prefix:
```
johnny@johnny-desktop:~/estuary/flow$ flowctl --profile local raw gazctl-env --data-plane ops/dp/public/local-cluster --prefix ops.us-central1.v1/ 
2025-05-08T16:38:44.477413Z  WARN …
```

agent: user auth APIs accept and verify request capability, and add user prefix authorization API

---

crates/agent/src/api/authorize_task.rs
crates/doc/src/reduce/strategy.rs
crates/doc/src/shape/inference.rs
crates/doc/src/shape/inspections.rs
crates/doc/src/shape/schema.rs
crates/gazette/src/journal/read.rs
crates/gazette/src/lib.rs
crates/proto-gazette/src/lib.rs
crates/runtime/src/capture/protocol.rs

* Omit a `reduce` annotation altogether when the inferred reduction strategy is `Reduction::Multiple`
* "fix" local fragment file:// schemes by not attempting to fetch them
* Explicitly error if the connector's SourcedSchema is not closed.
* Catch a spot where we failed to thread-through `x-generation-id`.
- - - …

more sourced schema tweaks

---

crates/agent/src/proxy_connectors.rs
crates/tables/src/behaviors.rs
crates/validation/src/capture.rs
crates/validation/src/derivation.rs
crates/validation/src/lib.rs
crates/validation/src/materialization.rs

We get a number of unclean connector proxy shutdown warnings from
reactors, and this is why. We want to ensure we properly close and read
EOF from RPCs. This also ensures we don't miss any final log statements
coming from the connector.
- - - …

ensure we're driving connector RPCs to EOF

---

crates/agent/src/api/snapshot.rs

Instead, just drop the Tx channel to signal the reciever. Tested on a local stack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2140)

agent: snapshots shouldn't assume `refresh_tx` hasn't been dropped

---

Tiltfile
crates/migrate/src/lib.rs
go/labels/labels.go
go/network/frontend.go
go/network/proxy_client.go
go/network/sni.go
go/network/sni_test.go

Refine the semantics of the `estuary.dev/cordon` label to reflect the destination FQDN of a migrated journal or task.
Next, update connector networking to be aware of cordons. If there's a non-empty cordon value, presume it's a destination FQDN and dial a proxied TLS connection to the destination, passing through the parsed SNI and connector port protocol.
Refactor protocol handling to avoid overwritting the resolvedSNI.portProtocol. Instead, we can examine the negotiated protocol of the frontend connection for metrics.
Also improve error checks and test coverage of SNI parsing.
Tested on a local stack with migrations of:
* source-hello-world
* source-http-ingest
* materialize-sqlite
* Migrate a connector which uses the connector networking feature from one data-plane …

go/network: forward migrated connector network requests

---

crates/validation/src/capture.rs
crates/validation/src/derivation.rs
crates/validation/src/materialization.rs
crates/validation/tests/snapshots/transition_tests__deletion_of_used_collection_when_disabled.snap
crates/validation/tests/transition_tests.rs

In the typical UX, if one disables a task and then deletes a collection which it references, than the task's binding will be disabled.
Or, if one attempts to publish a new binding of a disabled task for which the collection doesn't exist, then they will get an error.
- - - …

validation: enforce collection referential integrity, even when a task is disabled

---

crates/data-plane-controller/src/lib.rs

`logs_sink` will not exit until all references to `logs_tx` are dropped, and we're still holding one at the time we're awaiting its exit. D'oh.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2150)

data-plane-controller: explicitly drop `logs_tx`

---

crates/data-plane-controller/src/stack.rs
crates/data-plane-controller/src/state_fixture.json
crates/data-plane-controller/tests/snapshots/test_initial_convergence_and_release__test.snap
crates/data-plane-controller/tests/snapshots/test_preview__test.snap
crates/data-plane-controller/tests/snapshots/test_private_links__private_links.snap
crates/data-plane-controller/tests/util.rs

- Ran tests without adding `connector_limits` to state fixture, tests pass
- Ran tests after adding `connector_limits`, tests pass and can see `connector_limits` as part of the configuration now
Sister pull-request: https://github.com/estuary/est-dry-dock/pull/114
- - - …

dpc: connector limits configuration

---

site/docs/reference/Connectors/capture-connectors/README.md
site/docs/reference/Connectors/capture-connectors/jira-legacy.md
site/docs/reference/Connectors/capture-connectors/jira-native.md

The existing `source-jira-native` was renamed to `source-jira-legacy` in https://github.com/estuary/connectors/pull/2824. That connector's documentation has been updated to reflect the `-legacy` suffix.
An actually native `source-jira-native` connector is introduced in https://github.com/estuary/connectors/pull/2845. Initial documentation for that connector has been created.
(anything that might help …

docs: update Jira capture documentation

---

crates/agent/src/controlplane.rs
crates/agent/src/discovers.rs
crates/agent/src/discovers/executor.rs
crates/agent/src/integration_tests/harness.rs

Updates discovers to skip authorization checks for discovers that are performed by controllers.  Previously, we'd be relying on the `estuary_support/` role to allow auto-discovers to properly resolve live specs, which caused auto-discovers to fail for tenants that weren't covered by that role grant.
Also updates the integration test setup to remove the `estuary_support/` role. This was sufficent to reproduce the issue wth auto-discovers, and seemed like a good idea generally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2180)

agent: skip authorization checks for controller-initiated discovers

---

site/docs/getting-started/installation.mdx

Adds EU instructions for Azure storage mappings and makes some minor clarifications to the docs.
The [Configure Cloud Storage](https://docs.estuary.dev/getting-started/installation/) page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2181)

Docs: Add EU Azure storage mapping instructions

---

Cargo.lock
crates/flow-web/Cargo.toml

This just updates the flow-web version number so that we can release the latest version of the package
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2185)

flow-web: bump version to 0.5.13

---

site/docs/reference/Connectors/capture-connectors/snowflake.md

Adds some text to the Snowflake CDC docs describing the setup for Secure Data Sharing. Basically just a light rewording of what I already wrote on https://github.com/estuary/connectors/issues/2638
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2204)

docs/source-snowflake: Decribe datashare setup

---

crates/migrate/src/lib.rs

The cordon label must include the TCP port to which we'll forward. If not present (always true in production) then assume HTTPS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2215)

migrate: add /443 port default for cordon label

---

Cargo.lock
crates/activate/src/lib.rs
crates/agent/src/api/authorize_user_collection.rs
crates/agent/src/api/authorize_user_prefix.rs
crates/agent/src/api/authorize_user_task.rs
crates/agent/src/api/snapshot.rs
crates/dekaf/src/topology.rs
crates/flow-client/src/client.rs
crates/flowctl/Cargo.toml
crates/flowctl/src/collection/mod.rs
crates/flowctl/src/collection/read/mod.rs
crates/flowctl/src/generate/mod.rs
crates/flowctl/src/preview/journal_reader.rs
crates/flowctl/src/raw/mod.rs

- `flowctl raw gazctl-env` now offers a --name alternative, which looks up the data-plane
- add `flowctl collections split-journals` for splitting the journals of a collection
- lock down user authorization admin requests to estuary_support/ staff
We can make split-journals self-service if we add a a control plane API which ensures (for example) users aren't creating 100k journals.
This requires corresponding gazette PR: https://github.com/gazette/core/pull/434
* Use new flowctl commands
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief …

flowctl support improvements

---

crates/data-plane-controller/src/controller.rs

- I missed this part during testing as I added it last, the gcpkms:// passed to data-plane-controller's prefix should not be included to work with sops
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2225)

dpc: strip gcpkms:// from encryption

---

crates/agent-sql/src/data_plane.rs
crates/agent/src/api/snapshot.rs
crates/agent/src/main.rs

- I had updated `fetch_data_planes` so that if no list of data-plane IDs was provided, it would return all data-planes, but I had not realised that there were uses of this function in some parts of the code, notably in `discovers/executor` which did not pass a list of data-plane IDs, but did pass a default data plane name, and they expected a single data-plane to be returned in that case. The change was breaking these scenarios. In my local testings I had only tested with a single test data-plane so this was not caught. I reverted `fetch_data_planes` to its original and instead added a new function for fetching all data planes
- While looking for this bug, I noticed the cache for `decrypted_hmac_keys` would be populated by non-encrypted values as well, so I update the …

agent: HMAC encryption fix

---

site/docs/guides/connect-network.md

minor issue I noticed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2230)

docs: fix SSH command extra backslash

---

crates/agent/src/api/create_data_plane.rs
crates/validation/src/field_selection.fixture.yaml
crates/validation/src/field_selection.rs
crates/validation/src/materialization.rs
crates/validation/tests/common.rs
crates/validation/tests/snapshots/transition_tests__group_by_migration.snap
crates/validation/tests/transition_tests.rs

* When `recommended: true`, don't select object leaves to maintain legacy selection behavior in this case
* Add temporary migration handling to populate `groupBy` clause when the current key is non-canonical.
* Streamline encrypted HMAC key handling for "manual" (local) data-planes.
Tested on a local stack by creating two collections, one with a projection of the collection key, the other without.
I confirmed that we added a `groupBy` to only the intended collection, and that thereafter the field selection logging output no differences.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) …

field selection tweaks & fix local stacks

---

crates/models/src/lib.rs
crates/sources/tests/snapshots/schema_generation__catalog_schema_snapshot.snap
flow.schema.json

Our current serialization behavior is such that if a user provides a spec with an interval of `24h`, we will serialize it as `1d`. This updates the schema to permit units in days, because currently this causes a validation error in the UI. I'm kicking the can on whether to add months.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2254)

models: update interval schema to allow units in days

---

crates/gazette/src/journal/append.rs
crates/gazette/src/lib.rs
crates/gazette/src/shard/mod.rs
crates/migrate/src/lib.rs

`migrate` was using FuturesUnordered, which meant that all gRPC requests were essentially dispatched simultaneously. We observed repeating transport errors (reset TCP connections), and the suspicion is that we were triggering load shedding of the Go gRPC internals when migrating larger tenants with lots of requests.
Improve various `migrate` error contexts.
Also refine a few Gazette client APIs.
Tested on a local stack with an absurdly large fixture of ~50 captures and ~2k collections, which brought my dev machine to its knees. Even with that I wasn't able to replicate the TCP resets observed in production, but I did find some other edges to smooth. …

migrate: improve error instrumentation and reduce concurrency

---

crates/agent/src/controllers/activation.rs
crates/agent/src/controllers/executor.rs

- Removes a spammy warning that had gotten left in by mistake
- Log final deletions at info level so they're visible in grafana
- log task_id to aid in debugging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2273)

agent: tweaks some logging for controllers

---

supabase/migrations/20250711115313_catalog-stats-indexes.sql

Removes some unneeded indexes, and creates a new index on `ts` in order to facilitate more efficient deletions of old hourly stats. This is intended to resolve statement timeouts in the `delete_old_hourly_stats`, and cleanup some accumulated junk.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2277)

control-plane: update catalog_stats* table indexes

---

Tiltfile
crates/agent/src/main.rs

Changes agent to log in JSON format by default, so that we can more easily use logs in Grafana.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2284)

agent: log in json format by default

---

site/docs/concepts/materialization.md

Includes target resource naming convention options in docs, along with minor tweaks on language around default schema for clarity.
The resource naming section and mirror schemas option can be updated when `source.targetNaming` receives further updates.
Updates the [Materialization concepts page](https://docs.estuary.dev/concepts/materialization/)
Trying to catch up on some docs requests; thanks for the review!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2286)

Docs: Add target resource naming options

---

site/docs/reference/Connectors/capture-connectors/snowflake.md
site/docs/reference/Connectors/materialization-connectors/Snowflake.md

Following estuary/connectors#3066, Snowpipe Streaming is now the default option for delta updates bindings. This PR modifies our Snowflake reference docs to reflect that.
[Snowflake materialization connector reference](https://docs.estuary.dev/reference/Connectors/materialization-connectors/Snowflake/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2291)

Docs: Update Snowpipe information in Snowflake reference

---

crates/flow-client/src/lib.rs

I fat-fingered this URL when I made it a lazy static, so this just removes the extra `s`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2297)

flowctl: fix default config-encryption url

---

site/docs/reference/backfilling-data.md

Adds Dekaf as an incremental backfill use case in our backfilling docs as updating Dekaf schemas requires additional work in the connected service.
Updates [Backfilling Data](https://docs.estuary.dev/reference/backfilling-data/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2298)

Docs: Note Dekaf incremental backfill use case

---

site/docs/concepts/flowctl.md
site/docs/guides/flowctl/ci-cd.md

Following #2294, updates docs around `flowctl` and protecting secrets. Adds information on automatic encryption with `flowctl` and clarifies manual `sops` process.
Updates:
* [`flowctl` concepts page](https://docs.estuary.dev/concepts/flowctl/)
* [CI/CD guide](https://docs.estuary.dev/guides/flowctl/ci-cd/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2301)

Docs: Include `flowctl` automatic encryption capabilities

---

crates/flowctl/src/catalog/publish.rs
crates/flowctl/src/catalog/test.rs
crates/flowctl/src/draft/mod.rs
site/docs/guides/flowctl/ci-cd.md

Updates the default values for the `--default-data-plane` argument to be the new public data plane, since Cronut is being decomissioned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2303)

flowctl: change default data plane to c2

---

crates/dekaf/src/registry.rs

It looks like I broke this in https://github.com/estuary/flow/pull/2299. `Schema::canonical_form()` totally returns `String`, so we need to match that in order to be compliant with the confluent schema registry. 
Reported by @mdobson [here](https://github.com/mdobson/flow/pull/1), thank you!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2334)

dekaf: Fix serialization of `get_subject_latest()` for Materialize

---

Cargo.lock
crates/flow-web/Cargo.toml
crates/flow-web/FIELD_SELECTION.md
crates/flow-web/tests/web.rs
crates/validation/src/field_selection.rs

Use the serde "internally tagged enum" pattern for representing Select and Reject, so that the UI has a consistent `type` field for extraction of enum variant.
Update flow-web tests and publish a new version 0.5.18
- - - …

flow-web: use `type` tag for Select / Reject serialization

---

supabase/migrations/20250825162032_alert-subs-allow-list.sql
supabase/tests/alerts.test.sql

Resolves #2346
The `alert_subscriptions` table had an `exclude_alert_types` column, added as part of #2188, to allow users to opt out of notifications for specific alert types. This changes that to `include_alert_types`, inverting the filtering. This allows us to more easily beta test new alert types by enabling notifications for select users/tenants only.
Note that the UI for this is still TBD, so I don't think there's any impact there yet, and also no docs impact yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2361)

control-plane: Change alert_subscriptions to use an allow-list

---

crates/agent/src/discovers/specs.rs
crates/agent/src/integration_tests/auto_discovers.rs
crates/agent/src/integration_tests/snapshots/agent__integration_tests__user_discovers__initial-discover.snap
crates/agent/src/integration_tests/snapshots/agent__integration_tests__user_discovers__initial-publication.snap
crates/agent/src/integration_tests/snapshots/agent__integration_tests__user_discovers__second-discover.snap
crates/models/src/schemas.rs

Adopt a pattern similar to flow://inferred-schema where the connector-supplied schema is an overwritten sub-definition of the collection's write schema.
This allows users to "take control" of their write schema by adding additional top-level keywords or, if they choose, electing to not use `$ref: flow://connector-schema` at all.
In the garden path case, auto-discovery will continue to periodically update the sub-schema, and user keywords are preserved and applied atop the most recent update.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as …

agent: place discovered schemas into flow://connector-schema sub-schema

---

site/docs/getting-started/tutorials/continuous-materialized-view.md
site/docs/getting-started/tutorials/samples/continuous-materialized-view/flow.yaml
site/docs/guides/flatten-array.md
site/docs/guides/flowctl/create-derivation.md

GitPod has been sunset and our integration for derivations no longer works. This PR updates docs to remove outdated information, focusing on a CLI-first approach to working with derivations.
Affected docs include:
- [Create a derivation with flowctl](https://docs.estuary.dev/guides/flowctl/create-derivation/)
- [How to flatten an array using TypeScript](https://docs.estuary.dev/guides/flatten-array/)
- [Create a real-time materialized view in PostgreSQL](https://docs.estuary.dev/getting-started/tutorials/continuous-materialized-view/)

Docs: Remove GitPod from flowctl instructions and tutorials

---

crates/parser/src/config/character_separated.rs
crates/parser/src/config/snapshots/parser__config__test__config_schema_is_generated.snap

Add `~` as a supported delimiter in the parser.

parser: add tilde (~) delimiter support

---

crates/agent/src/integration_tests/quotas.rs
crates/control-plane-api/src/publications/quotas.rs

It's not clear from the error message what a user's next steps should be when they're trying to exceed their task quota. Directing them to reach out to support to increase their task quota makes it clear what users should do when they hit this error.

agent: improve error message when a tenant's task quota would be exceeded

---

crates/validation/src/capture.rs
crates/validation/src/derivation.rs
crates/validation/src/errors.rs
crates/validation/src/lib.rs
crates/validation/src/materialization.rs
crates/validation/tests/scenario_tests.rs
crates/validation/tests/snapshots/scenario_tests__capture_too_many_bindings.snap
crates/validation/tests/snapshots/scenario_tests__derivation_too_many_transforms.snap
crates/validation/tests/snapshots/scenario_tests__materialization_too_many_bindings.snap

The combiner uses u16 for binding indices, providing a hard upper bound of 65,535 bindings. This change adds validation to enforce a practical limit of 10,000 bindings per task to prevent performance issues and ensure reasonable catalog sizes.
Adds MAX_BINDINGS constant and TooManyBindings error variant, with checks in capture, derivation, and materialization validation paths. Tests verify that exceeding the limit produces appropriate errors. …

validation: limit captures, derivations, and materializations to 10k bindings

---

crates/data-plane-controller/src/stack.rs

data-plane-controller: dns_name should be optional for Azure privatelink

---

crates/validation/src/field_selection.rs
crates/validation/src/snapshots/validation__field_selection__tests__incompatible_and_ambiguous.snap

Reject::ConnectorIncompatible must be lower-rank than Reject::DuplicateFold.
If two fields are ambiguous, we want to reject the second field due to the DuplicateFold instead of ConnectorIncompatible. The former will cause the field to simply not be included, while the latter will trigger the onIncompatibleSchemaChange action.

validation: adjust Reject ordering

---

crates/control-plane-api/src/server/public/mod.rs

updates the metrics route to be compatible with axum 0.8, which had a breaking change to the route syntax.

control-plane-api: fix metrics route for axum 0.8
