estuary/flow

src/doc/diff.rs, src/materialization/mod.rs, src/runtime/specs.rs
Also includes an unrelated fix for catalog tests to compare floats using an epsilon value.
=> standardize shard names

crates/doc/src/inference.rs
Added a special case for computing the union of two shapes when one of
them is not possible in a valid document (i.e. when one shape represents
the schema `false`). Since we can prove that no valid document can take
such a shape, we short circuit and simply return the shape that can
exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/74)
=> Fix inferrence unions with impossible shapes

crates/doc/src/reduce/strategy.rs
When null, these reduction annotations behave as no-ops.
This behavior allows the current register state to condition whether
an `merge` or `append` reduction should be done, which otherwise isn't
possible as the "update" lambda doesn't have access to the register.
It's more efficient than reducing, and then pruning (using prune
annotations that don't exist yet), because we can track and optimize for
the fact that the register value hasn't change from its loaded RocksDB
state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/77)
=> doc: relax `merge` and `append` rules, allowing for LHS to be null

go/materialize/lifecycle/protocol.go
Adds functions to lifecycle.Load/StoreIterator types to allow for
checking whether they contain at least one item to process. This is
intended to provide a way for Driver implementations to avoid doing
work for Loads or Stores when a transaction does not contain any.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/113)
=> Add Poll_Request functions to Load/Store Iterators

.gitignore, crates/sources/src/loader.rs, crates/sources/src/scenarios/snapshots/sources__scenarios__endpoints_captures_materializations.snap, crates/sources/src/scenarios/test_endpoints_captures_materializations.yaml, crates/sources/src/specs.rs, crates/validation/src/materialization.rs, crates/validation/tests/snapshots/scenario_tests__golden_all_visits.snap, examples/flow.yaml, examples/soak-tests/set-ops/flow.yaml, go.mod, go.sum, go/flow/.snapshots/TestLoadJournalRules, go/flow/js_worker.go, go/flowctl-go/cmd-build.go, go/flowctl-go/cmd-develop.go, go/flowctl-go/cmd-test.go, go/materialize/driver/sql2/driver.go, go/materialize/driver/sqlite/sqlite.go, go/materialize/driver/sqlite/sqlite_test.go, go/protocols/flow/document_extensions.go, go/runtime/flow_consumer.go, go/shuffle/read.go, go/shuffle/read_test.go, go/shuffle/reader.go, go/shuffle/ring.go, go/testing/cluster.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/111)
=> sqlite ergonomics, concurrency, and materialization soak test

go.mod, go.sum, go/flowctl/cmd-build.go, go/flowctl/cmd-develop.go, go/flowctl/cmd-json-schema.go, go/flowctl/cmd-test.go, go/flowctl/logging.go, go/flowctl/main.go, go/testing/driver.go
Couple of small commits to make the CLI output easier on the eyes, especially for the `test` subcommand. There's definitely more work that _could_ be done here. It would be nice to have some scenario tests for build and test failures, for example. But I think this is probably a good place to leave it for now. Screenshots of example outputs below, in case you have any feedback on those.
I also added a `Build Success` message at the end of `flowctl build` just to give it something a little more clear than whatever npm spits out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/122)
=> Flowctl logs

examples/temp-sensors/flow.ts, examples/temp-sensors/flow.yaml, examples/temp-sensors/schemas.yaml
First, we'll show off reduction annotations and remote URL's, then registers and testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/137)
=> Updating the sensors example to break it into two tutorials. 

crates/doc/src/inference.rs, crates/json/src/schema/build.rs, crates/json/src/schema/mod.rs, crates/json/src/validator.rs, go/flowctl/cmd-discover.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/165)
=> small fixes from testing `flowctl discover` workflow with nested parser configs

.devcontainer/release.Dockerfile, go/flow/catalog.go, go/flowctl/cmd-apply.go, go/flowctl/cmd-develop.go, go/flowctl/cmd-test.go, go/ingest/ingest.go, go/labels/labels.go, go/materialize/driver/postgres/driver.go, go/runtime/flow_consumer.go, go/runtime/task_term.go, go/testing/driver.go
Just a draft for now. Still waiting to see if this actually works OK in practice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/164)
=> Install docker cli in flow image

go/capture/driver/airbyte/connector.go, go/capture/driver/airbyte/driver.go, go/flowctl/cmd-develop.go, go/flowctl/cmd-test.go, go/materialize/driver/postgres/driver.go, go/materialize/driver/snowflake/snowflake.go, go/runtime/capture.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/166)
=> various fixes from E2E testing of captures => materializations

.github/workflows/main.yml, crates/build/src/nodejs/snapshots/build__nodejs__scenario_test__scenario.snap, flow_generated/flow/collections.d.ts, flow_generated/flow/routes.ts, flow_generated/flow/transforms.d.ts, go/capture/driver/airbyte/connector.go, go/capture/driver/airbyte/driver.go, go/flow/catalog.go, go/flowctl/cmd-apply.go, go/flowctl/cmd-develop.go, go/flowctl/cmd-test.go, go/ingest/apis_test.go, go/ingest/ingest_test.go, go/materialize/driver/postgres/driver.go, go/protocols/capture/capture.pb.go, go/protocols/flow/flow.pb.go, go/protocols/materialize/materialize.pb.go, go/shuffle/api_test.go, go/shuffle/reader_test.go, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/167)
=> more minor fixups

.devcontainer/release.Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/169)
=> add jq to flow docker image

examples/local-sqlite.flow.yaml, go.mod, go.sum, go/bindings/build.go, go/bindings/build_test.go, go/bindings/combine_test.go, go/bindings/derive_test.go, go/bindings/extract_test.go, go/flow/stat_api.go, go/flowctl/cmd-apply.go, go/flowctl/cmd-develop.go, go/flowctl/cmd-discover.go, go/flowctl/cmd-test.go, go/ingest/apis_test.go, go/ingest/ingest_test.go, go/materialize/driver/postgres/sqlgen_test.go, go/materialize/driver/snowflake/snowflake_test.go, go/materialize/driver/sql2/validate_test.go, go/materialize/driver/sqlite/sqlite_test.go, go/shuffle/api_test.go, go/shuffle/reader_test.go, go/testing/cluster.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/171)
=> fixes to shard stat data-race and flowctl develop hang

crates/derive/src/combine_api.rs, crates/derive/src/extract_api.rs, go/ingest/http_api_test.go, go/runtime/capture.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/177)
=> improve errors produced on parsing invalid JSON

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yaml, .devcontainer/docker-debian.sh, .devcontainer/github-ubuntu-2004.Dockerfile, .vscode/settings.json, Makefile
Update to a Ubuntu 20.04 devcontainer base, with host Docker support which (🤞 ) works on Mac Docker as well as Codespaces.
I've confirmed it works fine on Codespaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/188)
=> devcontainer: update for 20.04 & Codespaces

crates/validation/src/collection.rs, crates/validation/src/errors.rs, crates/validation/tests/scenario_tests.rs, crates/validation/tests/snapshots/scenario_tests__collection_schema_string.snap, crates/validation/tests/snapshots/scenario_tests__schema_fragment_not_found.snap, crates/validation/tests/snapshots/scenario_tests__schema_reference_verification.snap
Resolves #127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/197)
=> Validate that top level collection schema is an object

go/runtime/split_workflow.go
Fixes #211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/214)
=> Updated ranges to use inclusive values when requesting split

go/runtime/capture.go
To ensure the CGO service is destroyed during garden-path processing.
Current suspicion is that buffers allocated by the CGO service (into
which combined results are marshalled) are what are leaking.
Technically they have a finalizer, but if Go memory pressure doesn't
require a GC they may never actually be reclaimed.
Issue #226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/227)
=> capture: defer a combiner.Destroy

go/runtime/flow_consumer.go, go/shuffle/read.go, go/shuffle/read_test.go, go/shuffle/reader.go, go/shuffle/reader_test.go, go/shuffle/ring.go, go/testing/driver.go
Issue #226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/229)
=> fix two teardown-related edge case bugs in shuffled reads

crates/derive/src/combine_api.rs, crates/derive/src/combiner.rs, crates/json/benches/citi_rides.rs, crates/json/benches/github_events.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/239)
=> instrument combiner with more debug logging

crates/protocol/src/consumer.rs, go.mod, go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/251)
=> go.mod: bump gazette to bring in read_channel_size & instrumentation

.devcontainer/github-ubuntu-2004.Dockerfile, Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/252)
=> make: switch to llvm 12

go/capture/driver/airbyte/connector.go, go/capture/driver/airbyte/connector_test.go, go/materialize/driver/image/driver.go
Issue #257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/258)
=> connectors: protoOutput must init a new record rather than re-use

README.md
- Replace code example with something simpler
- Links across top
- Re-wording, nitpicking etc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/295)
=> README updates and fine-tuning

README.md, examples/citi-bike/rides.flow.yaml
Use the Citi Bike rides schema and projections,
and fix the materialization endpoint (`postgres` was removed).
Add a new "Run It" section with (current) directions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/304)
=> README: update the 'show me the code' example

go/flow/builds.go, go/flow/builds_test.go, go/flowctl/cmd-api-activate.go, go/flowctl/cmd-test.go
* flowctl test: don't fail-fast if there are no derivations
* flowctl api activate: Enable capture.ApplyUpsert
* go/flow: de-index *sharedBuild if reference count is zero
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/306)
=> various fixes

go/bindings/combine.go, go/bindings/derive.go
As part of #316, the shard and collection labels were removed from the
prometheus metrics. That now seems to have been premature, since we
don't yet have an easy way to get grafana dashboards from the new stats
collections. This adds the labels back onto the prometheus metrics so
that the old grafana dashboards will continue to function, at least
until we're able to implement their replacements.
**Workflow steps:** no change
**Notes for reviewers:** n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/358)
=> Re-enable per-task prometheus combiner metrics

go/protocols/capture/pull_client.go, go/protocols/capture/pull_client_test.go
Update PullClient to prefer to include ready responses in a current
transaction. It will no longer start to commit a current transaction
when that txn isn't full, and there are ready documents to read.
Tweak test case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/364)
=> go/protocols: fix PullClient flake

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/amazon-kinesis.md, site/docs/reference/Connectors/capture-connectors/apache-kafka.md
Add docs for Kinesis and Kafka connectors
NA
NA
As always, this is a technical review to ensure I captured the appropriate level of detail for users and didn't misinterpret anything along the way. It seemed reasonable to combine two connector docs into one PR; I'm sure it's obvious but I'm only asking you to review the connector you wrote (:
A few specific requests
- (BOTH) - For both these connectors, I'm unsure what the role of `namespace` is in the binding config, or if it needs to be reflected here. Please advise!
- (KAFKA) - as noted in the code sample, I could use some good example auth parameters
--- …
=> Kinesis + Kafka connector docs

site/docs/reference/working-logs-stats.md, site/package-lock.json
Add docs for `flowctl logs` subcommand. Ended up being pretty straightforward, so will merge directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/392)
=> docs for flowctl logs

site/docs/concepts/materialization.md, site/docs/reference/Connectors/materialization-connectors/Rockset.md
In light of https://github.com/estuary/connectors/issues/115, the Rockset connector can handle TOASTed values without issue, but there are important considerations regarding delta updates and reduction strategies that users should be aware of.
na
The usual - needs a fact-check as some assumptions were involved. One specific question noted inline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/399)
=> Docs: add more delta updates info and rockset-specific caveats

site/docs/guides/connect-network.md, site/docs/reference/Connectors/capture-connectors/MySQL.md, site/docs/reference/Connectors/capture-connectors/PostgreSQL.md, site/docs/reference/Connectors/capture-connectors/amazon-kinesis.md, site/docs/reference/Connectors/capture-connectors/amazon-s3.md, site/docs/reference/Connectors/capture-connectors/apache-kafka.md, site/docs/reference/Connectors/capture-connectors/gcs.md, site/docs/reference/Connectors/materialization-connectors/BigQuery.md, site/docs/reference/Connectors/materialization-connectors/Rockset.md, site/package-lock.json
Adds docs to...
- Mysql connector
- Postgres connector
- SSH setup guide 
...which covers implementations on...
- AWS
- GCloud 
- Azure
... per https://docs.google.com/document/d/18tLqjKmdVSyqGtTgXOdoHXrH_9OsqNumapmP5FVi3SE/edit.
Needs a second set of eyes for completeness and accuracy. It should be noted that while I did spend quite a bit of time reading and referencing the UI for the VMs and managed DBs on the three platforms, I didn't set up complete end-to-end dataflows for each workflow (for the sake of time, since complete testing was done quite recently).
Also looks like some of the changes to config tables I did recently got rolled into this PR (?). No need to review all that.
--- …
=> Docs - managed DBs for MySql and Postgres; SSH

site/docs/reference/Connectors/materialization-connectors/BigQuery.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/434)
=> typo in bigquery docs example configuration

site/docs/reference/Connectors/materialization-connectors/Snowflake.md
- Add note about reserved words of Snowflake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/447)
=> docs: document Snowflake reserved words

site/docs/reference/Connectors/materialization-connectors/BigQuery.md, site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/Snowflake.md
Adds docs for materialize-snowflake
* I may still test in snowflake, if we do still have credentials
* Parameter descriptions were written by me
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/429)
=> Snowflake connector docs

site/docs/reference/Connectors/README.md, site/docs/reference/Connectors/capture-connectors/MySQL.md, site/docs/reference/Connectors/capture-connectors/PostgreSQL.md, site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/amazon-kinesis.md, site/docs/reference/Connectors/capture-connectors/amazon-s3.md, site/docs/reference/Connectors/capture-connectors/apache-kafka.md, site/docs/reference/Connectors/capture-connectors/exchange-rates.md, site/docs/reference/Connectors/capture-connectors/facebook-marketing.md, site/docs/reference/Connectors/capture-connectors/gcs.md, site/docs/reference/Connectors/capture-connectors/google-analytics.md, site/docs/reference/Connectors/capture-connectors/google-sheets.md, site/docs/reference/Connectors/capture-connectors/hubspot.md, site/docs/reference/Connectors/capture-connectors/mailchimp.md
Adds documentation for the 6 airbyte connectors that we currently support. 
We should have basic docs for all connectors available, in the interest of MVP. These docs will definitely be refined later, especially because we are actively working on refining several of these connectors. 
https://go.estuary.dev/tmiNoF - Mailchimp
https://go.estuary.dev/XSVhJy - hubspot
https://go.estuary.dev/phEkVt  and https://go.estuary.dev/RP7TxO - google sheets
https://go.estuary.dev/kbrc7P - exchange rates
https://go.estuary.dev/OzUqlE - FB marketing
https://go.estuary.dev/6PgxMK - GA
Will update after updating the live docs site
I'm breaking my review request down by the owner of each connector. 
(In hindsight, I should've made …
=> Document Airbyte connectors

site/docs/concepts/README.md, site/docs/concepts/_category_.json, site/docs/concepts/advanced/projections.md, site/docs/concepts/captures.md, site/docs/concepts/import.md, site/docs/concepts/schemas.md, site/docs/concepts/storage-mappings.md, site/docs/concepts/tests.md, site/docs/getting-started/_category_.json, site/docs/getting-started/flow-tutorials/_category_.json, site/docs/getting-started/installation.md, site/docs/guides/_category_.json, site/docs/guides/connect-network.md, site/docs/guides/create-dataflow.md, site/docs/overview/README.md, site/docs/overview/comparisons.md, site/docs/overview/who-should-use-flow.md, site/docs/reference/Connectors/_category_.json, site/docs/reference/organizing-catalogs.md, site/docs/reference/working-logs-stats.md
A lot of changes, all over the place, mostly concerning making higher-level docs more user-friendly, mentioning what can be done in the UI vs CLI, etc.
Self-reviewed. Nothing too technical here
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/491)
=> Updates dealing with UI-first approach, among other things

go.mod, go.sum
This package is not the same as the one set in the connector. Updating
it to match the same version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/502)
=> sqlDriver: Update older jsonschema package

go/protocols/materialize/client.go
From materialization connectors. There are valid use-cases for the
connector to load documents which weren't explicitly requested by the
runtime, such as for compaction and pruning.
Issue estuary/connectors#233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/506)
=> protocols: relax constraint that we only expect flighted documents

site/docs/reference/Connectors/materialization-connectors/BigQuery.md, site/docs/reference/Connectors/materialization-connectors/Google-sheets.md, site/docs/reference/Connectors/materialization-connectors/README.md
Adds documentation for new google sheets materialization connector. 
This one's pretty straightforward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/511)
=> Docs: Materialize Google Sheets

crates/connector_proxy/src/connector_runner.rs
- There is a case where a process may exit before the stdin of connector proxy has reached EOF (it is pending more data)
- In this case, we were waiting for our streams to end before processing exit status of the child
- I changed this behaviour so that we join exit status and streaming of data, so that we can bail out on failure of whichever comes first. In this case, exit status will finish with an `Err`, so the `try_join` will return early with that error and we proceed to exit the connector-proxy process.
I tried to write a test for this, but unfortunately the process gets stuck waiting for the stream. In case of a real run of connector-proxy, we manually do `std::process:exit` when we see an error, however I can't do that in the test because it breaks the test …
=> connector-proxy: handle case of child exitting before EOF in streams

site/docs/reference/Connectors/capture-connectors/MySQL.md, site/docs/reference/Connectors/capture-connectors/PostgreSQL.md
We've just landed some breaking changes to the SQL capture configurations in order to make them more user-friendly, so this should update the docs to match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/525)
=> docs/{MySQL,PostgreSQL}: Update configuration details

crates/connector_proxy/src/libs/command.rs
- some variations / versions of read require an argument
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/544)
=> connector_proxy: pass an argument to read -r

site/docs/reference/Connectors/materialization-connectors/Snowflake.md
Adds documentation around a new Snowflake config field: https://github.com/estuary/connectors/pull/259
N/A
This is it :tada: 
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/529)
=> Add Snowflake cloud provider docs

go/protocols/materialize/sql/driver.go
- ApplyDelete should be idempotent, so changing the code to respect that: if we can't load MaterializationSpec, we assume we have already done ApplyDelete and just skip.
- If the tables themselves have been individually deleted by user, we do not error out and allow deletion of the materialization
- resolves https://github.com/estuary/connectors/issues/255
- Delete a postgres materialization
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/536)
=> materialize/sql: idempotent ApplyDelete

crates/build/src/lib.rs
It's expected that user code may have TypeScript errors, and `tsc` may
then exit with an error after printing out a bunch of error info.
Currently build bubbles up an error, which causes `flowctl api build` to
exit with an error, but in these cases the build DB may not have
contained an entry in the `errors` table. This confuses the
control-plane agent which (reasonably) expects such an error to exist.
Refactor a bit to generate and include a TypeScript compilation issue as
a recorded build DB error.
Manually tested with broken example TypeScript module. …
=> build: add a catalog build error if TypeScript compilation fails

site/docs/reference/Connectors/materialization-connectors/Snowflake.md
Title says it all. Per recent testing. 
Going to skip a review I think because this ended up being essentially copy-paste.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/557)
=> Docs - add script for materialize-snowflake setup

.cargo/config.toml, Makefile, README.md, go.sh, go/bindings/pipe_bsd.go, go/bindings/pipe_linux.go, go/bindings/service.go, go/flow/js_worker.go, go/flow/js_worker_sys_proc_attr_bsd.go, go/flow/js_worker_sys_proc_attr_linux.go, go/flowctl-go/cmd-temp-data-plane.go, go/flowctl-go/sys_proc_attr_bsd.go, go/flowctl-go/sys_proc_attr_linux.go
- Supports darwin-arm64 platform
- `make`!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/575)
=> M1 compatibility

Makefile
Adds support for building on intel (non-m1) macs.
Run `make package` from an intel mac. The application will successfully build.
N/A
Adding another branch to the `etcd` download part is a little ugly, but since this should be consolidated once an official M1 build is available I left it like that. Alternatively we could extract this out into a script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/594)
=> Update makefile for building on intel macs

site/docs/reference/Connectors/capture-connectors/MySQL.md, site/docs/reference/Connectors/capture-connectors/PostgreSQL.md, site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/gcs.md, site/docs/reference/Connectors/capture-connectors/http-file.md, site/docs/reference/Connectors/capture-connectors/hubspot.md, site/docs/reference/Connectors/capture-connectors/intercom.md, site/docs/reference/Connectors/capture-connectors/mailchimp.md
Adds docs for the new http file source connector, https://github.com/estuary/connectors/pull/288
I added descriptions manually to the credentials config - I would recommend also adding these formally so they reflect in the UI. Let me know if it'd help for me to put up a ticket!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/589)
=> docs: source-http-file 

site/docs/reference/Connectors/capture-connectors/amazon-s3.md, site/docs/reference/Connectors/capture-connectors/gcs.md, site/docs/reference/Connectors/capture-connectors/http-file.md
Updates docs on parser config per https://github.com/estuary/flow/pull/591
These are in:
* source-s3
* source-gcs
* source-http-file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/602)
=> docs: updated parser config with discriminator 

site/docs/reference/Connectors/capture-connectors/hubspot.md
Updates per https://github.com/estuary/airbyte/pull/27 for new credential method
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/621)
=> docs: update source-hubspot

go/protocols/capture/pull_client.go, go/protocols/capture/pull_client_test.go, go/protocols/capture/push_server.go, go/protocols/capture/push_server_test.go, go/runtime/capture.go
We encountered some reactor pods which were wedged on shutdown.
On investigation, they had capture PullClients which were instantiated
but never started Serve(). The effect of this was they blocked
indefinitely on teardown awaiting resolution of the `loopOp` future,
which resolves only when the Serve() loop completes -- which could never
happen in these cases.
It was previously possible for a PullClient to be created but for the
shard to be cancelled or the task term changed before Serve() was
invoked. Refactor so that the serve loop is an inner implementation
detail which *must* be spawned for a constructed PullClient to be
returned. Further, defer the instantiation of a PullClient until needed
in StartReadingMessages.
No public impacts.
(How does one …
=> protocols/capture: simplify public interface and ensure serve loop runs

README.md
- For M1 you need to install `coreutils` for things like `nproc`
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/637)
=> readme: install coreutils for m1

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/662)
=> README.md: Fix broken image link

site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/google-pubsub.md
Adds docs for the new Google Pub/Sub materialization
(https://github.com/estuary/connectors/pull/336)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/671)
=> Docs: Materialize Google Pub/Sub

Makefile
- etcd 3.5.5 is finally here with official darwin-arm64 release
- simplified etcd's installation
- `make`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/675)
=> makefile: update to etcd 3.5.5 with official darwin-arm64 build

go/protocols/capture/pull_client.go, go/protocols/capture/pull_client_test.go
Otherwise the PullClient loop may deadlock waiting for commit operations which will never occur.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/677)
=> capture: we must monitor `ctx` if blocked on commit operations

crates/doc/src/inference.rs
Closes https://github.com/estuary/flow/issues/631
Removes the check that disallows integer property names schema, and teaches `Shape` to infer object properties with integer names.
With this change, collections with schemas like this can be used:
```yaml
example/int-props:
schema:
type: object
properties:
1:
type: object
properties:
2:
type: string
required: ["2"]
-: { type: string }
required:
- "1"
key: [/1/2]
```
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/676)
=> crates/doc: permit integer property names

site/docs/getting-started/installation.md, site/docs/reference/Connectors/capture-connectors/amazon-s3.md, site/docs/reference/Connectors/capture-connectors/gcs.md, site/docs/reference/Connectors/capture-connectors/google-analytics.md, site/docs/reference/Connectors/materialization-connectors/Google-sheets.md, site/docs/reference/Connectors/materialization-connectors/Parquet.md, site/docs/reference/Connectors/materialization-connectors/google-pubsub.md
Includes updates from the following PRs:
* https://github.com/estuary/flow/pull/689
* https://github.com/estuary/connectors/pull/340
* https://github.com/estuary/connectors/pull/343
* https://github.com/estuary/connectors/pull/356
* https://github.com/estuary/connectors/pull/354
* https://github.com/estuary/connectors/pull/351
I'll also need to update https://go.estuary.dev/flowctl
Self-review (proofreading)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/697)
=> docs: various smaller updates

go/connector/run.go
- I just saw this error on production (intermittent):
```
-- time="2022-09-28T16:43:50Z" level=fatal msg="fatal error" err="inspecting container port failed: go.estuary.dev/E111: getting docker entity \"\"'s port failed: exit status 1"
```
Which means `ReadFile` succeeded, but was empty. So I guess it takes some time in between the creation of the file and writing of the content in it by docker.
- I also saw this error (also intermittent):
```
-- time="2022-09-28T16:47:00Z" level=fatal msg="fatal error" err="inspecting container port failed: go.estuary.dev/E111: getting docker entity \"64ab7e6238c7120e31217107a536a0a7cd1f98c127609ece72f806a1ed2cc354\"'s port failed: exit status 1"
```
which similarly means the docker port command may need to wait until the container is in …
=> connector/run: find port before running docker

control_plane_readme.md
Adds build tools and bootstrap steps to readme doc.
N/A
N/A
This is based on ubuntu 20.04 LTS (focal) base image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/703)
=> Fix add bootstrap steps

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/bing-ads.md, site/docs/reference/Connectors/capture-connectors/google-firestore.md
Adds docs for source-bing-ads
Also sneak in a tweak to the source-firestore endpoint config docs. 
https://go.estuary.dev/QpEo4F
self-review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/721)
=> docs: bing ads

local/start-component.sh, supabase/functions/oauth/access-token.ts, supabase/functions/oauth/auth-url.ts, supabase/functions/oauth/encrypt-config.ts
Some locals were complaining about typing for edge functions. Added some basic types.
Added an option to the start of the agent to use the host network
Start up edge functions
None
We still need to put some more work into the edge functions. I think we need to check for data being there and clean up the typing, messaging, error handling overall. However, I will take that on in a future PR. Wanted to unblock myself and others with this ASAP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/715)
=> Fixing some minor issues with UI local development

site/docs/guides/system-specific-dataflows/firestore-to-dwh.md, site/docs/reference/Connectors/capture-connectors/google-firestore.md
Adds a specific user guide on creating a data flow from firestore to snowflake, per customer request
plus a few typo fixes and grammar nits
No shortlinks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/722)
=> docs: firestore to snowflake guide

supabase/functions/_shared/helpers.ts
- add `basicauth` helper to oauth helper functions (used in notion)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/730)
=> oauth: add basicauth helper

go/connector/run.go
- Add detail / context to errors in run.go, otherwise context of some errors such as TCP errors are not easily distinguishable from each other
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/723)
=> connector/run: add more detail to errors in run.go

.github/workflows/control-ci-cd.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/735)
=> ci: run control ci-cd when the config changes

supabase/functions/oauth/access-token.ts, supabase/functions/oauth/auth-url.ts
Rolling back the Handlebars version/deps change
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/738)
=> Rolling back changes to Handlebars version

crates/connector_proxy/src/connector_runner.rs
This is the cleanest cut-point I could find to disable the network tunneling logic in connector_proxy, by removing all mention of the wrapping operations
NetworkTunnelCaptureInterceptor::adapt_{request,response}_stream
from the connector runner functions.
This commit is deliberately kept to a really small diff so we can wait and verify that everything still works in prod for a bit before we start removing all the code that this change renders dead.
In theory this should have no noticeable impact (other than fixing the current bug with the `spec` subcommand), as the network tunneling logic has already been moved into the connectors that use it.
- - - …
=> connector_proxy: Don't use NetworkTunnelCaptureInterceptor

supabase/migrations/10_spec_ext.sql
- The previous PR was #742 was using user `postgres` to query the database which bypassed the RLS policy. This PR introduces a join with `auth_rules` which enforces the policy as a join.
- Also applied the same performance change to `combined_grants_ext`
- - - …
=> supabase: live_specs_ext use join with auth_rules

crates/connector_proxy/src/main.rs
- Pass `--log.level` down to connectors when invoking them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/772)
=> connector-proxy: pass --log.level down to connectors

go/runtime/derive.go
The trampoline server of a derive binding may be running concurrent tasks up until the point that binding.Destroy returns. Those tasks may be using the npm / TypeScript server which is managed by the `taskTerm`, so we must destroy the former before the latter.
- - - …
=> runtime: swap Derive.Destroy order to prevent use-after-free of npm server

supabase/functions/_shared/helpers.ts, supabase/functions/oauth/access-token.ts, supabase/functions/oauth/auth-url.ts
As we are looking to move Oauth towards Mustache we need to make sure the template are outputting the same thing as things could easily fail silently.
Impact all Oauth calls that use templates.
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/776)
=> Adding mustache to compare template output with Handlebars

Cargo.lock, crates/flowctl/Cargo.toml, crates/flowctl/src/auth/mod.rs, crates/flowctl/src/auth/roles.rs, crates/flowctl/src/catalog/mod.rs, crates/flowctl/src/collection/mod.rs, crates/flowctl/src/config.rs, crates/flowctl/src/dataplane.rs, crates/flowctl/src/draft/author.rs, crates/flowctl/src/draft/develop.rs, crates/flowctl/src/draft/mod.rs, crates/flowctl/src/lib.rs, crates/flowctl/src/raw.rs
- Revert #792 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/824)
=> Revert flowctl login changes

crates/proto-flow/src/flow.rs, go/protocols/flow/flow.proto, supabase/functions/_shared/helpers.ts, supabase/functions/oauth/access-token.ts, supabase/functions/oauth/auth-url.ts
- After #833 , I tested all connectors OAuth flows and ensured there are no incompatibilities, and now I feel comfortable removing Handleabars and doing a full switch to Mustache
N/A, transparent to users
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/841)
=> oauth: full switch to mustache

site/docs/concepts/flowctl.md, site/docs/concepts/import.md, site/docs/getting-started/installation.md, site/docs/guides/create-derivation.md, site/docs/reference/authentication.md
Documents the set of changes from:
* https://github.com/estuary/flow/pull/837
* https://github.com/estuary/flow/pull/828
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/859)
=> docs: flowctl updates

site/docs/concepts/schemas.md, site/docs/concepts/web-app.md, site/docs/guides/create-dataflow.md, site/docs/guides/edit-data-flows.md, site/docs/guides/system-specific-dataflows/firestore-to-dwh.md, site/docs/guides/system-specific-dataflows/s3-to-snowflake.md, site/docs/reference/editing.md
Updates docs for:
* Schema inference. Conceptual overview, noting where it's available, and updating guides and tutorials accordingly
* Improved organization: moving Edit workflow steps to the Guides node (where they belong...). 
* Recent changes to UI elements (mainly https://github.com/estuary/ui/pull/433)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/887)
=> Docs: schema inference & recent UI updates

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/google-analytics-4.md, site/docs/reference/Connectors/capture-connectors/google-analytics.md, site/package-lock.json, site/package.json
Adds docs for the new connector, source-google-analytics-data-api (GA4)
Resolves https://github.com/estuary/airbyte/issues/113
The config descriptions currently contain these shortlinks:
https://go.estuary.dev/fz3SSy
https://go.estuary.dev/C9pwjr
... which are for our UA connector and should be replaced with shortlinks specific to this connector. 
Also, the documentation URL for this connector will need a new shortlink.
* Not 100% on my interpretation of custom reports, so that could use a critical eye. Everything else is tested. 
* A bot recently upgraded docusaurus, which required a node update, hence the much larger than usual changes to  package-lock.json
- - - …
=> docs: source-google-analytics-data-api

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/sqlserver.md
Adds docs for new source-sqlserver connector (https://github.com/estuary/connectors/pull/532). 
Included a quick how-to section on updating the collection key with flowctl. I figure that'll probably go away or change pretty soon but good to have for now. 
I did not test this on AWS as of now but hoping to circle back on that soon as time permits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/937)
=> docs: source-sqlserver

local/start-component.sh
This is to work around issues connecting from the oauth function to the config-encryption service. I feel fairly confident that this ought to work for Mac and WSL users, but would appreciate some help testing it out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/944)
=> Run config-encryption in docker locally

site/docs/reference/Connectors/capture-connectors/mongodb.md
document https://github.com/estuary/connectors/pull/548
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/950)
=> docs: capture MongoDB

site/docs/reference/Connectors/capture-connectors/alpaca.md
Documentation updates for https://github.com/estuary/connectors/pull/574
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/964)
=> docs: source-alpaca minimum backfill start date

site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/amazon-redshift.md
Docs for new `materialize-redshift` connector, see https://github.com/estuary/connectors/pull/580
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/965)
=> docs: materialize-redshift

site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/SQLite.md
- add `materialize-sqlite` connector dogs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/973)
=> docs: add materialize-sqlite

go/flowctl-go/cmd-api-activate.go
Closes https://github.com/estuary/flow/issues/970
This change will trigger an unassignment of failed shards when a publication is activated with `flowctl-go api activate`.
This is helpful for situations where a task has stopped working and a user publishes a change to fix it. Currently they will have to wait a while until the shard supervisor restarts the failed shard to see if the fix worked. With this, the shard will immediately be re-assigned so they will know right away if they task is working.
N/A
- - - …
=> flowctl-go: unassign failed shards when activating a publication

crates/agent/src/directives/beta_onboard.rs
Allow an optional `survey` property, with any JSON type, to be associated with `betaOnboard` directive claims.
Begin submitting directive claims which include a `survey` property with arbitrary sub-structure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1008)
=> agent: allow onboarding claims to have an optional `survey` field.

.vscode/settings.json, Tiltfile, supabase/env.local, supabase/functions/oauth/access-token.ts
Fix a type-check that currently fails on a local stack (and would fail if applied in prod?).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1019)
=> oauth: fix type-check error in access-token edge function

Tiltfile
At least I'm assuming the `--control-plane-auth-url` was just a typo. LMK if not
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1021)
=> fix typos in Tiltfile

crates/flowctl/src/raw/capture.rs
- fix an issue where the channel might end up being full and we bail out: we need to just backpressure by holding off on reading more messages from connector until we can combine and drain the already-queued ones.
- - - …
=> flowctl: fix raw capture backpressure from channel

site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/pinecone.md
New docs for the new `materialize-pinecone` connector (see https://github.com/estuary/connectors/pull/730)
These are new documents
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1054)
=> docs: materialize-pinecone docs for new connector

go.mod, go.sum, go/protocols/materialize/sql/std_fence.go, go/runtime/flow_consumer.go, go/shuffle/ring.go
Use the standard library `errors` package everywhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1058)
=> runtime: cleanup uses of `errors` package

crates/flowctl/src/raw/capture.rs
- I found this extremely useful to troubleshoot an issue with `source-s3` (`filesource`) that we were discussing [here](https://github.com/estuary/connectors/pull/726). This allows you to see how the checkpoint is evolving for a connector.
```
flowctl raw capture source-s3.flow.yaml --print-checkpoint
```
- - - …
=> flowctl: option to print checkpoint updates in raw capture

Cargo.lock, crates/derive-sqlite/src/connector.rs, crates/derive-sqlite/src/dbutil.rs, crates/derive-sqlite/src/validate.rs, crates/derive-typescript/src/lib.rs, crates/doc/src/inference.rs, crates/flowctl/src/lib.rs, crates/flowctl/src/local_specs.rs, crates/flowctl/src/preview/mod.rs, crates/flowctl/src/raw/mod.rs, crates/json/Cargo.toml, crates/json/src/schema/formats.rs, crates/json/src/validator.rs, crates/runtime/src/derive/combine.rs, crates/schema-inference/Cargo.toml, crates/schema-inference/src/analyze.rs, crates/schema-inference/src/inference.rs, crates/schema-inference/src/shape.rs, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_back_to_string-2.snap, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-2.snap, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-3.snap, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging-4.snap, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_merging.snap, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings-2.snap, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings-3.snap, crates/schema-inference/src/snapshots/schema_inference__analyze__test__string_format_number_special_strings.snap, go/connector/container.go, go/protocols/materialize/client.go, go/runtime/flow_consumer.go
See individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1069)
=> improve `flowctl preview` and various other fixes

site/docs/reference/Connectors/capture-connectors/amazon-kinesis.md, site/docs/reference/Connectors/capture-connectors/amazon-s3.md, site/docs/reference/Connectors/capture-connectors/gcs.md, site/docs/reference/Connectors/capture-connectors/http-file.md, site/docs/reference/Connectors/capture-connectors/sftp.md
A couple of updates mostly to filesource-based capture connectors; see individual commit messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1076)
=> docs: updates to filesource connector docs

crates/agent/src/publications/builds.rs
I discovered a fairly major bug in the agent that causes it to crash when failing to publish due to incompatbile collections. Additionally, it was misidentifying collections that need to be re-created due to lacking the `x-infer-schema` annotation. This fixes both issues. There's an unfortunate lack of automated tests for this, but I'm thinking that perhaps a future commit could move the `BuildOutput` into the `validations` crate and be covered by the scenario tests there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1092)
=> agent: fix publish bug in checking for incompatible collections

.github/workflows/main.yml, Cargo.lock, Cargo.toml, crates/connector-init/src/rpc.rs, go.mod, go.sum, go/protocols/capture/pull_client.go
Also increase a buffer size, and send a single
capture.Request.Acknowledge with a count, rather than one Acknowledge
for each committed transaction.
These changes are all performance improvements, with no change to features or semantics.
- - - …
=> update tonic and gazette versions used by Flow

crates/flowctl/src/catalog/mod.rs
Fixes #1117
When fetching many live specs by name, we would overflow the URL length limit. This changes it to instead chunk up the names into batches of 25 and make a separate request for each batch. This ensures that our URL lengths stay well under the limit.  I went ahead and did the same thing for prefix-based fetching, while I was in here.
It's possible that there's some other API calls that would need to be chunked in the same way, though none were immediately obvious. I'm confident that this at least fixes the immediate problem, so am inclined to just merge and worry about any other sites requiring chunking later.
- - - …
=> flowctl: use multiple requests for fetching many specs

site/docs/reference/Connectors/capture-connectors/aircall.md, site/docs/reference/Connectors/capture-connectors/amazon-sqs.md, site/docs/reference/Connectors/capture-connectors/bigquery.md, site/docs/reference/Connectors/capture-connectors/oracle-db.md, site/docs/reference/Connectors/capture-connectors/pinterest.md, site/docs/reference/Connectors/capture-connectors/postgres-heroku.md, site/docs/reference/Connectors/capture-connectors/woocommerce.md
New connector docs for:
1. Aircall
2. Amazon SQS
3. Bigquery (Capture)
4. Oracle Database
5. Pinterest
6. Postgres (Heroku)
7. Woocommerce
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1118)
=> New connector docs

site/docs/reference/Connectors/capture-connectors/amazon-dynamodb.md
Docs for the new `source-dynamodb` connector, see https://github.com/estuary/connectors/pull/877
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1139)
=> docs: docs for new source-dynamodb connector

site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/amazon-dynamodb.md
Docs for https://github.com/estuary/connectors/pull/928
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1169)
=> docs: materialize-dynamodb docs

site/docs/reference/Connectors/materialization-connectors/Elasticsearch.md
Doc updates to `materialize-elasticsearch` per changes in https://github.com/estuary/connectors/pull/910
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1161)
=> docs: update materialize-elasticsearch docs

crates/flowctl/src/config.rs
We've observed an infrequent but _super_ annoying bug where flowctl can occasionally truncate its own config file. This seems to be related to concurrent invocations of flowctl, where one instance will observe the truncated config file as it's being overwritten by another instance.  In some scenarios, we've also observed the config file being left in a truncated state.
This commit updates the `Config::write` function to write the config to a temp file, which is subsequently renamed to the target config file. This guarantees that another instance will either see the first version of the config file, or the new one, but never anything in between.
- - - …
=> flowctl: atomically persist config files

crates/runtime/src/container.rs
For unknown reasons, `docker run` invocations within Gitpod don't emit any stdout or stderr from the container, which is currently breaking our container startup logic. Add `--tty` -- which muxes stderr into stdout -- as a work-around.
We should revert this commit when we can. See:
https://github.com/gitpod-io/gitpod/issues/18814
- - - …
=> runtime: temporarily add --tty to containers to un-break Gitpod

site/docs/reference/Connectors/materialization-connectors/mongodb.md
This connector no longer uses the checkpoints table, so remove that part from the docs.
See https://github.com/estuary/connectors/pull/952
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1181)
=> docs: update materialize mongodb docs

crates/doc/src/combine/spill.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1224)
=> combine: fix off-by-one errors in logged trace

site/docs/reference/Connectors/capture-connectors/amazon-rds-mariadb.md, site/docs/reference/Connectors/capture-connectors/amazon-rds-mysql.md, site/docs/reference/Connectors/capture-connectors/amazon-rds-postgres.md, site/docs/reference/Connectors/capture-connectors/amazon-rds-sqlserver.md, site/docs/reference/Connectors/materialization-connectors/amazon-rds-mysql.md, site/docs/reference/Connectors/materialization-connectors/amazon-rds-postgres.md, site/docs/reference/Connectors/materialization-connectors/amazon-rds-sqlserver.md
Amazon RDS Connector Docs
Capture
- MySQL
- PostgreSQL
- Mariadb
- SQL Server
Materialize
- MySQL
- PostgreSQL
- SQL Server
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1272)
=> Wihl amazon rds docs

site/docs/reference/time-travel.md
First version of time travel docs. Eventually to be referenced by all existing materialization docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1275)
=> Wihl time travel docs

site/docs/reference/Connectors/materialization-connectors/databricks.md
- Basic documentation for Databricks https://github.com/estuary/connectors/pull/1021
- I expect to add more to these docs specially around performance considerations as we learn more about the system
- - - …
=> docs: databricks

supabase/migrations/39_alerts.sql
Updates the alerts migration to include a couple of fixes we identified during the deployment and testing of this feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1293)
=> control-plane: fix alerts migration

site/docs/reference/Connectors/materialization-connectors/README.md
- I had forgotten to add databricks page to sidebar
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1294)
=> docs: add materialize databricks to sidebar

site/docs/reference/Connectors/capture-connectors/netsuite-odbc.md
Documentation for the alpha version of the NetSuite Connector.
Self explanatory. 
Net-new documentation link.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1311)
=> docs: netsuite connector alpha docs

site/docs/reference/Connectors/materialization-connectors/databricks.md
- See https://github.com/estuary/connectors/pull/1123
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1308)
=> docs/databricks: cost-saving using update delay and Auto Stop

site/docs/reference/Connectors/capture-connectors/apache-kafka.md
- Update docs to reflect changes in https://github.com/estuary/connectors/pull/1129
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1319)
=> docs: update docs for kafka connector

Makefile
looks like a custom alias
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1320)
=> fix: remove dependence on nproc

site/docs/reference/Connectors/capture-connectors/sftp.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1356)
=> docs: add sshKey to source-sftp docs

crates/parser/src/format/character_separated/detection.rs
Updates the parser CSV dialect detection to explicitly prefer double quotes when there's a tie between two dialects.  Also improves the logging of dialect detection to log the top few runners up, to aid in debugging.
I'm doubtful that this will fix the issue with the specific file that's failing in production, but I do think it will at least help debugging the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1358)
=> parser: prefer double quotes in dialect detection

go.mod, go.sum
Pulls in gazette/core#363
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1368)
=> update gazette dependency to pull in shards prune fix

site/docs/reference/Connectors/materialization-connectors/starburst.md
Remove duplicated information
https://docs.estuary.dev/reference/Connectors/materialization-connectors/starburst/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1380)
=> Remove duplicated information

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/snowflake.md
Adds setup/configuration docs for the new `source-snowflake` connector.
The shortlink go.estuary.dev/source-snowflake should already be pointed at the correct place, so once this is merged everything should be good.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1373)
=> docs/snowflake: Initial documentation

site/docs/reference/Connectors/materialization-connectors/Elasticsearch.md
Doc updates for https://github.com/estuary/connectors/pull/1268
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1383)
=> docs: elasticsearch docs for materializing keywords

site/docs/reference/Connectors/materialization-connectors/BigQuery.md
Docs about how to modify a table to have specific partitioning while materializing to that table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1387)
=> docs: materialize-bigquery partitioning information

site/docs/reference/Connectors/capture-connectors/google-ads.md
Updating `source-google-ads` to contain information on both ClickView streams and customer_id credentials.
Both `customer_id` and `login_customer_id` explanation may seem redundant. I choose to add both explanations since when creating a soure-google-ads connector on estuary dashboard, i did receive a email claming some users do experience issues in setting them up.
Also added pictures and directions to where both settings can be found in Gads dashboard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1384)
=> Update Google Ads Docs

Cargo.lock, Cargo.toml, crates/connector-init/src/codec.rs, crates/flowctl/Cargo.toml, crates/runtime/src/container.rs, crates/runtime/src/rocksdb.rs, go.mod, go.sum
Run a general `cargo update`.
Update our rust-rocksdb to rebase on their most-recent release. All but one of changes have been merged upstream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1389)
=> update a number of dependencies, including RocksDB (to 8.10)

site/docs/reference/Connectors/capture-connectors/http-ingest.md
Docs-only update to go along with estuary/connectors#1276
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1392)
=> docs: update source-http-ingest reference for paths endpoint config

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/gladly.md
Basic documentation for the `source-gladly` connector.
See https://github.com/estuary/connectors/pull/1308
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1402)
=> docs: source-gladly

site/docs/reference/Connectors/materialization-connectors/Snowflake.md
- Documents how to configure Snowpipe by using key-pair authentication
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1407)
=> docs: snowpipe docs

go.mod, go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1416)
=> update gazette dependency to pull in gazette/core#369

Cargo.lock, Cargo.toml, crates/doc/src/combine/memtable.rs, crates/doc/src/combine/mod.rs, crates/doc/src/combine/spill.rs, crates/doc/tests/combiner_perf.rs, crates/doc/tests/merge_patch_fuzz.rs, crates/doc/tests/spill_merge_fuzz.rs, crates/flowctl/src/raw/mod.rs, crates/network-tunnel/Cargo.toml, crates/parser/src/input/mod.rs, crates/runtime/src/capture/task.rs, crates/runtime/src/combine/protocol.rs, crates/runtime/src/derive/task.rs, crates/runtime/src/materialize/task.rs, crates/runtime/src/rocksdb.rs, local/README.md
Improve schema validation errors by including metadata about the collection that failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1408)
=> improve schema validation errors by including metadata about the collection that failed

site/docs/reference/Connectors/capture-connectors/notion.md
Doc updates for https://github.com/estuary/connectors/pull/1407
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1421)
=> docs: update source-notion

site/docs/reference/Connectors/materialization-connectors/BigQuery.md, site/docs/reference/Connectors/materialization-connectors/Snowflake.md, site/docs/reference/Connectors/materialization-connectors/databricks.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1425)
=> Update delay doc updates- warehouse materializations

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/linkedin-pages.md
This adds the docs for the new connector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1433)
=> Add docs LinkedIn Pages connector and its configuration

Makefile
- run `codesign` on binaries on macOS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1436)
=> make: codesign binaries on mac

examples/derive-patterns/join-outer.flow.yaml
Adds an example of doing an outer join using a sql derivation. We've been asked about this several times, so I thought it would help to have an example we can link to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1446)
=> examples: add an example of outer join using a sql derivation

site/docs/reference/Connectors/capture-connectors/mongodb.md
Doc updates per https://github.com/estuary/connectors/pull/1466
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1447)
=> docs: update source-mongodb for incremental backfills

site/docs/getting-started/tutorials/postgresql_cdc_to_snowflake.md
Update the Tutorial based on comments from @willdonnelly. Thanks for the review!
[The tutorial](https://docs.estuary.dev/getting-started/tutorials/postgresql_cdc_to_snowflake/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1454)
=> docs: Update PostgreSQL CDC to Snowflake tutorial with technical details.

site/docs/reference/Connectors/capture-connectors/hubspot-real-time.md
Doc updates per https://github.com/estuary/connectors/pull/1549
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1463)
=> docs: update hubspot real-time docs

Cargo.lock, crates/dekaf/Cargo.toml, crates/dekaf/src/lib.rs, crates/dekaf/src/main.rs, crates/dekaf/src/read.rs, crates/dekaf/src/registry.rs, crates/dekaf/src/session.rs, crates/dekaf/src/topology.rs, crates/gazette/src/journal/read_json_lines.rs, crates/simd-doc/src/ffi/mod.rs, crates/simd-doc/src/ffi/simd-doc.hpp, crates/simd-doc/src/lib.rs, crates/simd-doc/src/tests/fixtures.rs, crates/simd-doc/src/tests/fuzz.rs, crates/simd-doc/src/tests/mod.rs, crates/simd-doc/src/transcoded.rs, crates/simd-doc/tests/parser_perf.rs
Please see individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1461)
=> dekaf: refresh tokens, deletes, performance, and fixes

site/docs/guides/howto_join_two_collections_typescript.md
How-to guide on joining two collections in TypeScript.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1471)
=> docs: How-to guide for joining two collections in TypeScript

site/docs/guides/derivation_tutorial_sql.md
Add short guide for simple SQL derivations. This is a how-to guide that to showcase how to write & publish a simple SQL derivation and is built for people to follow along using the demo data flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1468)
=> docs: Add SQL derivation how-to guide

site/docs/reference/Connectors/materialization-connectors/amazon-redshift.md
A small documentation update per https://github.com/estuary/connectors/pull/1551
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1464)
=> materialize-redshift: update docs for case sensitive identifiers

site/docs/reference/Connectors/capture-connectors/PostgreSQL/Supabase.md
Adds a short section to the Supabase docs discussing connection poolers and how to get a direct connection address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1482)
=> docs/PostgreSQL/Supabase: More details on direct connections

.github/workflows/main.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1491)
=> Skip CI for just doc changes

crates/flowctl/src/controlplane.rs, crates/flowctl/src/local_specs.rs, crates/flowctl/src/raw/mod.rs
Ensure we're surfacing an error from LiveCatalog resolution. Remove LiveCatalog as a result from local_specs::validate() because no callers actually care about it.
Extend Client to track whether it's authenticated or not, and then update the flowctl Resolver to no-op resolutions for unauthenticated clients instead of returning an error.
- - - …
=> crates/flowctl: improve handling for unauthenticated clients (for CI)

crates/agent/src/integration_tests/locking_retries.rs, crates/validation/src/errors.rs, crates/validation/tests/snapshots/transition_tests__insert_but_already_exists.snap, crates/validation/tests/snapshots/transition_tests__update_but_does_not_exist.snap
- the original error is too technical for most users to understand what it means
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1498)
=> validation: more intuitive error message for expected pub

site/docs/getting-started/tutorials/real-time-cdc-with-mongodb.md, site/package-lock.json, site/package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1492)
=> docs: Embed video in tutorial for MongoDB connector

site/package-lock.json, site/package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1490)
=> docs: Upgrade Docusaurus to latest version

crates/doc/src/shape/widen.rs
Previously, the schema inference logic could silently swallow change detection for integer locations which are widenend to fractional values.
Fixes #1522 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1523)
=> crates/doc: properly identify integer => numeric schema changes

crates/agent/src/discovers.rs
Fixes #1521 
Background discovers get prioritized behind interactive publications, so it's possible for an interactive publication to update the endpoint config after the `discovers` row has already been created but before it's been processed. This detects that condition and bails, so we can try again on the next auto-discover.
I tested this manually, by creating `discovers` rows and modifying the endpoint config, and getting the expected error on the auto-discover. I also tested that regular auto-discovers still work when the endpoint isn't modified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1524)
=> agent: prevent auto-discovers overwriting endpoint

site/docs/reference/Connectors/materialization-connectors/Snowflake.md
Documentation update for estuary/connectors#1725. Additionally, I reordered the properties in the Endpoint list to reflect the order in the UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1526)
=> docs: update materialize-snowflake for optional account

Cargo.lock, crates/derive-sqlite/Cargo.toml, crates/derive-sqlite/src/connector.rs
Rather than using serde_json.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1534)
=> derive-sqlite: switch to using simd_doc::Parser for parsing documents

crates/agent/src/controllers/materialization.rs, crates/agent/src/integration_tests/dependencies_and_activations.rs
The materialization controller would fail to retry publications if they failed for reasons other than unsatisfiable constraints. This plugs the hole, and adds a publication failure/retry to the `dependencies_and_activations` integration tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1533)
=> agent: fix retry of materialization publications

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/google-pubsub.md
Creates documentation for the new `source-google-pubsub` connector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1541)
=> docs: source-google-pubsub

sso_readme.md, supabase/attrMaps/auth0_com.json
These attribute mappings are updated via the CLI and stored in Supabase DB. However, an easy way to update them is with a CLI command that points to the file.
N/A
N/A
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1538)
=> Add SSO related `attribute mapping` files into Supabase directory

site/docs/reference/Connectors/capture-connectors/zendesk-support.md
Doc updates for estuary/connectors#1779. The list of supported resources & bindings were updated & sorted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1543)
=> docs: update source-zendesk-support

site/docs/reference/Connectors/materialization-connectors/Snowflake.md
Doc updates for https://github.com/estuary/connectors/pull/1728
N/A
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1544)
=> docs: update materialize-snowflake docs for timestamp column changes

crates/doc/src/shape/widen.rs
Previously, we would map `32.0` or `100.0` or `3.14159e100` into `type: integer`, because they have a zero'd out fractional component. While _technically_ this is correct, in practice there's a big difference between the first examples and the last: `3.14159e100` cannot fit into a native 64-bit integer representation.
This is a problem downstream because materializations use `type: integer` as an indication to use a native integer representation, and then fail when attempting to fit the float into such a column.
Instead, infer such values to be `number` if they're too big to fit into a native integer. …
=> doc: non-fractional floats which exceed integer ranges are numbers

site/docs/reference/Connectors/capture-connectors/OracleDB/OracleDB.md
- Documentation for the first version of Oracle connector (https://github.com/estuary/connectors/pull/1660)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1560)
=> docs: source-oracle first version

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/pendo.md
New docs for estuary/connectors#1826. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1568)
=> docs: create source-pendo

site/docs/reference/Connectors/capture-connectors/PostgreSQL/neon-postgres.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1569)
=> docs: fix neon variant doc page

site/docs/reference/Connectors/capture-connectors/PostgreSQL/neon-postgres.md, site/docs/reference/allow-ip-addresses.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1575)
=> docs: ip allowlist reference & fix links in Neon docs

site/docs/reference/Connectors/README.md, site/docs/reference/Connectors/dekaf/README.md, site/docs/reference/Connectors/dekaf/_category_.json, site/docs/reference/Connectors/dekaf/dekaf-tinybird.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1578)
=> docs: Add Tinybird Dekaf integration docs

site/docs/guides/dekaf_reading_collections_from_kafka.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1582)
=> docs: Add note about beta status for Dekaf

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/pendo.md
Doc updates for estuary/connectors#1863. Rebuilt `source-pendo` with the Estuary CDK and added event streams.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1593)
=> docs: update source-pendo

.github/workflows/flow-web.yaml, crates/agent-sql/Cargo.toml, crates/gazette/src/lib.rs, crates/models/Cargo.toml, crates/models/src/id.rs, crates/models/src/references.rs, supabase/pending/data_planes_prod.sql
See individual commits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1596)
=> additional migration edits and un-break flow-web crate

go/runtime/capture.go, go/runtime/derive.go, go/runtime/materialize.go, go/runtime/task.go
Most initialization or authorization errors happen during term initialization. If an error occurs, fail-fast to cancel all term-related work like journal listings and reads.
This dramatically squelches log noise from failed RBAC checks.
- - - …
=> go/runtime: cancel task term if we fail to RestoreCheckpoint

site/docs/reference/Connectors/materialization-connectors/amazon-s3-iceberg.md
Docs for https://github.com/estuary/connectors/pull/1886
Closes https://github.com/estuary/connectors/issues/1885
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1606)
=> docs: materialize-s3-iceberg REST catalog

crates/agent/src/api/authorize.rs, go/runtime/authorizer.go, go/runtime/capture.go, go/runtime/connector_proxy.go, go/runtime/derive.go, go/runtime/testing.go
See individual commits.
No changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1611)
=> stack of small fast-follows from release of federated data-planes

site/docs/reference/Connectors/capture-connectors/zendesk-support.md
Doc updates for [estuary/connectors#1895](https://github.com/estuary/connectors/pull/1895).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1612)
=> docs: source-zendesk-support ticket_metrics cursor

site/docs/guides/dekaf_reading_collections_from_kafka.md, site/docs/guides/flowctl/create-derivation.md, site/docs/guides/flowctl/edit-draft-from-webapp.md, site/docs/guides/how_to_generate_refresh_token.md, site/docs/reference/Connectors/dekaf/README.md, site/docs/reference/Connectors/dekaf/dekaf-bytewax.md, site/docs/reference/Connectors/dekaf/dekaf-imply.md, site/docs/reference/Connectors/dekaf/dekaf-materialize.md, site/docs/reference/Connectors/dekaf/dekaf-singlestore.md, site/docs/reference/Connectors/dekaf/dekaf-startree.md, site/docs/reference/Connectors/dekaf/dekaf-tinybird.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1614)
=> docs: Add Dekaf integrations to docs

crates/agent/src/api/authorize.rs, go.mod, go.sum
This is a stack of fast-follows to address issues or opportunities observed in production, related to the federated data-planes roll-out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1615)
=> configurable gRPC server limits, reduced log noise, and randomize expirations

site/docs/concepts/advanced/evolutions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1551)
=> docs: Add docs for onIncompatibleSchemaChange

site/docs/reference/Connectors/capture-connectors/bigquery-ga4-native.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1553)
=> docs: Add docs for GA4 native BigQuery connector

.github/workflows/main.yml, crates/agent/src/proxy_connectors.rs, crates/runtime/src/container.rs, crates/runtime/src/lib.rs, go.mod, go.sum
See individual commits. This fixes the build after a dependabot merge, quiets logging, and fixes a message size limit issue in production during some Discover RPCs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1617)
=> stack of minor fixes

site/docs/reference/Connectors/capture-connectors/MySQL/singlestore-batch.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1624)
=> docs: Add SingleStore batch variant docs

.devcontainer/release.Dockerfile, crates/models/src/raw_value.rs
* Add packages required by podman for some containers
* Update `models::RawValue` such that it can never contain newlines
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1625)
=> .devcontainer/release.Dockerfile: add additional podman packages & newline fix

site/docs/reference/Connectors/capture-connectors/PostgreSQL/neon-postgres.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1646)
=> docs: Minor fixes for Neon docs

site/docs/reference/Connectors/capture-connectors/mongodb.md
Doc updates for https://github.com/estuary/connectors/pull/1956
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1647)
=> docs: update source-mongodb docs for batch mode

site/docs/reference/Connectors/capture-connectors/netsuite-suitetalk.md
To point users to more help with debugging suiteql permissions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1652)
=> docs: add suitetalk permission link

supabase/migrations/64_refresh_views.sql
Confirmed to not break anything on a local stack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1649)
=> supabase: add new columns to live_specs_ext and publication_specs_ext views

site/docs/reference/Connectors/materialization-connectors/databricks.md
- We had a customer ask how can they use service principal tokens for the Databricks materialization. I figured it out yesterday and here are docs to help users do this on their own
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1673)
=> docs/databricks: how to create a token for service principals

go/runtime/flow_consumer.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1713)
=> consumer: read --flow.network from FLOW_NETWORK env variable

crates/simd-doc/src/ffi/simd-doc.hpp, crates/simd-doc/src/lib.rs, crates/simd-doc/src/tests/fixtures.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1734)
=> simd-doc: Add failing test for parsing incomplete rows

crates/models/src/schemas.rs, crates/validation/tests/scenario_tests.rs
Users occasionally get confusing error messages when they try to publish a collection spec where the `readSchema` contains an incorrect `flow://write-schema` definition. This updates our validation logic to always overwrite any inlined write schema definition, so we can ensure it is correct.
Normally, our response would probably be "just don't add that def", but the control plane previously used to do that inlining, and there's still some collections for which the inlined defs have not yet been removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1741)
=> validation: always overwrite inlined write schema

site/docs/reference/Connectors/materialization-connectors/mongodb.md
Documentation updates for https://github.com/estuary/connectors/pull/2092
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1751)
=> docs: add note for materialize-mongodb `_id` field renaming

scripts/install-connector-local.sh
Fixes https://github.com/estuary/flow/issues/1755 by adding the `recommended` column to the insert.
N/A
N/A
Does not impact production systems.
For locals only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1756)
=> Adding `recommended` column to connector install script

site/docs/reference/Connectors/materialization-connectors/http-webhook.md
Documentation updates for https://github.com/estuary/connectors/pull/2128.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1766)
=> docs: update materialize-webhook config options

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1765)
=> docs: Add get started section to main README

site/docs/reference/Connectors/capture-connectors/genesys.md
Documentation for the new `source-genesys` connector merged in https://github.com/estuary/connectors/pull/2136.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1770)
=> docs: create source-genesys

site/docs/reference/Connectors/capture-connectors/front.md
Documentation for the `source-front` connector merged in https://github.com/estuary/connectors/pull/2150.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1777)
=> docs: create source-front

site/docs/reference/Connectors/capture-connectors/apache-kafka.md
Updates for https://github.com/estuary/connectors/pull/2089, mostly related to configuring schema registry on the capture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1778)
=> docs: source-kafka doc updates

go/network/frontend.go, go/network/sni.go
We've seen a few legacy clients that don't support HTTP/2 or ALPN negotiation. Improve the connector networking frontend to support HTTP/1.1 transports for clients that don't support HTTP/2, or don't support ALPN at all, while still preferring HTTP/2 where possible.
In particular, this lets connector networking work seamlessly with NodeJS clients that are using the old "https" NodeJS module instead of the newer "http2" module. This is less performant than HTTP/2, but metrics can indicate which tasks are using large numbers of user connections / TLS handshakes.
(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sh …
=> go/network: improve support for clients lacking ALPN

crates/agent/src/proxy_connectors.rs
Allows setting the agent's connector timeout via the `FLOW_CONNECTOR_TIMEOUT` env variable, so we can change it without needing to re-compile the whole application.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1805)
=> agent: read connector timeout from env

crates/runtime/src/unary.rs, go.mod, go.sum
Also remove unused import
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1810)
=> go.mod: update gazette pin to dc2b9ab

site/docs/concepts/materialization.md
Docs for feature that was recently shipped. Discussion here: https://estuaryworkspace.slack.com/archives/C02G25WJCNS/p1733421953163009
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1812)
=> Add docs for default schema names and delta updates

sso_readme.md, supabase/attrMaps/auth0_com.json
https://github.com/estuary/flow/issues/1818
- Removed the attribute mapping files
- Updated the read me
N/A
N/A
Please take a look in 1password and make sure things generally make sense in there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1817)
=> Remove `sso` attribute mapping files and update docs

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/intercom-native.md
Doc updates for https://github.com/estuary/connectors/pull/2204 as well as some other new connectors I forgot to add to the Capture Connectors README.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1828)
=> docs: source-intercom-native

site/docs/reference/Connectors/capture-connectors/OracleDB/OracleDB.md, site/docs/reference/Connectors/capture-connectors/OracleDB/flashback.md
- Update docs regarding required grants for Oracle to work
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1834)
=> docs/oracle: fix grants for flashback and cdc

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/asana.md, site/docs/reference/Connectors/capture-connectors/jira-native.md, site/docs/reference/Connectors/capture-connectors/stripe-realtime.md, site/docs/reference/Connectors/capture-connectors/stripe.md
We’re missing reference documentation for several connectors. This update adds new docs for the Asana, Jira Native, and Stripe Real-time (Stripe Native) connectors. It also modifies the existing Jira and Stripe docs to note that newer connectors are available.
Will add new pages at the following paths:
* https://docs.estuary.dev/reference/Connectors/capture-connectors/asana/
* https://docs.estuary.dev/reference/Connectors/capture-connectors/jira-native/
* https://docs.estuary.dev/reference/Connectors/capture-connectors/stripe-realtime/
- - - …
=> Docs: Add Asana, Jira Native, and Stripe Real-time reference docs

site/docs/reference/Connectors/capture-connectors/braintree.md, site/docs/reference/Connectors/capture-connectors/intercom-native.md, site/docs/reference/Connectors/capture-connectors/mixpanel.md
Documentation updates for:
- https://github.com/estuary/connectors/pull/2208
- https://github.com/estuary/connectors/pull/2244
- https://github.com/estuary/connectors/pull/2256
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1860)
=> docs: source-{braintree, intercom, mixpanel}-native updates

site/docs/reference/Connectors/capture-connectors/OracleDB/OracleDB.md, site/docs/reference/Connectors/capture-connectors/OracleDB/flashback.md
- Docs for setting up a user in container databases for Oracle
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1843)
=> docs: OracleDB container database setup

site/docs/reference/Connectors/materialization-connectors/BigQuery.md
Docs for https://github.com/estuary/connectors/pull/2276
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1872)
=> docs: update docs for materialize-bigquery storage read API

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/shopify-native.md
Docs for https://github.com/estuary/connectors/pull/2277.
I named the docs "Shopify (GraphQL)" to distinguish it from the imported `source-shopify` connector. Once the native connector has the same streams/captures the same data as the imported once, we could consider renaming the import to "Shopify (deprecated)" and the native one to just "Shopify".
- - - …
=> docs: initial docs for source-shopify-native

.github/workflows/deploy-data-plane-controller.yaml, crates/data-plane-controller/src/controller.rs
- Based on this: https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#set-configuration-using-environment-variables
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1890)
=> data-plane-controller: add Azure secret env variables

site/docs/reference/Connectors/capture-connectors/intercom-native.md
Doc updates for https://github.com/estuary/connectors/pull/2281.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1882)
=> docs: add `tickets` stream for source-intercom-native

site/docs/reference/Connectors/capture-connectors/OracleDB/OracleDB.md
- clarify where to run queries in CDB databases
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1889)
=> oracle: cdb instructions for running the queries

site/docs/reference/Connectors/capture-connectors/MariaDB/amazon-rds-mariadb.md, site/docs/reference/Connectors/capture-connectors/MySQL/amazon-rds-mysql.md, site/docs/reference/Connectors/capture-connectors/OracleDB/OracleDB.md, site/docs/reference/Connectors/capture-connectors/OracleDB/flashback.md, site/docs/reference/Connectors/capture-connectors/PostgreSQL/amazon-rds-postgres.md, site/docs/reference/Connectors/capture-connectors/PostgreSQL/postgres-batch.md, site/docs/reference/Connectors/capture-connectors/SQLServer/amazon-rds-sqlserver.md, site/docs/reference/Connectors/capture-connectors/SQLServer/sqlserver.md, site/docs/reference/Connectors/capture-connectors/aircall.md, site/docs/reference/Connectors/capture-connectors/google-drive.md, site/docs/reference/Connectors/capture-connectors/google-pubsub.md, site/docs/reference/Connectors/capture-connectors/linkedin-pages.md, site/docs/reference/Connectors/capture-connectors/netsuite-suiteanalytics.md, site/docs/reference/Connectors/capture-connectors/pinterest.md, site/docs/reference/Connectors/capture-connectors/woocommerce.md
This update collects various changes to links, including adding or fixing the connector's Docker image link and updating links to external docs, like AWS. Also includes some other minor typo fixes in the connector pages.
Various capture connector docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1900)
=> Docs: Update connector links

site/docs/reference/Connectors/capture-connectors/OracleDB/OracleDB.md
- A few points that came up during Launchmetrics' setup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1907)
=> docs: OracleDB cdc docs improvements

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/zendesk-support-native.md
Docs for https://github.com/estuary/connectors/pull/2309 and https://github.com/estuary/connectors/pull/2331.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1908)
=> docs: source-zendesk-support-native

site/docusaurus.config.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1922)
=> Add design elements to AI chat widget

site/docs/reference/Connectors/materialization-connectors/amazon-s3-csv.md, site/docs/reference/Connectors/materialization-connectors/azure-fabric-warehouse.md, site/docs/reference/Connectors/materialization-connectors/google-gcs-csv.md
Some baseline docs for the new fabric warehouse materialization.
See https://github.com/estuary/connectors/pull/2300
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1901)
=> docs: doc uppdates for materialize-azure-fabric-warehouse

go.mod, go.sum
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1926)
=> go.mod: bump gazette pin to fa8573f

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/google-analytics-data-api-native.md
Docs for the initial version of `source-google-analytics-data-api-native` introducted in https://github.com/estuary/connectors/pull/2360.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1927)
=> docs: source-google-analytics-data-api-native

.github/workflows/control-ci-cd.yaml, .github/workflows/derive-typescript.yaml, .github/workflows/docs-ci-previews.yaml, .github/workflows/docs-ci-prod.yaml, .github/workflows/flowctl-release.yaml, .github/workflows/main.yml
This updates the GitHub workflows to use later versions of ubuntu as GitHub is deprecating the use of ubuntu-20.04 in the near future.
It does not touch the dev container, as I'm not sure any actually uses it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1930)
=> Update GitHub Workflows

Cargo.lock, crates/flow-web/Cargo.toml
Bump version to push a new package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1941)
=> flow-web: bump to 0.5.11

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/zendesk-support-native.md, site/docs/reference/Connectors/capture-connectors/zendesk-support.md
Doc updates for https://github.com/estuary/connectors/pull/2407.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1943)
=> docs: added streams to source-zendesk-support-native

site/docs/reference/Connectors/capture-connectors/braintree.md
Doc updates for https://github.com/estuary/connectors/pull/2437.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1963)
=> docs: add `schedule` resource config setting to braintree docs

site/docs/reference/backfilling-data.md
This bit of documentation could very easily be read as implying that users _ought to_ follow a more complicated process to pause writes and perform an only-changes backfill when upgrading PostgreSQL.
My perspective on the matter is that just hitting the "Backfill" button should always be our #1 recommendation because it's easy for users and is the most guaranteed-to-work-in-all-cases option. While many users probably will want the more complicated approach, I want us to be clear that this is an _optimization_ to reduce the time and data usage of a backfill, where the user is deliberately making a tradeoff of doing more setup work and manually making certain guarantees in order to avoid the full backfill.
- - - …
=> docs/backfilling-data: Recommend plain backfills

site/docs/reference/Connectors/capture-connectors/OracleDB/flashback.md, site/docs/reference/Connectors/capture-connectors/OracleDB/oracle-batch.md
Inspired by postgres batch docs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1967)
=> docs: add Oracle Batch Query connector docs

crates/data-plane-controller/src/controller.rs
- Introduced this infinite loop when refactoring this bit of code, was going to Ansible after PulumiUp2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1977)
=> data-plane-controller: fix infinite loop

Cargo.lock, crates/data-plane-controller/Cargo.toml, crates/data-plane-controller/src/controller.rs, crates/data-plane-controller/src/dry_run_fixture.json, crates/data-plane-controller/src/lib.rs, crates/data-plane-controller/src/repo.rs, crates/data-plane-controller/src/snapshots/data_plane_controller__stack__test__simulate_chained_replace_release.snap, crates/data-plane-controller/src/snapshots/data_plane_controller__stack__test__simulate_chained_surge_releases.snap, crates/data-plane-controller/src/snapshots/data_plane_controller__stack__test__simulate_etcd_rollout.snap, crates/data-plane-controller/src/snapshots/data_plane_controller__stack__test__simulate_gazette_and_reactor_rollout.snap, crates/data-plane-controller/src/snapshots/data_plane_controller__stack__test__simulate_noop_rollout.snap, crates/data-plane-controller/src/stack.rs, crates/data-plane-controller/src/state_fixture.json, supabase/migrations/20250225204931_data_plane_releases.sql
A Rollout is an attachement of a Deployment which performs incremental,
stepped updates of its `desired` replicas towards a `target`.
Rollouts are stepped atomically across all Deployments of a data-plane
model, which means we can coordinate a release by creating appropriate
Rollouts (scaling one deployment down, and another up; "surge" vs
"replace").
Also introduce a data-plane Release and a corresponding SQL table to
hold them. The data-plane-controller will look for a release which
matches a current Deployment, and if found will create a new Deployment
with Rollout attachments to enact it.
**Workflow Steps:**
Attach a rollout directly to a Deployment, as:
```
"rollout": {
"target": 7,
"step": 3
}
```
This will step the deployment up to 7 desired replicas, in increments …
=> data-plane-controller: add releases and rollouts

site/docs/reference/Connectors/materialization-connectors/Dekaf/tinybird.md
Reorders the deletions section in the Tinybird docs somewhat to clarify that CDC deletion mode is required and streamlines instructions.
[Tinybird Dekaf docs](https://docs.estuary.dev/reference/Connectors/materialization-connectors/Dekaf/tinybird/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1987)
=> Docs: Fix Tinybird deletion instructions

site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/amazon-s3-iceberg.md, site/docs/reference/Connectors/materialization-connectors/apache-iceberg.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1991)
=> docs: materialize-iceberg

site/docs/getting-started/getting-started.md, site/docs/reference/Connectors/materialization-connectors/azure-fabric-warehouse.md, site/docs/reference/Connectors/materialization-connectors/motherduck.md, site/docusaurus.config.js
Embed new videos into docs pages. Add more links to resources on home page and in the footer, such as to Slack and YouTube.
* [Home page](https://docs.estuary.dev/)
* [Fabric connector](https://docs.estuary.dev/reference/Connectors/materialization-connectors/azure-fabric-warehouse/)
* [MotherDuck connector](https://docs.estuary.dev/reference/Connectors/materialization-connectors/motherduck/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/1993)
=> Docs: Embed/link to more resources

site/docs/reference/Connectors/capture-connectors/google-analytics-data-api-native.md
Documentation updates for https://github.com/estuary/connectors/pull/2516.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2003)
=> docs: source-google-analytics-data-api-native add lookback window setting

crates/data-plane-controller/src/controller.rs, crates/data-plane-controller/src/data_plane_fixture.json, crates/data-plane-controller/src/dry_run_fixture.json, crates/data-plane-controller/src/stack.rs, supabase/migrations/20250313160612_data_plane_azure_link.sql
- Support parsing of azure private links, add test to make sure it works as expected
- Add column for `azure_link_endpoints` to `data_plane` and populate it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2007)
=> data-plane-controller: parse azure private links

crates/validation/src/materialization.rs
Eases the validation of materialization connector resource spec schemas, in the specific case where the materialization does not have a `sourceCapture`.
We validate that these annotations exist because they're required in order to automatically add bindings to materialization specs. But not all connectors have a reasonable way to support this. For example, the slack connector requires users to get a channel ID to use as part of the resource config. This has prevented any publications of specs for the materialize-slack connector.
So this commit changes the validation logic to only validate the resource spec schema annotations if the materialization actually defines a `sourceCapture`.
- - - …
=> validation: allow missing x-collection-name annotation

site/docs/reference/Connectors/materialization-connectors/apache-iceberg.md
Adds some basic documentation for setting up materialize-iceberg to materialize to s3 table buckets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2029)
=> docs: basic docs for materialize-iceberg with s3 table buckets

site/docs/concepts/flowctl.md, site/docs/getting-started/tutorials/continuous-materialized-view.md, site/docs/guides/flowctl/create-derivation.md, site/docs/guides/flowctl/troubleshoot-task.md, site/docs/reference/Connectors/capture-connectors/PostgreSQL/google-cloud-sql-postgres.md, site/docs/reference/Connectors/capture-connectors/amazon-sqs.md, site/docs/reference/Connectors/capture-connectors/bigquery-batch.md, site/docs/reference/Connectors/capture-connectors/genesys.md, site/docs/reference/Connectors/capture-connectors/github.md, site/docs/reference/Connectors/capture-connectors/google-ads.md, site/docs/reference/Connectors/capture-connectors/netsuite-suiteanalytics.md, site/docs/reference/Connectors/materialization-connectors/Dekaf/startree.md, site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/azure-fabric-warehouse.md, site/docs/reference/time-travel.md, site/docs/reference/working-logs-stats.md
Rollup of various improvements to docs:
- Updated info on `flowctl` commands and usage
- Fixed a couple broken links
- Embedded new NetSuite video
- Minor typo fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2033)
=> Docs: flowctl updates, typo fixes, add new video

site/docs/reference/Connectors/capture-connectors/stripe-realtime.md
Doc updates for https://github.com/estuary/connectors/pull/2646.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2062)
=> docs: add `Events` to `source-stripe-native`

crates/runtime/src/materialize/task.rs
Increase the truncation cut-off for BigQuery from 1000 => 1500.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2061)
=> runtime: adjust BigQuery SerPolicy bound

site/docs/reference/Connectors/materialization-connectors/amazon-dynamodb.md
See https://github.com/estuary/connectors/pull/2690
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2086)
=> docs: updated materialize-dynamodb to remove delta updates config

site/docs/getting-started/getting-started.md, site/docs/getting-started/support.md
This update adds instructions on sharing data with Estuary during troubleshooting sessions if access is not already granted.
Also updates the overview video as a bonus.
Will add a new page at: https://docs.estuary.dev/getting-started/support/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2099)
=> Docs: Add support information

crates/runtime/src/container.rs
- CONNECTOR_MEMORY_LIMIT
- CONNECTOR_CPU_LIMIT
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2101)
=> runtime: allow connector limits to be configured through env

site/docs/getting-started/azureAuthorize.jsx, site/docs/getting-started/installation.mdx, site/docs/guides/byoc/README.md, site/docs/guides/byoc/azure.md
Developers have been having some difficulties with a couple of our Azure resources, especially around connecting Estuary's Azure applications to their accounts. This update clarifies what developers should expect and makes the storage bucket tenant field more prominent:
* [Azure cloud storage configuration](https://docs.estuary.dev/getting-started/installation/)
* [Azure BYOC instructions](https://docs.estuary.dev/guides/byoc/azure/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2104)
=> Docs: Improve Azure connection instructions

site/docs/reference/Connectors/materialization-connectors/motherduck.md
See https://github.com/estuary/connectors/pull/2720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2103)
=> docs: update materialize motherduck docs for GCS staging buckets

site/docs/reference/Connectors/capture-connectors/google-analytics-data-api-native.md
Doc updates for https://github.com/estuary/connectors/pull/2719.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2098)
=> docs: ga4-data-api-native dimension & metric limits

site/docs/guides/connect-network.md
This update adds information about using AWS PrivateLink with a private deployment, providing extra details around setting up with MongoDB, which requires some alternate steps.
Updates the [Secure connections](https://docs.estuary.dev/guides/connect-network/) guide
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2124)
=> Docs: Add AWS PrivateLink instructions and variations

go/shuffle/read.go
This ensures correct handling of the `name` meta-label.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2134)
=> shuffle: use LabelSetExt prior to matching source journal labels

site/docs/getting-started/azureAuthorize.jsx, site/docs/getting-started/installation.mdx
- We have a new redirect URI now for Azure OAuth process
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2146)
=> docs: update azure redirect uri

crates/data-plane-controller/src/stack.rs
When doing replacement releases, we start with `desired: 0, current: 0`, so we must allow that when doing rollouts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2148)
=> dpc: allow desired: 0, current: 0 when there is a rollout

site/docs/reference/Connectors/capture-connectors/hubspot-real-time.md
Doc updates for https://github.com/estuary/connectors/pull/2797.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2156)
=> docs: remove access token auth for hubspot native

site/docs/getting-started/installation.mdx, site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/SQLServer/sqlserver-batch.md, site/docs/reference/Connectors/capture-connectors/shopify-native.md, site/docs/reference/Connectors/capture-connectors/shopify.md, site/docs/reference/Connectors/materialization-connectors/Dekaf/dekaf.md
Miscellaneous updates, especially to keep connector information up-to-date:
* Adds documentation for SQL Server Batch connector
* Updates Shopify GraphQL connector data streams
* Embeds video in Dekaf connector docs
* Adds missing connectors to capture connector overview
* And adjusts storage bucket docs
Various
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2155)
=> Docs: Update (mostly) connector information

site/docs/guides/flatten-array.md
This adds @SeanWhelan's guide on flattening an array field to our docs.
Will add a new page at: https://docs.estuary.dev/guides/flatten-array/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2149)
=> Docs: Add guide to flatten an array

site/docs/reference/Connectors/materialization-connectors/Dekaf/dekaf.md, site/docs/reference/Connectors/materialization-connectors/Dekaf/risingwave.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2157)
=> Add RisingWave docs

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/sage-intacct.md
See https://github.com/estuary/connectors/pull/2776
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2141)
=> docs: basic documentation for Sage Intacct

site/docs/reference/Connectors/capture-connectors/pendo.md
Documentation updates for https://github.com/estuary/connectors/pull/2799.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2160)
=> docs: add TrackType and Visitor streams to source-pendo

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/outreach.md
Documentation for the new `source-outreach` capture connector introduced in https://github.com/estuary/connectors/pull/2709.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2097)
=> docs: source-outreach

.github/workflows/deploy-data-plane-controller.yaml
- Currently deploying data-plane-controller is manual, with this change it becomes automatic on merges to master which have modified either the deploy workflow or `crates/data-plane-controller`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flo …
=> data-plane-controller: automatically deploy on changes

site/docs/reference/Connectors/materialization-connectors/README.md, site/docs/reference/Connectors/materialization-connectors/amazon-s3-iceberg.md, site/docs/reference/Connectors/materialization-connectors/azure-blob-parquet.md, site/docs/reference/Connectors/materialization-connectors/google-gcs-parquet.md
Docs for https://github.com/estuary/connectors/pull/2842
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2172)
=> docs: add docs for azure blob storage parquet materialization

site/docs/reference/Connectors/capture-connectors/Salesforce/salesforce-native.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2178)
=> Add features to Salesforce connector docs

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/looker.md
Documentation for https://github.com/estuary/connectors/pull/2808.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2162)
=> docs: basic documentation for source-looker

site/docs/reference/Connectors/capture-connectors/google-ads.md
Documentation updates for https://github.com/estuary/connectors/pull/2922
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2219)
=> docs: source-google-ads add primary key for custom GAQL streams

site/docs/reference/Connectors/capture-connectors/outreach.md, site/docs/reference/Connectors/capture-connectors/zendesk-support-native.md
Doc updates for https://github.com/estuary/connectors/pull/2916.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2223)
=> docs: source-{zds-native,outreach} OAuth updates

site/docs/reference/Connectors/capture-connectors/shopify-native.md
Doc updates for:
- https://github.com/estuary/connectors/pull/2948
- https://github.com/estuary/connectors/pull/2668
There may be more permissions required when authenticating with access tokens from a custom app, but we can add more to this list as we discover the minimum required permissions.
- - - …
=> docs: source-shopify-native permissions for new streams & conditionally discover `customers`

crates/agent/src/api/create_data_plane.rs
- `sqlx` treats `serde_json::Value` values as `JSONB` by default, and TIL in certain circumstances Postgres cannot automatically convert from `jsonb` to `json` when inserting data (and `sqlx` did not complain about this during compile time checks), so we got:
```
PgDatabaseError { severity: Error, code: "42846", message: "CASE/WHEN could not convert type jsonb to json", detail: None, hint: None, position: Some(Original(1012)), where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("parse_coerce.c"), line: Some(1548), routine: Some("coerce_to_common_type") }
```
I simplified the code by getting rid of RawValue, and added an explicit cast to `::json` in the SQL query. Tested this locally by calling `create-data-plane`, first able …
=> agent: fix create-data-plane

site/docs/reference/Connectors/capture-connectors/pendo.md
Documentation updates for https://github.com/estuary/connectors/pull/3010.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2251)
=> docs: source-pendo add `Account` stream

site/docs/reference/Connectors/capture-connectors/bing-ads.md
Documentation updates for https://github.com/estuary/airbyte/pull/335.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2255)
=> doc: source-bing-ads add lookback window setting

site/docs/reference/Connectors/capture-connectors/google-analytics-data-api-native.md
Documentation updates for https://github.com/estuary/connectors/pull/3025.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2258)
=> docs: source-ga4-native increase resource interval

site/docs/reference/Connectors/capture-connectors/intercom-native.md
Documentation updates for https://github.com/estuary/connectors/pull/3027.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2260)
=> docs: source-intercom-native add `search_page_size` config setting

site/docs/reference/Connectors/capture-connectors/snowflake.md
Documentation updates for https://github.com/estuary/connectors/pull/3023.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2256)
=> docs: source-snowflake add optional role input

crates/agent/src/controllers/materialization.rs
Eases a restriction on dekaf materializations, which prevented them from using source captures.  I'm not exactly sure why this restriction was still in place, but my recollection is that it was there because we didn't have a `connector_tags` row for dekaf materializations. We definitely have one now, though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2288)
=> agent: allow dekaf materializations to use source captures

site/docs/reference/Connectors/capture-connectors/hubspot-real-time.md
Documentation updates for https://github.com/estuary/connectors/pull/3099.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2306)
=> docs: source-hubspot-native add `forms` and `form_submissions` streams

site/docs/reference/Connectors/capture-connectors/README.md, site/docs/reference/Connectors/capture-connectors/google-play.md
Documentation for https://github.com/estuary/connectors/pull/3136.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2318)
=> docs: new connector source-google-play

site/docs/reference/Connectors/capture-connectors/Salesforce/salesforce-native.md
Documentation updates for https://github.com/estuary/connectors/pull/3180.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2343)
=> docs: source-salesforce-native add `UserPass` authentication option

site/docs/guides/derivation_tutorial_sql.md, site/docs/guides/iam-auth/azure.md, site/docs/private-byoc/byoc-deployments/aws-byoc.md, site/docs/private-byoc/byoc-deployments/azure-byoc.md, site/docs/private-byoc/byoc-deployments/gcp-byoc.md, site/docs/reference/Connectors/capture-connectors/klaviyo-native.md, site/docs/reference/Connectors/materialization-connectors/Dekaf/dekaf.md
Small rollup of typo fixes, especially across new docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2350)
=> Docs: Small typo fixes

crates/sources/src/inline.rs
Small fix to get local materializations working with inlined configurations using flowctl.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2351)
=> flowctl: fix inlining of local materialization config

crates/parser/src/format/mod.rs
This is intended to help diagnose issues with unexpected file content or parser behavior by logging out a small prefix of the file content when parsing fails.
This is only done when no records could be successfully parsed from the file. That's just because it's much easier to do that way, and still seems helpful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/estuary/flow/2367)
=> parser: print file content prefix when parsing fails completely

site/docs/reference/Connectors/materialization-connectors/Elasticsearch.md
Docs for https://github.com/estuary/connectors/pull/3303
=> docs: materialize-elasticsearch routing field configuration docs

crates/data-plane-controller/src/data_plane_fixture.json, crates/data-plane-controller/src/stack.rs
- add `dns_name` to AzurePrivateLink
=> dpc: support azure private link dns_name

crates/control-plane-api/src/server/update_l2_reporting.rs
=> update-l2-reporting: allow default_data_plane to be empty

crates/agent/src/controllers/executor.rs
We've seen a case where controllers fail to update their status due to null bytes being included in one of the columns.  I've not yet been able to pin down exactly how that's happening, but wanted to add a guard against null bytes in the error message, as that seems like the most likely suspect.  Also add some xtra logging to help pin down the issue.
=> agent: guard against null bytes in controller errors

crates/validation/src/lib.rs
The ops/ prefix is special as these specs exist in all data-planes. When validating existing ops/ specs, we now pass the current data_plane_id as explicit_plane to avoid errors about missing mapped data-planes.
For regular specs, we continue to pass None to allow walk_prefix to use the first storage mapping plane as a no-op placeholder, avoiding errors when data-planes are removed from mappings or intended for other specs.
**Notes for …
=> validation: use explicit data plane for ops/ prefix specs
